ext/RMagick/extconf.rb

From  #169
To check ImageMagick architectures
```file``` command:
```
$ file `which convert`
/usr/local/bin/convert: Mach-O 64-bit executable x86_64
```

set ARCHFLAGS appropriately for OSX (#169)

---

ext/RMagick/extconf.rb

When clean installation from ```gemhome/master```, ```rmagick/version.rb``` is not found.
If some old rmagick (e.g. 2.13.4) is installed, the ```rmagick/version.rb``` is loaded, so no build error.
on ruby < 1.9.2, there are no ```require_relative```. #154
on ruby >= 1.9.2, ```require_relative``` exists. #142

fix: in `require': cannot load such file -- rmagick/version (LoadError)

---

.travis.yml

Looks like ImageMagick updated their patch level from `6.8.9-6` to
`6.8.9-10`

Fix for ImageMagick 404

---

ext/RMagick/rmdraw.c

Fixed escaping of '%' sign in get_type_metrics

---

rmagick.gemspec

It seems in versions of Ruby prior to 2.x, calling `Gem::Version.new` with a frozen string as an argument will result in a RuntimeError, since the library will attempt to mutate the string.
It seems to be a very similar problem [to this](https://groups.google.com/forum/#!topic/merb/EdwOwo64erE).
In versions of Ruby above 2.x the Gem::Version library does a .dup on the object that comes in right away, so there it shouldn't be a problem.
Important to note is that reproducing after noticing it was problematic. With no Ruby versions at first in rbenv, I bumped into the issue (tried Ruby `1.9.3` first). When I resolved it by adding the changes proposed in the PR, the `bundle install` went through. On subsequent attempts to reproduce the issue (by removing the `.dup` from the two lines) …

Send in RUBY_VERSION.dup to Gem::Version

---

ext/RMagick/rmagick.c
ext/RMagick/rmagick.h
ext/RMagick/rmdraw.c
ext/RMagick/rmenum.c
ext/RMagick/rmfill.c
ext/RMagick/rmilist.c
ext/RMagick/rmimage.c
ext/RMagick/rminfo.c
ext/RMagick/rmmain.c
ext/RMagick/rmmontage.c
ext/RMagick/rmpixel.c
ext/RMagick/rmstruct.c
ext/RMagick/rmutil.c

From #176
I merely replaced `volatile VALUE X` with `RB_GC_GUARD(X)`.
(Perhaps some `RB_GC_GUARD` are unnecessary, but status quo for now)
> RB_GC_GUARD is only effective on the VALUE data type, not converted C data types.
> 3) “volatile” implementations may be buggy/inconsistent in some
compilers and architectures. RB_GC_GUARD is customizable for broken
systems/compilers without those without negatively affecting other
systems.
[Appendix E. RB_GC_GUARD to protect from premature GC](https://github.com/ruby/ruby/blob/trunk/doc/extension.rdoc#appendix-e-rb_gc_guard-to-protect-from-premature-gc)

replaced `volatile VALUE X` with `RB_GC_GUARD(X)`

---

lib/rmagick_internal.rb

Segfault Log:
https://travis-ci.org/gemhome/rmagick/jobs/60001052
segfault reproduction script (on Ruby 2.2.X):
```rb
require 'test/unit'
class SegfaultTest < Test::Unit::TestCase
def test_segfault
def create_img
local_img = Magick::Image.new(20, 20)
end
create_img
GC.stress = true
proc1 = proc do |which, id, addr, method|
assert(which == :c)
end
Magick.trace_proc = proc1
img = Magick::Image.new(777, 777)
end
end
```
If `local_img` is garbage collected in `Magick#trace_proc=`,
`Image#destroy!` and `Magick#trace_proc`(i.e. `proc1`) will be called **in the middle of `Magick#trace_proc=`**.
At this time, `Magick#trace_proc` might be not completely prepared yet,
so segmentation fault will be raised.
[Magick#trace_proc](http://www.imagemagick.org/RMagick/doc/magick.html#trace_ …

fixed segfault in `Magick#trace_proc=` for ruby 2.2.X

---

README.textile
before_install_linux.sh

[Job #404.20 - gemhome/rmagick - Travis CI](https://travis-ci.org/gemhome/rmagick/jobs/62917281)
repro script foo.rb(from test/Info.rb):
```rb
require 'rubygems'
monitor = proc do |mth, q, s|
puts s
true
end
img = Magick::Image.new(2000, 2000) { self.monitor = monitor }
img.resize!(20, 20)
img.monitor = nil
```
```sh
$ ruby -v
ruby 1.8.7 (2013-12-22 patchlevel 375) [x86_64-linux]
$ ruby foo.rb
40
40
40
40
foo.rb:6: stack level too deep (SystemStackError)
from foo.rb:10:in `call'
from foo.rb:10:in `resize!'
from foo.rb:10
foo.rb:6: [BUG] Segmentation fault
ruby 1.8.7 (2013-12-22 patchlevel 375) [x86_64-linux]
Aborted (core dumped)
```
Ruby 1.8 uses C stack. (Ruby 1.9 and later use RubyVM stack)
The cause for segfault might be that C stack size limit is too small.
Some …

Fix Ruby 1.8 segfault

---

ext/RMagick/rmilist.c
spec/rmagick/ImageList1_spec.rb

Fixed #202 and added tests
The cause is a loop in a linked list in `AppendImageToList`.
at rmilist.c:
```c
t = rb_ary_entry(images, x);
image = rm_check_destroyed(t);
AppendImageToList(&head, image);
```
`AppendImageToList` 1st call:
- head = images[0]
`AppendImageToList` 2nd call:
- images[0]->next = images[1]
- images[1]->prev = images[0]
`AppendImageToList` 3rd call:
- images[1]->next = images[2]
- images[2]->prev = images[1]
if images[0] and images[1] are identical:
- head = images[0] = images[1]
- images[0]->next = images[1] = images[0]
- images[1]->prev = images[0] = images[1]
then it hangs because of a loop in this linked list.

Fixed #202; Avoid a loop in linked list

---

ext/RMagick/extconf.rb

In Win64 ImageMagick 6.9.1-6, the version message is
>Version: ImageMagick 6.9.1--6 Q16 x64 2015-06-20 http://www.imagemagick.org
containing multiple hyphens. 
I don't know whether this notation is a bug or a feature of ImageMagick, but I think support for this notation is useful and not destructive

Accept `convert -version` format variation

---

.travis.yml
before_install_linux.sh
doc/ex/gravity.rb
lib/rvg/embellishable.rb
lib/rvg/misc.rb
lib/rvg/rvg.rb
lib/rvg/stretchable.rb
lib/rvg/transformable.rb
test/Magick.rb

I'm surprised to see a well known open source project with a red build for 4 months. I'm sure this will lead only to tears and misery and I think the time to fix it is well invested.
It wasn't even hard this time:
* Imagemagick doesn't offer `tar.gz` any more, so I changed it to download `tar.xz` instead
* I ran `rubocop -a`
Since no spec was failing after that, I removed everything from allowed failures.
I'd also remove Ruby 1.8 and 1.9 from Travis (and require 2.0 in the gemspec). [Quoting PragTob](https://twitter.com/PragTob/status/623172491301789696): 
> I don't think keeping compatibility with OLD gems/rubies is important. They are probably fine running an old major version of your gem too
But that's up to you to decide, I haven't changed it.

Fix the build

---

.editorconfig

@vassilevsky, @u338steven, @bf4
I'm thinking about refactoring the indentation style, based on:
https://github.com/styleguide/ruby
https://github.com/bbatsov/ruby-style-guide
So this first pull-request is adds an .editorconfig file to formalize the coding-style based on the guides above.

Add .editorconfig to make a default indentation style

---

ext/RMagick/extconf.rb

Related to #201
1. Call `pkg-config` instead of `Magick-config`, if `graphicsmagick-libmagick-dev-compat` is installed
This is because GraphicsMagick has `Magick-config` and it might be called.
[Ubuntu – File list of package graphicsmagick-libmagick-dev-compat/vivid/all](http://packages.ubuntu.com/en/vivid/all/graphicsmagick-libmagick-dev-compat/filelist)
1. Replace `convert` with `*-config` to get ImageMagick version
This is because GraphicsMagick has `convert` and it might be called.
[Ubuntu – File list of package graphicsmagick-imagemagick-compat/vivid/all](http://packages.ubuntu.com/en/vivid/all/graphicsmagick-imagemagick-compat/filelist)
[Ubuntu – File list of package imagemagick-6.q16/vivid/amd64](http://packages.ubuntu.com/en/vivid/amd64/imagemagick-6.q16/filelist)
1. …

Fix build problems

---

README.textile

Created after finding out about my own fault in https://github.com/rmagick/rmagick/issues/225
Since I checked the README prerequisites as first troubleshooting step, I believe that this hint could be helpful for others too.
Your contribution guidelines state
> NOTE: GitHub suggests `rmagick-temp/rmagick` repo by default.
This is not true for me. I got `rmagick/rmagick` suggested, which is the repo I forked from.

Add README hint for bitness under windows

---

lib/rmagick_internal.rb

This patch fixes a ruby warning "assigned but unused variable".

⚠️ assigned but unused variable - current

---

ext/RMagick/extconf.rb
lib/rmagick/version.rb

With ImageMagick 6.9 binaries have been splitted into two and MagickWand package must be used in order to compile this gem.

Support for ImageMagick 6.9+

---

rmagick.gemspec

Rake removed this method from Rake 12.0.
See:
https://github.com/ruby/rake/blob/master/History.rdoc#compatibility-changes-1
Seems rspec older than 3.4.0 require incompatible version of rake.
Rake test should be run fine by now
I found no reason why rspec should be locked by minor version, so i think latest 3 version of rspec should be working fine

Fix rake `undefined method `last_comment'` error

---

ext/RMagick/rmdraw.c

I was unable to render `%x` in a text because RMagick doesn't want the text to include image attributes. But these image attributes do not seem to be used by the underlying process. And using a double percent as mentioned in the doc doesn't work either: it prevents the error but both percent signs are actually rendered.
So I just removed this check and it works. I can render `%x` just fine.
Maybe this behavior depends on the imagemagick library version?

Stop preventing image attributes in texts

---

README.textile

I just solve problem with installing rmagick on OS X. I was faced with incompatible rmagick with imagemagick 7.x.x ver.
I had to downgrade the imagemagick version to 6.9.6-5.
> brew switch imagemagick 6.9.6-5

Fix prerequisites

---

ext/RMagick/rmmain.c
test/Image2.rb

Image_morphology_channel requires 4 arguments.
https://github.com/rmagick/rmagick/blob/6759bf186355af107205c5ab98f3433856d25935/ext/RMagick/rmimage.c#L4211
If you pass 3 arguments, it causes a SEGV in RMagick.
```ruby
image = Magick::ImageList.new('./Flower_Hat.jpg').first
kernel_info = Magick::KernelInfo.new("Octagon")
new_img = image.morphology_channel(Magick::RedChannel, Magick::EdgeOutMorphology, 2)
new_img.write('./morphology_channel.png')
```
```
$ ruby morphology_channel.rb
morphology_channel.rb:7: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-darwin18]
* ~/Library/Logs/CrashReporter …
```

fix argument count in Image#morphology_channel

---

ext/RMagick/extconf.rb
ext/RMagick/rmimage.c

GetImageChannelEntropy() was implemented at ImageMagick 6.9.0-0.
If RMagick was compiled with older ImageMagick 6,
it will cause a following error when it looks up GetImageChannelEntropy symbol.
```
dyld: lazy symbol binding failed: Symbol not found: _GetImageChannelEntropy
Referenced from: /Users/watson/prj/rmagick/lib/RMagick2.bundle
Expected in: flat namespace
dyld: Symbol not found: _GetImageChannelEntropy
Referenced from: /Users/watson/prj/rmagick/lib/RMagick2.bundle
Expected in: flat namespace
```
Travis CI shows same error in https://travis-ci.org/rmagick/rmagick/jobs/436792873

check that GetImageChannelEntropy() is implemented in ImageMagick

---

.travis.yml

The older Ruby versions were dropped at https://github.com/rmagick/rmagick/commit/a828a434e3ccb776eb50637a5e52aeaeb1509a38
So, now it always fails at Ruby 2.0, 2.1 lanes on Travis CI, like
```
Bundler could not find compatible versions for gem "ruby":
In Gemfile:
ruby
rmagick was resolved to 2.16.0, which depends on
ruby (>= 2.2.0)
Could not find gem 'ruby (>= 2.2.0)', which is required by gem 'rmagick', in
any of the relevant sources:
the local ruby installation
The command "bundle install --verbose" failed and exited with 6 during .
Your build has been stopped.
```
(https://travis-ci.org/rmagick/rmagick/jobs/471690003#L2014)

Drop older Ruby versions for Travis

---

before_install_linux.sh

Recently, Bundler v2 was released (https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html).
It supports Ruby 2.3+, but RMagick still supports Ruby 2.2 environment.
If it install bundler v2 on Ruby 2.2, it will cause the following error.
```
Fetching: bundler-2.0.1.gem (100%)
ERROR:  Error installing bundler:
The last version of bundler (>= 0) to support your Ruby & RubyGems was 1.17.3. Try installing it with `gem install bundler -v 1.17.3`
bundler requires Ruby version >= 2.3.0. The current ruby version is 2.2.0.
The command "source before_install_$TRAVIS_OS_NAME.sh" failed and exited with 1 during .
```
(https://travis-ci.org/rmagick/rmagick/jobs/481684602#L3123)
So, this will change the version of bundler to 1.17.3 for Travis.

install bundler v1.17.3 for Ruby 2.2 on Travis

---

spec/rmagick/image/channel_entropy_spec.rb
spec/spec_helper.rb

channel_entropy spec always fails with older ImageMagick.
If you would run channel_entropy spec with unsupported ImageMagick version, this patch will skip it.

skip channel_entropy spec with unsupported ImageMagick

---

ext/RMagick/rmimage.c

`AcquireExceptionInfo()` allocates the memory area for handling exception in ImageMagick.
However, Ruby's GC does not manage its memory area.
So, `rmagick` must release them after handling exception by using `DestroyExceptionInfo()`.
```
$ ruby rmagick.rb
Process: 76636: RSS = 133 MB
```
```
$ ruby rmagick.rb
Process: 77939: RSS = 10 MB
```
```ruby
source = Magick::Image.new(20, 20)
100000.times do |i|
image.gray?
image.sparse_color(Magick::VoronoiColorInterpolate, 0, 0, 'red')
Magick::Image.combine(image, source)
GC.start
end
```

Fix memory leak

---

lib/rmagick_internal.rb

It causes the error if it requires RMagick on Windows with recent [RubyInstaller](https://rubyinstaller.org) as following.
To solve this error, you need to copy the DLL accoding to article in https://medium.com/ruby-on-rails-web-application-development/install-rmagick-gem-on-windows-7-8-10-imagemagick-6-9-4-q16-hdri-5492c3fef202#f956
This Pull Request fix this error accoding to https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers
With this patch, RMagick works well on Windows, like

Fix loading error on Windows

---

spec/rmagick/image/read_spec.rb

This test was failing when [it was first introduced][1]. In order to get
us to a passing build, this skips the test for now.
[1]: https://github.com/rmagick/rmagick/pull/230

Tests: disable failing test

---

test/Image2.rb

There were a handful of different methods that were failing in the tests
for various reasons. For now, I simply filtered out the methods that are
not handled properly, but we can revisit as we update the tests.

Tests: handle broken Image tests

---

ext/RMagick/rmdraw.c

that may not be enough later with imagemagick changing struct's size.

AcquireDrawInfo() instead of magick_alloc()-ing some memory

---

before_install_linux.sh

We no longer support Ruby 1.8, so this can be removed. This was
motivated by wanting to add `set -u` to the top of the script, which was
complaining about the variable being unset.

Tests: remove block to handle Ruby 1.8

---

ext/RMagick/rmdraw.c

`draw->info` was initialized at `DrawOptions_initialize()` via `Draw_initialize()`.
If allocate the memory area with `AcquireDrawInfo()` in here, the area cannot be released in `destroy_Draw()`.
* Before
```
$ ruby draw_marshal_load.rb
Process: 62978: RSS = 812 MB
```
* After
```
$ ruby draw_marshal_load.rb
Process: 7588: RSS = 24 MB
```
* Test code
```ruby
wm = Magick::Image.read("xc:none") { self.size = "100x50" }.first
gc = Magick::Draw.new
gc.fill '#ff0000'
gc.font_weight Magick::BoldWeight
gc.font_size 18
gc.rotate 15
gc.gravity Magick::CenterGravity
gc.text 0, 0, "RMagick"
gc.draw wm
dump = gc.marshal_dump
g = Magick::Draw.new
g.marshal_load(dump)
end …
```

Fix memory leak in Draw#marshal_load

---

.travis.yml
before_install_linux.sh

We build ImageMagick from source code for test at each time.
And it take a time slightly.
This patch introduce `ccache` to cache built objects in order to reduce compiling time.

Introduce ccache to build ImageMagick on Travis

---

.travis.yml
CHANGELOG.md
README.textile
test/Image2.rb
test/Image_attributes.rb

The default Heroku and Ubuntu version for ImageMagick is 6.8, so we
should be good to march forward from there.

deprecate support for ImageMagick < 6.8

---

CHANGELOG.md
README.textile
lib/rmagick/version.rb

TravisCI uses 2.3.7 by default, and it doesn't seem necessary to enforce
a point release.

3.0: loosen ruby version to 2.3.0

---

.travis.yml

- Remove Ruby 2.5 for now. It's failing, so in the interest of getting a
passing build and a 3.0 release, let's disable it. I'll re-add it as a
tracking PR.
- Remove build against latest ImageMagick. This is likely to cause
inconsistent failures, so in the interest of a reliable build, we
can remove it and add tracking PRs for versions we want to support.
- Remove `allowed_failures`. These slow down builds and add some noise,
so better to explicitly add support for new versions as they come up.

CI: clean up .travis.yml

---

spec/rmagick/image/read_spec.rb

This test is causing the appveyor build to fail due to the way it
spawns a new process. Both tests affected are already skipped, as they
have never passed, so we can just block out the offending code for the
moment.
https://ci.appveyor.com/project/mockdeep/rmagick/builds/22143507

CI: comment out `before` block in skipped specs

---

.circleci/config.yml
rmagick.gemspec

TravisCI performance isn't great, and I need to be able to SSH into the
build in order to debug. I tried the `curl` command [recommended in the
Travis docs][1], but that didn't do the trick. Circle doesn't support
matrix the way that Travis does, but I figure we can manage with a
slightly more verbose config file.
[1]: https://docs.travis-ci.com/user/running-build-in-debug-mode/#restarting-a-job-in-debug-mode-via-api

CI: add CircleCI config

---

ext/RMagick/rmagick.c

`GetMagickInfoList()` API returns allocated memory area which need to release in RMagick.
* Before
```
$ ruby init_formats.rb
Process: 69864: RSS = 226 MB
```
* After
```
$ ruby init_formats.rb
Process: 71149: RSS = 20 MB
```
* Test code
```ruby
100000.times do
Magick.init_formats
end
```

Fix memory leak in Magick.init_formats

---

ext/RMagick/rmimage.c

The deprecated GetExceptionInfo() API cannot be used in old ImageMagick of Windows and it causes link error.

Use AcquireExceptionInfo() instead of GetExceptionInfo()

---

ext/RMagick/rmdraw.c

`AcquireExceptionInfo()` returns allocated memory area which need to release in RMagick using `DestroyExceptionInfo()`.
* Before
```
$ ruby polaroid_options.rb
Process: 81296: RSS = 66 MB
```
* After
```
$ ruby polaroid_options.rb
Process: 83152: RSS = 29 MB
```
* Test code
```ruby
100000.times do
Magick::Image::PolaroidOptions.new
end
```

Fix memory leak in PolaroidOptions.new

---

ext/RMagick/rminfo.c

`GetPageGeometry()` API returns allocated memory area.
We have to release it after used or before raising exception.
* Before
```
$ ruby test.rb
Process: 42227: RSS = 1052 MB
```
* After
```
$ ruby test.rb
Process: 42536: RSS = 65 MB
```
* Test code
```ruby
100000.times do
begin
info.origin = 'foobarbaz' * 100
rescue
end
info.origin = '+50+20'
end
GC.start
```

Fix memory leak in Info#origin=

---

ext/RMagick/rminfo.c

`GetPageGeometry()` API returns allocated memory area which need to release in RMagick.
In here, we can remove to duplicate of the string (`magick_clone_string()`) instead of release the string in `geometry`.
* Before
```
$ ruby test.rb
Process: 35116: RSS = 628 MB
```
* After
```
$ ruby test.rb
Process: 35827: RSS = 121 MB
```
* Test code
```ruby
100000.times do
info.page = 'foobarbaz' * 100
end
GC.start
```

Fix memory leak in Info#page=

---

ext/RMagick/rmimage.c
ext/RMagick/rminfo.c
ext/RMagick/rmutil.c

The SEGV has been occurred with old ImageMagick (v6.8.9) on only Windows.
If you set the `Proc` object through the `#monitor=` method, the object will be called each time ImageMagick processing progresses at https://github.com/rmagick/rmagick/blob/b1828e24af5eeb1e2b3c2f3e592552950a27bb6b/ext/RMagick/rmutil.c#L1464.
The Proc object is called correctly only once and SEGV always occurs in the second call.
I guess that there is a problem in callback processing with old ImageMagick and it breaks Proc object or something...
So I will disable this method on Windows because it is hard to fix this problem.
* Test code
```
monitor = proc do |mth, q, s|
true
end
img = Magick::Image.new(2000, 2000) { self.monitor = monitor }
img.resize!(20, 20)
```
* Result
```
> ruby test.rb …
```

Disable monitor feature on Windows

---

.appveyor.yml

To support Windows environment, we can use AppVeyor CI for testing.
As the first step, It works with the following combinations.
- Ruby+Devkit 2.5.3-1 (https://rubyinstaller.org/downloads/)
- ImageMagick 6.9.10.24
Example)
https://ci.appveyor.com/project/Watson1978/rmagick/builds/21991269
@mockdeep Can you add AppVeyor integration in this repository if you interest ?

Add AppVeyor configuration

---

ext/RMagick/rmimage.c
test/Image1.rb

Fix #200
If nil or empty string argument was given in Image.read method, ImageMagick `ReadImage()` API does not return a response.

Should raise exception in Image.read if nil or empty string argument was given

---

lib/rmagick/version.rb

- bump RMagick version to 3.0.0
- bump `MIN_IM_VERSION` to 6.8.9
Side note, `MIN_WAND_VERSION` was introduced in 55a2b2e (PR #255). It
looks like the `MagickWand` package was extracted in IM version 6.9.
Once we've moved our min ImageMagick version up past 6.9, we should be
able to unify the 2 constants.

Bump versions

---

ext/RMagick/rmimage.c

We can trace creating/destroying Image by setting `Proc` object via `Magick.trace_proc=` method.
If the `Proc` object raises an exception, it causes memory leak when new Image will be created.
The `Proc` object will be called by `rm_trace_creation()` and `rm_trace_creation()` works before converting ImageMagick Image object to Ruby object.
We have to release the ImageMagick object which is unmanaged by Ruby's GC.
* Before
```
$ ruby test.rb
Process: 22010: RSS = 249 MB
```
* After
```
$ ruby test.rb
Process: 23262: RSS = 16 MB
```
* Test code
```ruby
Magick.trace_proc = Proc.new { raise }
10000.times do
begin
image.resize(10, 10)
rescue
end
end
GC.start
puts "Process: #{Process.pid}: RSS = …
```

Fix memory leak when raise an exception in trace_proc at creating new Image

---

Gemfile
rmagick.gemspec

Because we don't check in `Gemfile.lock`, it's good to lock these down
in our `gemspec` file. This makes sure the build stays consistent if,
say, there's a major breaking release of RSpec, or once we've added
Rubocop to the build we don't want it to randomly fail every time they
add new rules.

Lock down development dependency versions

---

ext/RMagick/rminfo.c

If the object which can't be converted to `String`, Ruby C API `StringValuePtr()` will raise the exception.
* Before
```
$ ruby fill.rb
Process: 35832: RSS = 240 MB
```
* After
```
$ ruby fill.rb
Process: 36981: RSS = 16 MB
```
* Test code
```ruby
200000.times do
begin
info.fill = Object.new
rescue
end
begin
info.stroke = Object.new
rescue
end
begin
info.undercolor = Object.new
rescue
end
end
GC.start
```

Fix memory leak in Info#{fill=, stroke=, undercolor=}

---

ext/RMagick/rminfo.c

If the object which can't be converted to `String`, Ruby C API `StringValuePtr()` will raise the exception.
* Before
```
$ ruby format.rb
Process: 32550: RSS = 398 MB
```
* After
```
$ ruby format.rb
Process: 34253: RSS = 16 MB
```
* Test code
```ruby
begin
info.format = Object.new
rescue
end
end
GC.start
```

Fix memory leak in Info#format=

---

ext/RMagick/rmilist.c

If empty image list was given, `images_from_imagelist()` will raise exception.
* Before
```
$ ruby quantize.rb
Process: 18666: RSS = 388 MB
```
* After
```
$ ruby quantize.rb
Process: 19794: RSS = 17 MB
```
* Test code
```ruby
begin
list.quantize()
rescue
end
end
GC.start
```

Fix memory leak in ImageList#quantize

---

ext/RMagick/rmilist.c

If empty image list was given, `images_from_imagelist()` will raise exception.
* Before
```
$ ruby optimize_layers.rb
Process: 16589: RSS = 388 MB
```
* After
```
$ ruby optimize_layers.rb
Process: 17735: RSS = 16 MB
```
* Test code
```ruby
begin
list.optimize_layers(Magick::CompareAnyLayer)
rescue
end
end
GC.start
```

Fix memory leak in ImageList#optimize_layers

---

ext/RMagick/rmilist.c

If empty image list was given, `images_from_imagelist()` will raise exception.
* Before
```
$ ruby morph.rb
Process: 14433: RSS = 388 MB
```
* After
```
$ ruby morph.rb
Process: 15567: RSS = 16 MB
```
* Test code
```ruby
begin
list.morph(1)
rescue
end
end
GC.start
```

Fix memory leak in ImageList#morph

---

ext/RMagick/rmilist.c

If empty image list was given in ImageList object, `images_from_imagelist()` will raise exception.
* Before
```
$ ruby map.rb
Process: 11276: RSS = 389 MB
```
* After
```
$ ruby map.rb
Process: 12419: RSS = 17 MB
```
* Test code
```ruby
begin
list.map(image)
rescue
end
end
GC.start
```

Fix memory leak in ImageList#map

---

ext/RMagick/rmilist.c
test/ImageList2.rb

`ImageList` object has actual image list in instance variable `@images` and we can easily override the value to `@images` using `Object#instance_variable_set` method.
If you set invalid value to `@images`, RMagick causes SEGV at https://github.com/rmagick/rmagick/blob/e2c9919470555cc712a0d7d9a5d1b91079f6425b/ext/RMagick/rmilist.c#L867
This patch will check `@images` whether it has `Array` object.
* Result
```
$ ruby test.rb
test.rb:8: [BUG] Segmentation fault at 0x0000000000000003
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
* ~/Library/Logs/DiagnosticReports
* /Library/Logs/DiagnosticReports
for more details.
Don't forget to include the above …
```

Fix SEGV in ImageList methods with invalid image list

---

before_install_linux.sh

- `-e` stops the script on an error
- `-u` does not allow unassigned variables, except for conditional
checks like `case` and `-v`. Because `CONFIGURE_OPTIONS` might not be
set, I needed to add a check for this.
- `-o pipefail` causes pipe (`|`) expressions to return a failing status
if any of the commands in the pipeline returns a failing status. We
currently don't have any pipes to worry about, but we might someday.
We need to add `set +u` at the end of the file to allow unbound
variables in scripts wrapping this on CircleCI and Travis.

CI: set strict options for setup script

---

README.textile

- Remove VersionEye as it's [no longer active][1].
- Remove Gitter, as I don't think any of the core maintainers want to be
active on there. Users are probably better off asking Stack Overflow
questions or opening issues on the repo.
- Remove downloads badge. Doesn't seem that useful.
- Remove coverage badge. We're not monitoring coverage at the moment,
but we can re-add it once we are.
- Add CI badges for AppVeyor and CircleCI.
Unfortunately, it looks like in `textile` format if we put them
on separate lines in the raw text each badge shows up on a separate line
on Github. When we switch it over to markdown we can put these on
different lines for easier maintenance.
[1]: https://blog.versioneye.com/2017/10/19/versioneye-sunset-process/

Docs: update badges in README

---

ext/RMagick/rmimage.c

If the object which can't be converted to `String`, Ruby C API `StringValuePtr()` will raise the exception.
* Before
```
$ ruby test.rb
Process: 61030: RSS = 390 MB
```
* After
```
$ ruby test.rb
Process: 62316: RSS = 15 MB
```
* Test code
```ruby
image = Magick::Image.new(10, 10)
begin
image.format = Object.new
rescue
end
end
GC.start
```

Fix memory leak in Image#format=

---

ext/RMagick/rmilist.c

We have to release memory area allocated by `AcquireExceptionInfo()` before raising exception.
* Before
```
$ ruby test.rb
Process: 67533: RSS = 389 MB
```
* After
```
$ ruby test.rb
Process: 66292: RSS = 17 MB
```
* Test code
```ruby
list.read('./doc/ex/images/Button_0.gif', './doc/ex/images/Button_1.gif')
begin
list.optimize_layers(Magick::UndefinedLayer)
rescue
end
end
GC.start
```

Fix memory leak in ImageList#optimize_layers with not supported layer method

---

ext/RMagick/rmilist.c

If empty image list was given, `images_from_imagelist()` will raise exception.
* Before
```
$ ruby mosaic.rb
Process: 75028: RSS = 388 MB
```
* After
```
$ ruby mosaic.rb
Process: 76093: RSS = 16 MB
```
* Test code
```ruby
begin
list.mosaic()
rescue
end
end
GC.start
```

Fix memory leak in ImageList#mosaic

---

before_install_linux.sh

We should be able to use the latest version now that we've dropped
support for Ruby 2.2.

Remove bundler version from setup script

---

ext/RMagick/rmimage.c

If invalid argument was given, `rm_check_destroyed()` will raise an exception.
This is detected by profiling tool when run test at https://github.com/rmagick/rmagick/blob/e758a48bfa6fb5075b3f82cdca61cca656cdc3a3/test/Preview.rb#L51.
* Before
```
$ ruby preview.rb
Process: 78085: RSS = 390 MB
```
* After
```
$ ruby preview.rb
Process: 79161: RSS = 18 MB
```
* Test code
```ruby
begin
image.preview(2)
rescue
end
end
GC.start
```

Fix memory leak in Image#preview

---

ext/RMagick/rmimage.c

`rm_clone_image()` returns memory area allocated by ImageMagick API.
The area should be convert to Ruby object using `rm_image_new()`.
However, if invalid argument was given, `Color_to_MagickPixelPacket()` will raise an exception before converting then it causes memory leak.
This is detected by profiling tool when run test at https://github.com/rmagick/rmagick/blob/e758a48bfa6fb5075b3f82cdca61cca656cdc3a3/test/Image2.rb#L1197.
* Before
```
$ ruby test.rb
Process: 85928: RSS = 152 MB
```
* After
```
$ ruby test.rb
Process: 86997: RSS = 16 MB
```
* Test code
```ruby
red = Magick::Pixel.new(Magick::QuantumRange)
10000.times do
begin
image.opaque(red, 2)
rescue
end
end
GC.start
puts "Process: …
```

Fix memory leak in Image#opaque

---

ext/RMagick/rmimage.c

`rm_clone_image()` returns memory area allocated by ImageMagick API.
The area should be convert to Ruby object using `rm_image_new()`.
However, if invalid argument was given, `NUM2INT()` will raise an exception before converting then it causes memory leak.
* Before
```
$ ruby test.rb
Process: 89039: RSS = 153 MB
```
* After
```
$ ruby test.rb
Process: 90212: RSS = 14 MB
```
* Test code
```ruby
begin
image.cycle_colormap('x')
rescue
end
end
GC.start
```

Fix memory leak in Image#cycle_colormap

---

ext/RMagick/rmimage.c

The memory area allocated by `CloneDrawInfo()` is required to release after used in this method.
* Before
```
$ ruby test.rb
Process: 93466: RSS = 92 MB
```
* After
```
$ ruby test.rb
Process: 94540: RSS = 23 MB
```
* Test code
```ruby
x = 5
y = 5
100000.times do |i|
target = image.pixel_color(x, y)
image.matte_flood_fill(target, Magick::TransparentOpacity, x, y, Magick::FloodfillMethod)
end
GC.start
```

Fix memory leak in Image#matte_flood_fill

---

ext/RMagick/rmimage.c

* Before
```
$ ruby test.rb
Process: 23764: RSS = 2802 MB
```
* After
```
$ ruby test.rb
Process: 24929: RSS = 14 MB
```
* Test code
```ruby
begin
image.bilevel_channel('x')
rescue
end
end
GC.start
```

Fix memory leak in Image#bilevel_channel

---

ext/RMagick/rmimage.c

* Before
```
$ ruby test.rb
Process: 20884: RSS = 2801 MB
```
* After
```
$ ruby test.rb
Process: 22217: RSS = 14 MB
```
* Test code
```ruby
begin
image.threshold('x')
rescue
end
end
GC.start
```

Fix memory leak in Image#threshold

---

ext/RMagick/rmimage.c

* Before
```
$ ruby test.rb
Process: 17408: RSS = 88 MB
```
* After
```
$ ruby test.rb
Process: 20019: RSS = 14 MB
```
* Test code
```ruby
begin
image.swirl('x')
rescue
end
end
GC.start
```

Fix memory leak in Image#swirl

---

ext/RMagick/rmimage.c

* Before
```
$ ruby test.rb
Process: 15476: RSS = 88 MB
```
* After
```
$ ruby test.rb
Process: 16770: RSS = 14 MB
```
* Test code
```ruby
begin
image.shear('x', 'y')
rescue
end
end
GC.start
```

Fix memory leak in Image#shear

---

ext/RMagick/rmimage.c

If invalid argument was given, `NUM2LONG()` will raise an exception.
* Before
```
$ ruby test.rb
Process: 13379: RSS = 88 MB
```
* After
```
$ ruby test.rb
Process: 14490: RSS = 14 MB
```
* Test code
```ruby
begin
image.roll('x', 'y')
rescue
end
end
GC.start
```

Fix memory leak in Image#roll

---

ext/RMagick/rmimage.c

* Before
```
$ ruby test.rb
Process: 10103: RSS = 88 MB
```
* After
```
$ ruby test.rb
Process: 11834: RSS = 14 MB
```
* Test code
```ruby
begin
image.radial_blur_channel('x')
rescue
end
end
GC.start
```

Fix memory leak in Image#radial_blur_channel

---

ext/RMagick/rmimage.c

* Before
```
$ ruby test.rb
Process: 7256: RSS = 89 MB
```
* After
```
$ ruby test.rb
Process: 9312: RSS = 14 MB
```
* Test code
```ruby
begin
image.radial_blur('x')
rescue
end
end
GC.start
```

Fix memory leak in Image#radial_blur

---

ext/RMagick/rmimage.c

If invalid argument was given in first argument of `Image#gamma_channel`, `NUM2DBL()` will raise an exception.
* Before
```
$ ruby test.rb
Process: 3255: RSS = 1407 MB
```
* After
```
$ ruby test.rb
Process: 5404: RSS = 14 MB
```
* Test code
```ruby
100000.times do |i|
begin
image.gamma_channel('x')
rescue
end
end
GC.start
```

Fix memory leak in Image#gamma_channel

---

ext/RMagick/rmimage.c

If destroyed `Image` object was given, `rm_check_destroyed()` will raise an exception.
Then, memory area allocated by `rm_clone_image()` causes memory leak.
This is detected by profiling tool when run test at https://github.com/rmagick/rmagick/blob/b72b52fc9f676be1b594f28232a6a79d90c88250/test/Image2.rb#L1015.
* Before
```
$ ruby test.rb
Process: 99463: RSS = 1407 MB
```
* After
```
$ ruby test.rb
Process: 885: RSS = 14 MB
```
* Test code
```ruby
map_obj = Magick::Image.new(5, 5)
map_obj.destroy!
100000.times do |i|
begin
image.map(map_obj, true)
rescue
end
end
GC.start
```

Fix memory leak in Image#map

---

ext/RMagick/rmimage.c

If If invalid argument was given, `rm_str2cstr()` will raise exception.
* Before
```
$ ruby test.rb
Process: 39019: RSS = 176 MB
```
* After
```
$ ruby test.rb
Process: 40111: RSS = 14 MB
```
* Test code
```ruby
begin
Magick::Image._load(Object.new)
rescue
end
end
GC.start
```

Fix memory leak in Image._load

---

ext/RMagick/rmimage.c

If If invalid argument was given, `Export_AffineMatrix()` will raise exception.
* Before
```
$ ruby test.rb
Process: 32919: RSS = 153 MB
```
* After
```
$ ruby test.rb
Process: 34697: RSS = 15 MB
```
* Test code
```ruby
image1 = Magick::Image.new(20, 20)
image2 = Magick::Image.new(20, 20)
begin
image1.composite_affine(image2, 'x')
rescue
end
end
GC.start
```

Fix memory leak in Image#composite_affine

---

README.textile

This is for #392 
When I try to install rmagick, A build error occurred.
The mkmf.log shows different requirements from README.
```mkmf.log
Can't install RMagick 3.0.0. You must have ImageMagick 6.8.9 or later.
```

Docs: Fix ImageMagick version

---

ext/RMagick/rmimage.c

ImageMagick `SharpenImageChannel()` API returns new Image object.
So, the memory area allocated by `rm_clone_image(image);` causes memory leak.
* Before
```
$ ruby sharpen_channel.rb
Process: 9502: RSS = 281 MB
```
* After
```
$ ruby sharpen_channel.rb
Process: 10950: RSS = 22 MB
```
* Test code
```ruby
image.sharpen_channel
end
GC.start
```
This pull request has breaking change.
Before this change, `Image#sharpen_channel` just returns cloned image.
After this, `Image#sharpen_channel` returns expected image effected by `SharpenImageChannel()` API.

Fix memory leak in Image#sharpen_channel

---

ext/RMagick/rmpixel.c

This block checks for ImageMagick <= 6.5, which we no longer support.

remove code for older ImageMagick

---

ext/RMagick/rmagick.h
ext/RMagick/rmimage.c
ext/RMagick/rmutil.c
test/Image3.rb

If invalid argument which is not `Array` object was given in `Image#recolor`,
`RARRAY_LEN()` in https://github.com/rmagick/rmagick/blob/b72b52fc9f676be1b594f28232a6a79d90c88250/ext/RMagick/rmimage.c#L10955 causes SEGV.
* Result
```
$ ruby test.rb
test.rb:4: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
* ~/Library/Logs/DiagnosticReports
* /Library/Logs/DiagnosticReports
for more details.
Don't forget to include the above Crash Report log file in bug reports.
-- Control frame information -----------------------------------------------
c:0003 p:---- s:0012 e:000011 CFUNC  :recolor
c:0002 p:0032 s:0007 …
```

Fix SEGV in Image#recolor

---

ext/RMagick/extconf.rb
ext/RMagick/rmagick.h
ext/RMagick/rmfill.c
ext/RMagick/rmilist.c
ext/RMagick/rmimage.c
ext/RMagick/rmmain.c
ext/RMagick/rmpixel.c
ext/RMagick/rmutil.c

So, we can use API added in older version without check.

Remove some have_func checking for older ImageMagick API

---

ext/RMagick/rmilist.c

If invalid argument was given, `NUM2UINT()` will raise exception.
Then, the memory area allocated by `images_from_imagelist()` causes memory leak.
* Before
```
$ ruby test.rb
Process: 31231: RSS = 177 MB
```
* After
```
$ ruby test.rb
Process: 32804: RSS = 18 MB
```
* Test code
```ruby
list = Magick::ImageList.new('sample1.gif', 'sample2.gif')
begin
list.animate('x')
rescue
end
end
GC.start
```

Fix memory leak in ImageList#animate

---

ext/RMagick/rmimage.c

If it used `ProfileImage()` API to remove image profile, the API causes memory leak.
Seems that we should not use `ProfileImage()` for that.
If we use `DeleteImageProfile()` instead, we can avoid the memory leak.
* Before
```
$ ruby test.rb
Process: 90640: RSS = 104 MB
```
* After
```
$ ruby test.rb
Process: 34697: RSS = 15 MB
```
* Test code
```ruby
image = Magick::Image.new(10, 10)
20000.times do |i|
image.profile!('iptc', 'foobarbaz')
image.delete_profile('iptc')
end
GC.start
```

Fix memory leak in Image#delete_profile

---

ext/RMagick/rmimage.c
test/Image3.rb

If unknow name was given in `Image#profile!`, it causes SEGV.
Seems `GetMagickInfo()` API returns NULL with unknow name without exception.
Then SEGV will be caused when it use returned value of `GetMagickInfo()`.
* Result
```
$ ruby test.rb
test.rb:4: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
* ~/Library/Logs/DiagnosticReports
* /Library/Logs/DiagnosticReports
for more details.
Don't forget to include the above Crash Report log file in bug reports.
-- Control frame information -----------------------------------------------
c:0003 p:---- s:0013 e:000012 CFUNC  :profile!
c:0002 p:0034 s:0007 …
```

Fix SEGV in Image#profile!

---

ext/RMagick/extconf.rb
ext/RMagick/rmdraw.c
ext/RMagick/rmutil.c

So, we can use structure members which were added in older version without any check.

Remove some have_struct_member checking for older ImageMagick structure members

---

ext/RMagick/rmagick.c
ext/RMagick/rmagick.h
ext/RMagick/rmmain.c
test/Magick.rb

Add the method to get the ImageMagick delegate information.
That information includes encoder and decoder supported by ImageMagick.
For example, when write a test code to save `webp` images, it is easy to know whether ImageMagick has been supported. Related to https://github.com/rmagick/rmagick/issues/60

Add Magick.delegates method

---

ext/RMagick/rminfo.c

* Before
```
$ ruby test.rb
Process: 75876: RSS = 61 MB
```
* After
```
$ ruby test.rb
Process: 76977: RSS = 14 MB
```
* Test code
```ruby
info.caption = "foobarbaz"
info.caption = nil
info.comment = "foobarbaz"
info.comment = nil
info.label = "foobarbaz"
info.label = nil
end
GC.start
```

Fix memory leak in Info#{caption=, comment=, label=}

---

ext/RMagick/extconf.rb
ext/RMagick/rmagick.h
ext/RMagick/rmilist.c
ext/RMagick/rmimage.c
ext/RMagick/rmmain.c

So, we can use API added in older version without check.

Remove some have_type checking for older ImageMagick API

---

ext/RMagick/rmimage.c
test/Image2.rb

Close #403
Maybe, the API of ancient ImageMagick might has caused SEGV if 0.0 was given as gamma value into Image#gamma_correct.
Now, seem we can call ImageMagick API without SEGV.

Remove unnecessary value check in argument of Image#gamma_correct

---

ext/RMagick/extconf.rb
ext/RMagick/rmmain.c

Remove have_enum_values checking of AlphaChannelType

---

ext/RMagick/rmimage.c

This is similar issue with https://github.com/rmagick/rmagick/pull/409
Seems `RemoveImageArtifact()` will not deallocate memory area completedly for this case.
If we use `DeleteImageArtifact()` instead, we can avoid the memory leak.
* Before
```
$ ruby test.rb
Process: 99131: RSS = 30 MB
```
* After
```
$ ruby test.rb
Process: 2934: RSS = 15 MB
```
* Test code
```ruby
image = Magick::Image.new(10, 10)
image.define('deskew:auto-crop', 40)
image.undefine('deskew:auto-crop')
end
GC.start
```

Fix memory leak in Image#undefine

---

ext/RMagick/rminfo.c

* Before
```
$ ruby test.rb
Process: 93913: RSS = 30 MB
```
* After
```
$ ruby test.rb
Process: 94901: RSS = 15 MB
```
* Test code
```ruby
info.gravity = Magick::CenterGravity
info.gravity = nil
end
GC.start
```

Fix memory leak in Info#gravity=

---

ext/RMagick/rminfo.c

* Before
```
$ ruby test.rb
Process: 91727: RSS = 30 MB
```
* After
```
$ ruby test.rb
Process: 92615: RSS = 14 MB
```
* Test code
```ruby
info.dispose = Magick::BackgroundDispose
info.dispose = nil
end
GC.start
```

Fix memory leak in Info#dispose=

---

ext/RMagick/rminfo.c

* Before
```
$ ruby test.rb
Process: 89367: RSS = 45 MB
```
* After
```
$ ruby test.rb
Process: 90734: RSS = 15 MB
```
* Test code
```ruby
info.delay = 42
info.delay = 42
info.delay = nil
end
GC.start
```

Fix memory leak in Info#delay=

---

ext/RMagick/rminfo.c

* Before
```
$ ruby test.rb
Process: 86727: RSS = 30 MB
```
* After
```
$ ruby test.rb
Process: 87881: RSS = 14 MB
```
* Test code
```ruby
info.define('iptc', 'test', 'foobarbaz')
end
GC.start
```

Fix memory leak in Info#define

---

ext/RMagick/rminfo.c

* Before
```
$ ruby test.rb
Process: 85446: RSS = 45 MB
```
* After
```
$ ruby test.rb
Process: 86450: RSS = 14 MB
```
* Test code
```ruby
info['test'] = 'foobarbaz'
info['test'] = 'foobarbaz'
info['test'] = nil
end
GC.start
```

Fix memory leak in Info#[]=

---

ext/RMagick/rminfo.c

* Before
```
$ ruby test.rb
Process: 83360: RSS = 76 MB
```
* After
```
$ ruby test.rb
Process: 84430: RSS = 15 MB
```
* Test code
```ruby
info.attenuate = 1.0
info.attenuate = 1.0
info.attenuate = nil
info.stroke_width = 1.0
info.stroke_width = 1.0
info.stroke_width = nil
end
GC.start
```

Fix memory leak in Info#{attenuate=, stroke_width=}

---

doc/rvg.html
doc/rvgtut.html
ext/RMagick/rmkinfo.c
lib/rvg/deep_equal.rb
lib/rvg/misc.rb
lib/rvg/units.rb
test/Image1.rb
test/Info.rb
test/Magick.rb

Fixnum and Bignum were unified into Integer at Ruby 2.4.
If use Fixnum in Ruby land with newer version, it shows warning message
```
warning: constant ::Fixnum is deprecated
```
It means we are not able to use Fixnum in the future.

Replace Fixnum to Integer

---

ext/RMagick/rminfo.c

* Before
```
$ ruby test.rb
Process: 15203: RSS = 30 MB
```
* After
```
$ ruby test.rb
Process: 16508: RSS = 14 MB
```
* Test code
```ruby
info.define('tiff', 'bits-per-sample', 2)
info.undefine('tiff', 'bits-per-sample')
end
GC.start
```

Fix memory leak in Info#undefine

---

ext/RMagick/extconf.rb
ext/RMagick/rmenum.c
ext/RMagick/rmmain.c

Remove have_enum_values checking of CompressionType

---

ext/RMagick/extconf.rb
ext/RMagick/rmmain.c

Remove have_enum_values checking of DistortImageMethod

---

ext/RMagick/extconf.rb
ext/RMagick/rmilist.c
ext/RMagick/rmimage.c
ext/RMagick/rmmain.c

Remove have_enum_values checking of DitherMethod

---

ext/RMagick/extconf.rb
ext/RMagick/rmenum.c
ext/RMagick/rmmain.c

Remove have_enum_values checking of FilterTypes

---

ext/RMagick/extconf.rb
ext/RMagick/rmagick.h
ext/RMagick/rmimage.c
ext/RMagick/rmmain.c

Remove have_enum_values checking of MagickEvaluateOperator

---

ext/RMagick/extconf.rb
ext/RMagick/rmimage.c
ext/RMagick/rmmain.c

Remove have_enum_values checking of MagickFunction

---

ext/RMagick/extconf.rb
ext/RMagick/rmenum.c
ext/RMagick/rmilist.c
ext/RMagick/rmmain.c

Remove have_enum_values checking of ImageLayerMethod

---

ext/RMagick/extconf.rb
ext/RMagick/rmenum.c
ext/RMagick/rmmain.c

Remove have_enum_values checking of VirtualPixelMethod

---

ext/RMagick/extconf.rb

If installed ImageMagick 6 using Homebrew, it will install ImageMagck where `pkg-config` command can't find the path by default.
The users have to set `PKG_CONFIG_PATH` environment variables to install RMagick.
```
$ brew install imagemagick@6
$ gem install rmagick
Building native extensions. This could take a while...
ERROR:  Error installing rmagick:
ERROR: Failed to build gem native extension.
current directory: /Users/watson/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rmagick-3.0.0/ext/RMagick
/Users/watson/.rbenv/versions/2.5.3/bin/ruby -r ./siteconf20190303-76249-1h2084u.rb extconf.rb
checking for clang... yes
checking for Magick-config... no
checking for pkg-config... yes
Package MagickCore was not found in the pkg-config search path.
Perhaps you should add the directory …
```

Fix build error on Homebrew environment

---

ext/RMagick/extconf.rb

There is some Ruby environment on Windows.
1. MinGW
2. mswin
3. cygwin
The problem in MinGW was fixed in https://github.com/rmagick/rmagick/pull/315
This patch will fix the problem in mswin by adjusting compiler flag values for Visual Studio 2017.
* Before patch
```
C:\tmp>ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mswin64_140]
C:\tmp>gem install rmagick-3.0.0.gem
Building native extensions. This could take a while...
ERROR:  Error installing rmagick-3.0.0.gem:
ERROR: Failed to build gem native extension.
current directory: C:/usr/lib/ruby/gems/2.5.0/gems/rmagick-3.0.0/ext/RMagick
C:/usr/bin/ruby.exe -r ./siteconf20190303-1888-cmo6ru.rb extconf.rb
checking for X11.lib... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary …
```

Support ruby-mswin environment on Windows

---

ext/RMagick/rmmain.c

Add some enum values of AlphaChannelType declared in ImageMagick 6.8.9.

Add AlphaChannelType enum values

---

ext/RMagick/rmmain.c

Add some enum values of DistortImageMethod declared in ImageMagick 6.8.9.

Add DistortImageMethod enum values

---

ext/RMagick/extconf.rb

`MagickWand-config` and `Magick-config` depend on `pkg-config` command.
If remove `pkg-config`, `MagickWand-config` and `Magick-config` does not work.
```
$ brew uninstall --ignore-dependencies pkg-config
Uninstalling /usr/local/Cellar/pkg-config/0.29.2... (11 files, 627.2KB)
$ ./MagickWand-config --cflags
./MagickWand-config: line 41: pkg-config: command not found
$ ./Magick-config --cflags
./Magick-config: line 41: pkg-config: command not found
```
And `pkg-config` can take same value of `MagickWand-config`.
```
$ pkg-config --cflags MagickWand
-DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/Users/watson/imagemagick/include/ImageMagick-6
$ ./MagickWand-config --cflags
-DMAGICKCORE_HDRI_ENABLE=0 …
```

Remove MagickWand-config and Magick-config configuration

---

before_install_linux.sh
test/Image3.rb

Close #60
If ImageMagick was built with webp library, RMagick should handle `webp` format.

Add test for supporting webp format

---

ext/RMagick/rmimage.c

* Before
```
$ ruby test.rb
Process: 25135: RSS = 37 MB
```
* After
```
$ ruby test.rb
Process: 26362: RSS = 14 MB
```
* Test code
```ruby
pixels = image.export_pixels(0, 0, image.columns, image.rows, 'RGB')
pixels[0] = 'x'
begin
image.import_pixels(0, 0, image.columns, image.rows, 'RGB', pixels, Magick::IntegerPixel)
rescue
end
begin
image.import_pixels(0, 0, image.columns, image.rows, 'RGB', pixels, Magick::DoublePixel)
rescue
end
end
GC.start
```

Fix memory leak in Image#export_pixels

---

ext/RMagick/rmimage.c

* Before
```
$ ruby test.rb
Process: 21658: RSS = 59 MB
```
* After
```
$ ruby test.rb
Process: 22717: RSS = 14 MB
```
* Test code
```ruby
begin
image.function_channel(Magick::SinusoidFunction, 'x', 1.0, 1.0, 1.0)
rescue
end
end
GC.start
```

Fix memory leak in Image#function_channel

---

ext/RMagick/rmimage.c

* Before
```
$ ruby test.rb
Process: 18748: RSS = 35 MB
```
* After
```
$ ruby test.rb
Process: 19800: RSS = 14 MB
```
* Test code
```ruby
begin
image.distort(Magick::AffineProjectionDistortion, ['x', 0, 0, 1, 0, 0])
rescue
end
end
GC.start
```

Fix memory leak in Image#distort

---

ext/RMagick/rmimage.c

* Before
```
$ ruby test.rb
Process: 14895: RSS = 53 MB
```
* After
```
$ ruby test.rb
Process: 16886: RSS = 14 MB
```
* Test code
```ruby
begin
image.convolve(3, [1.0, 1.0, 1.0, 1.0, 'x', 1.0, 1.0, 1.0, 1.0])
rescue
end
end
GC.start
```

Fix memory leak in Image#convolve

---

ext/RMagick/extconf.rb
ext/RMagick/rmimage.c

https://github.com/rmagick/rmagick/pull/327#issuecomment-471152383
ImageMagick renamed `IsGrayImage()` to `SetImageGray()` on version 6.9.x.

Use SetImageGray() to fix Image#gray? with IM 6.9

---

ext/RMagick/rmilist.c
ext/RMagick/rmimage.c

I've found these methods does not handle Boolean value as `dither` at https://github.com/rmagick/rmagick/pull/429/files#diff-ccd418bf6a9c1db42c436f11f43012ccL980
The following code should generate the image without dither.
```
image = Magick::Image.read('./doc/ex/images/Flower_Hat.jpg').first
image.quantize(16, Magick::RGBColorspace, false).write('test.png')
```
Before | After
-- | --
Seems the test code also assumes Boolean value.
https://github.com/rmagick/rmagick/blob/e6f26e058a7762c5b08e3a8716fc7a943a7ae95b/test/Image3.rb#L105-L106

Fix Image#quantize and ImageList#quantize could not make dither false

---

ext/RMagick/rmimage.c

* Before
```
$ ruby test.rb
Process: 6843: RSS = 186 MB
```
* After
```
$ ruby test.rb
Process: 8143: RSS = 15 MB
```
* Test code
```ruby
pixels = image.dispatch(0, 0, image.columns, image.rows, 'RGBA')
pixels[10] = 'x'
50000.times do |i|
begin
Magick::Image.constitute(image.columns, image.rows, 'RGBA', pixels)
rescue
end
end
GC.start
```

Fix memory leak in Image#constitute

---

ext/RMagick/rmimage.c

* Before
```
$ ruby test.rb
Process: 2669: RSS = 76 MB
```
* After
```
$ ruby test.rb
Process: 5014: RSS = 14 MB
```
* Test code
```ruby
begin
image.sparse_color(Magick::VoronoiColorInterpolate,
'x', 10, 'red',
10, 'y', 'blue',
'x', 'y', 'lime',
80, 20, 'yellow')
rescue
end
end
GC.start
```

Fix memory leak in Image#sparse_color

---

ext/RMagick/rmimage.c

* Before
```
$ ruby test.rb
Process: 99346: RSS = 53 MB
```
* After
```
$ ruby test.rb
Process: 1444: RSS = 14 MB
```
* Test code
```ruby
begin
image.convolve_channel(3, [1.0, 1.0, 1.0, 1.0, 'x', 1.0, 1.0, 1.0, 1.0])
rescue
end
end
GC.start
```

Fix memory leak in Image#convolve_channel

---

examples/histogram.rb

$defout has existed until Ruby 1.8.x https://github.com/ruby/ruby/blob/f48ae0d10c5b586db5748b0d4b645c7e9ff5d52e/io.c#L6075
However, it was replaced to $stdout at Ruby 1.9
Close #263

Replace obsoleted $defout to $stdout

---

ext/RMagick/rmimage.c
ext/RMagick/rminfo.c
ext/RMagick/rmutil.c

Avoid SEGV in monitor feature for Ruby 2.5+
If you invoke the following code, `monitor` feature will causes SEGV or stack error.
Seems this problem depends on the platform.
(At least, the following code works fine on macOS)
```
monitor = proc do |mth, q, s|
p "#{q}, #{s}"
true
end
img = Magick::Image.new(2000, 2000) { self.monitor = monitor }
img.resize!(20, 20)
img.monitor = nil
```
When callback the Ruby code via `monitor`, it will cause Ruby stack breaking in Ruby VM.
To avoid SEGV, this patch will skip the callback if Ruby stack error detected.
Reverts https://github.com/rmagick/rmagick/pull/344
Related to https://github.com/rmagick/rmagick/pull/339

Avoid SEGV in monitor feature for Ruby 2.5+

---

ext/RMagick/rmutil.c
test/Image3.rb

Fix #36
Setting `image->colorspace` is not sufficient and the unitialized property causes a SEGV.
This patch will use ImageMagick API instead to fix SEGV inside ImageMagick.
(Refer [SetImageColorspace()](https://github.com/ImageMagick/ImageMagick6/blob/8ed8ee76dd5fcfc3d182cf00c5696508425176b4/magick/colorspace.c#L1189) API)

Fix SEGV in Image#write with CMYKColorspace

---

ext/RMagick/rmutil.c
test/Info.rb

`rb_id2name()` will create String object and return a pointer to the internal characters.
`rb_str_new2()` will create String object that refers to that pointer.
If destroyed first String object which created by `rb_id2name()`, second String object will be broken.
To fix SEGV, get rid of unnecessary String object creating.
This patch will create only one String object.
And the object should be guard from Ruby’s GC by `RB_GC_GUARD(method);`.
We have to add same workaround for old Ruby with https://github.com/rmagick/rmagick/pull/462.
It seems to crash when GC is executed when Ruby stack length is an abnormal value.  We have to check stack length manually because `ruby_stack_check()` does not work  Ruby 2.4
Related to https://github.com/rmagick/rmagick/pull/467

Avoid problems related to GC in monitor feature

---

spec/rmagick/image/properties_spec.rb

Seems it will always raises exception since ImageMagick 7 if random string was given as property name with `Image#[]=`.
Want to use the same test code as possible with ImageMagick 6 and 7 both.
Refer to https://github.com/rmagick/rmagick/pull/469/commits/caa7ecfc8deefd1d5e566cdc05b55dd487661083

Use appropriate image property names

---

test/ImageList2.rb

ImageList#optimize_layers(CompareClearLayer) fails with ImageMagick 6.9.
```
/Users/watson/prj/rmagick/test/ImageList2.rb:278:in `test_optimize_layers'
275:       Magick::RemoveZeroLayer
276:     ]
277:     @ilist.read(IMAGES_DIR + '/Button_0.gif', IMAGES_DIR + '/Button_1.gif')
=> 278:     layer_methods.each do |method|
279:       assert_nothing_raised do
280:         res = @ilist.optimize_layers(method)
281:         assert_instance_of(Magick::ImageList, res)
/Users/watson/prj/rmagick/test/ImageList2.rb:278:in `each'
/Users/watson/prj/rmagick/test/ImageList2.rb:279:in `block in test_optimize_layers'
/Users/watson/prj/rmagick/test/ImageList2.rb:282:in `block (2 levels) in test_optimize_layers'
<2> expected but was
<1>
Failure: test_optimize_layers(ImageList2UT)
```
With ImageMagick 6.8, …

[IM6.9] Fix test_optimize_layers()

---

test/ImageList1.rb

test_iterations fails with ImageMagick 6.9.
```
33:
34:   def test_iterations
35:     assert_nothing_raised { @list.iterations }
=> 36:     assert_equal(1, @list.iterations)
37:     assert_nothing_raised { @list.iterations = 20 }
38:     assert_equal(20, @list.iterations)
39:     assert_raise(ArgumentError) { @list.iterations = 'x' }
/Users/watson/prj/rmagick/test/ImageList1.rb:36:in `test_iterations'
<1> expected but was
<0>
Failure: test_iterations(ImageList1UT)
```
The default iterations value of GIF image was set to 1 by ImageMagick `ReadGIFImage()` API with ImageMagick 6.8 when read the image via `Image#read` method.
However, the default value was removed at ImageMagick 6.9.9.
https://github.com/ImageMagick/ImageMagick6/commit/e975a5709ddcf436d9f3cf9d4f5cf52feaac053f#diff-9ca915028732 …

[IM6.9] Fix test_iterations()

---

test/Image_attributes.rb

Image#colors with PseudoClass returns different value between ImageMagick 6.7 and 6.9.
Seems it is tough to test returned value of Image#colors.
* ImageMagick 6.7.7
```
153:     assert_equal(0, @img.colors)
154:     img = @img.copy
155:     img.class_type = Magick::PseudoClass
=> 156:     assert_equal(40, img.colors)
157:     assert_raise(NoMethodError) { img.colors = 2 }
158:   end
159:
<40> expected but was
<10000>
```
* ImageMagick 6.9.10
```
153:     assert_equal(0, @img.colors)
154:     img = @img.copy
155:     img.class_type = Magick::PseudoClass
=> 156:     assert_equal(40, img.colors)
157:     assert_raise(NoMethodError) { img.colors = 2 }
158:   end
159:
<40> expected but was
<41>
```
`Image#colors` just returns property value of `image->colors` set by `ImageMagick`. …

[IM6.9][IM6.7] Fix test_colors()

---

test/Image_attributes.rb

We use `GetImageType()` in ImageMagick API to retrieve image type.
The API uses `IsGrayImage()` to detect GrayscaleMatteType.
```
if (IsGrayImage(image,exception) != MagickFalse)
{
if (image->matte != MagickFalse)
return(GrayscaleMatteType);
return(GrayscaleType);
}
```
https://github.com/ImageMagick/ImageMagick6/blob/27b1c74979ac473a430e266ff6c4b645664bc805/magick/attribute.c#L771-L776
We have known that the API have breaking change.
https://github.com/rmagick/rmagick/blob/1c5aed2fd15f2aa5f6ae0227e8c9b7437d11d92d/ext/RMagick/rmimage.c#L7156-L7163
So, I think test_image_type() should not test distinct value.

[IM6.9][IM6.7] Fix test_image_type()

---

ext/RMagick/extconf.rb

This patch decorates error message to notice it by user ease.
Before | After
-- | --

Improve error message

---

test/Image_attributes.rb

`GetNumberColors()` API returns different value between ImageMagick 6.8 and 6.9.
```
498:
499:   def test_number_colors
500:     assert_nothing_raised { @hat.number_colors }
=> 501:     assert_equal(27_942, @hat.number_colors)
502:     assert_raise(NoMethodError) { @hat.number_colors = 2 }
503:   end
504:
<27942> expected but was
<27980>
```
I think we don't need to test distinct value because Image#{number_colors, total_colors} just return `GetNumberColors()` value.

[IM6.9] Fix test_number_colors() and test_total_colors()

---

test/ImageList2.rb

Whether `Montage#frame=` will be causes exception with GIF image,
it is strongly depends on ImageMagick behavior.
And seems ImageMagick behavior was changed between 6.8 and 6.9.
```
Failure: <Magick::ImageMagickError> exception expected but none was thrown.
test_montage(ImageList2UT)
/Users/watson/prj/rmagick/test/ImageList2.rb:204:in `test_montage'
201:       montage = ilist.montage { self.font = 2 }
202:       assert_equal(@ilist, ilist)
203:     end
=> 204:     assert_raise(Magick::ImageMagickError) do
205:       montage = ilist.montage { self.frame = 'z' }
206:       assert_equal(@ilist, ilist)
207:     end
```
I think this test is not appropriate.

[IM6.9] Fix test_montage()

---

ext/RMagick/rmagick.c

It is better to use the methods here instead, these methods are also available in ImageMagick 7 and that will make it easier to port.
And I also don't understand why there is a check for `magick_info->encoder` before `magick_info->adjoin)`. Even if there is only a decoder it can still support multi-image files.

Use methods instead.

---

ext/RMagick/rmdraw.c

This patch will use expected type for variable to get rid of following compiler warning.
```
rmdraw.c:315:15: warning: result of comparison of constant 100 with expression of type 'WeightType' is always true
[-Wtautological-constant-out-of-range-compare]
if (w < 100 || w > 900)
~ ^ ~~~
rmdraw.c:315:26: warning: result of comparison of constant 900 with expression of type 'WeightType' is always false
[-Wtautological-constant-out-of-range-compare]
if (w < 100 || w > 900)
~ ^ ~~~
2 warnings generated.
```

Get rid of compiler warning

---

ext/RMagick/rmdraw.c
ext/RMagick/rminfo.c
ext/RMagick/rmpixel.c

QueryColorDatabase will no longer be available in ImageMagick 7 so it will be better to use QueryColorCompliance instead.

Use QueryColorCompliance instead of QueryColorDatabase.

---

ext/RMagick/extconf.rb
lib/rmagick/version.rb

This PR changes the method that is used to determine the version of ImageMagick. It searches for ImageMagick-6* instead of Wand or MagickWand. This fixes an issue when both ImageMagick 6 and 7 can be found with pck-config. And it also makes sense to remove Wand because that part of ImageMagick is not used by this library.

Use a different method to get the compiler flags for ImageMagick.

---

ext/RMagick/rmimage.c
test/Image2.rb
test/Image_attributes.rb

This PR fixes the unit tests for newer versions of ImageMagick. 
Two tests fail because of this patch: https://github.com/ImageMagick/ImageMagick/commit/0059300b3777fa505c1856b05b2e36ee45189b24. The unit tests now checks the size of the string for when the value that is returned also contains the alpha channel.
Another test that fails is because previous version of ImageMagick would change an image from `DirectClass` to `PseudoClass` inside the `CompressImageColormap` method. This is no longer happening and that is why the assert has been disabled. And the `Image_compress_colormap_bang` method has also been changed to raise a warning when this has happened.

Fix unit tests

---

ext/RMagick/rmagick.h
ext/RMagick/rmenum.c
ext/RMagick/rmilist.c

This removes a define that is constant. Maybe this was another value in a really ancient version of ImageMagick but it can be removed now.

Removed constant define.

---

.travis.yml
before_install_linux.sh

This PR changes the Travis build to improve the build speed. This includes the following changes:
- The ImageMagick build now includes two extra flags that disables building Magick++ and the documentation . The latter requires a more recent version of ImageMagick but was added in advance.
- The current build checks every version of ImageMagick with every version of Ruby. In this PR this is changed to only build the recent version of ImageMagick with every Ruby version and only build the old version and hdri on one version of Ruby.

Faster build

---

ext/RMagick/rmimage.c

This patch will use expected type for variable to get rid of following compiler warning.
```
rmimage.c:8309:16: warning: address of array 'image->filename' will always evaluate to 'true' [-Wpointer-bool-conversion]
if (image->filename)
~~  ~~~~~~~^~~~~~~~
1 warning generated.
```
`image->filename` has declared as following in ImageMagick.
```
char
magick[MaxTextExtent],
unique[MaxTextExtent],
zero[MaxTextExtent],
filename[MaxTextExtent];
```
The address of `filename[MaxTextExtent]` always is not `NULL`.
So, this patch will remove unnecessary `if` sentence to get rid of compiler warning.

Get rid of compiler warning about `image->filename`

---

ext/RMagick/extconf.rb
ext/RMagick/rmagick.h
ext/RMagick/rmimage.c
ext/RMagick/rmutil.c

rb_frame_this_func() was introduced at Ruby 1.9.0
Maybe, there is THIS_FUNC() definition to support Ruby 1.8.x.
However, now we don't support that.
So, now we can use rb_frame_this_func() directly.

Use rb_frame_this_func() directly instead of THIS_FUNC() macro

---

.appveyor.yml
.circleci/config.yml
.travis.yml

Also add back builds across versions of ruby. We've seen a number of odd
regressions with different combinations of Ruby and ImageMagick, so even
though it slows down the build, I think we're probably better off
testing all combinations.

CI: add ImageMagick 6.9 to CI build

---

rmagick.gemspec

Newer Ruby shows the following notice message what `has_rdoc=` method is deprecated.
```
$ ruby -v
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]
$ rake build
gem build -V rmagick.gemspec
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from rmagick.gemspec:29.
Successfully built RubyGem
Name: rmagick
Version: 3.0.0
File: rmagick-3.0.0.gem
```
This PR will remove `has_rdoc=` setting because it is `Deprecated and ignored.`.
https://apidock.com/ruby/Gem/Specification/has_rdoc%3D

gemspec: Remove deprecated has_rdoc=

---

ext/RMagick/rmagick.h
ext/RMagick/rmmain.c

This PR adds a new define call `ENUMERATORV` that can be used for enum values where the name is different from the value in ImageMagick. And this PR moves the enumeration defines from the header file to the code file where they are used.

Add new enumerator define

---

ext/RMagick/rmfill.c

This PR changes the use of `unsigned long` and `long int` to the correct type (`ssize_t`).

Use ssize_t instead.

---

test/Info.rb

I introduced `GC.stress` to test GC problems.
https://github.com/rmagick/rmagick/pull/468
However, it take a time to finish `test_monitor`.
And, seems that `GC.stress` is too much for this case.
So, this PR change to `GC.start`.
By this changing, test execution time will reduce from 60sec to 40sec.
* Before
```
$ rake
...
Finished in 60.401073433 seconds.
------------------------------------------------------------------------------------------------------------------------------
402 tests, 232622 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
------------------------------------------------------------------------------------------------------------------------------
6.66 tests/s, 3851.29 assertions/s
```
* After
```
$ rake
...
Finished in …
```

Use GC.start instead of GC.stress to reduce test execution time

---

.appveyor.yml

Sometime, it fails to download ImageMagick installer binary on AppVeyor, like
```
Build started
git clone -q --branch=master https://github.com/rmagick/rmagick.git C:\projects\rmagick
git checkout -qf 23b133b1ff06ea43c592276c0619e9e9562f971e
Running Install scripts
appveyor DownloadFile https://ftp.icm.edu.pl/pub/graphics/ImageMagick/binaries/ImageMagick-%IMAGEMAGICK_VERSION%-%PATCH_VERSION%-Q16-x64-dll.exe
Error downloading remote file: One or more errors occurred.
Inner Exception: The remote name could not be resolved: 'ftp.icm.edu.pl'
Command exited with code 2
```
https://ci.appveyor.com/project/mockdeep/rmagick/builds/23472095/job/s5jjgd03o1tkqmm1
I don't like to restart CI build by download failure.
So, this PR introduce retry command. …

CI: Add “appveyor-retry” to retry download binary

---

doc/magick.html
ext/RMagick/rmagick.c
test/Magick.rb

This pull adds support for setting a TimeResource limit.
The limit itself is a bit tricky to use as it's evaluated between subsequent calls to GetImagePixelCache, rather than being per operation. The only way reset it is to call SetMagickResourceLimit which calls ResetPixelCacheEpoch, effectively forcing you to call Magic.limit_resource(:time, <int>) before anything you want to cap.

Add TimeResource support

---

ext/RMagick/rmkinfo.c

This is a private method inside ImageMagick and should not be used. This is the first step towards removing this method.

Deprecate KernelInfo#zero_nans.

---

ext/RMagick/rmkinfo.c

This method has been made private in ImageMagick 7 and I don't think anyone will/should use this in ImageMagick 6.

Deprecate KernelInfo#show.

---

ext/RMagick/extconf.rb
ext/RMagick/rmagick.h

int8_t, uint8_t,… etc are declared in stdint.h
However, seems RMagick does not there types or macro defined in stdint.h.
By removing headers checking, it will reduce a time generating Makefile slightly.

Remove unused stdint.h

---

ext/RMagick/rmagick.h
ext/RMagick/rmpixel.c

This PR removes rm_set_magick_pixel_packet from the header file, corrects the argument type and makes it static in rmpixel.c

Refactor rm_set_magick_pixel_packet

---

ext/RMagick/extconf.rb

We don’t use long double type in RMagick.
By removing have_type(), it will reduce a time generating Makefile slightly.

Remove have_type for long double

---

ext/RMagick/rmenum.c

This PR removes the return statements from the `ENUM_new` and `ENUM_name` methods and moves the `default:` case to the bottom of the switch.

Use default in case statement instead.

---

ext/RMagick/rmkinfo.c

This PR corrects the indentation of the `rmkinfo.c` file. All other files use 4 spaces but this file only has 2 spaces.

Corrected indentation.

---

test/Draw.rb
test/test_all_basic.rb

This patch will improve coverage of rmdraw.c
* Before
- Line coverage : 21.2 %
- Functions : 38.5 %
* After
- Line coverage : 96.4 %
- Functions : 96.2 %

Add Draw tests

---

ext/RMagick/rmagick.h
ext/RMagick/rmilist.c
ext/RMagick/rmimage.c
ext/RMagick/rmmain.c
test/Image2.rb

This PR fixes the issue that was reported in #508. The `FxImageChannel` method only operates on a single image. The `Image_fx` method has been added and the `ImageList_fx` has been marked as deprecated.

Add Image#fx method

---

.rubocop_todo.yml
test/Enum.rb
test/test_all_basic.rb

This patch will improve coverage of rmenum.c
* Before
- Line coverage : 52.6 %
- Functions : 83.7 %
* After
- Line coverage : 57.4 %
- Functions : 89.8 %
Related to #542

Add Enum tests

---

ext/RMagick/rmagick.h
ext/RMagick/rmimage.c
ext/RMagick/rmpixel.c

The `Color_to_PixelPacket` method was preserved because I thought I would need this for the ImageMagick 7 changes but it turns out that I don't it. This PR removes that method.

Remove Color_to_PixelPacket.

---

ext/RMagick/rmagick.h
ext/RMagick/rmilist.c
ext/RMagick/rmimage.c

The `rmagick.h` file has some defines that appear to be for older versions of Ruby. This PR removes the defines and replaces them with the values in the other files.

Use rb_io instead of the defines.

---

ext/RMagick/rmutil.c

This PR removes the automatic allocation of the ImageInfo that is broken. The `my_info` is created in case `info` is `NULL` but this is not used in the call to `rm_acquire_image`. And all the calls to this method are also from places where the value cannot be null. I have also removed the `RB_GC_GUARD` because we return the value.
And it looks like we could move this method to the `rminfo.c` file but that should be something for another PR.

Removed automatic allocation of the ImageInfo that is broken.

---

.travis.yml
before_install_linux.sh

This PR will skip compiling ImageMagick if the built cache is existed
Before it take a 63.56 sec to install ImageMagick.
By this, it will be reduced to 29.28 sec if built cache was existed.

CI: Use built cache to skip compiling on Travis

---

ext/RMagick/rmimage.c
test/Image1.rb

This PR fixes some issues in the `Image_color_histogram` method:
- `SetImageStorageClass` should be used instead of a custom implementation.
- The check `exception->severity != UndefinedException` will also be true for a warning but `rm_check_exception` will not raise an exception. But `histogram` was already freed at this point and that will cause issues later in the method. This has been resolve by using `rm_should_raise_exception` instead.

Fix color histogram

---

test/ImageList1.rb
test/ImageList2.rb

This patch will improve coverage of rmilist.c
* Before
- Line coverage : 78.3 %
- Functions : 84.6 %
* After
- Line coverage : 91.7 %
- Functions : 92.3 %

Add ImageList tests

---

ext/RMagick/rmimage.c
test/Image_attributes.rb

This patch should fix https://github.com/rmagick/rmagick/issues/554

Fix Image#iptc_profile does not work with older ImageMagick

---

test/Info.rb

This patch will improve coverage of rminfo.c
* Before
- Line coverage : 80.4 %
- Functions : 87.2 %
* After
- Line coverage : 95.1 %
- Functions : 98.2 %
Related to #542

Add Info tests

---

test/ImageList2.rb

This patch will improve coverage of rmmontage.c
* Before
- Line coverage : 78.2 %
- Functions : 85.7 %
* After
- Line coverage : 97.8 %
- Functions : 100.0 %

Add Montage tests

---

ext/RMagick/rmimage.c

`kernel_info = AcquireKernelInfo("1");` will allocate memory area in `kernel_info->values`.
If override the pointer in `kernel_info->values`, it does not have a chance to release the area any more.
https://github.com/rmagick/rmagick/blob/b9c48b6c8b593422c3e5cbc1d4e76b671ab2db4b/ext/RMagick/rmimage.c#L10835
To suppress memory allocation in `kernel_info->values`, this PR changes to use `AcquireKernelInfo(NULL)`.
* Before
```
$ ruby test.rb
Process: 1395: RSS = 198 MB
```
* After
```
$ ruby test.rb
Process: 1961: RSS = 72 MB
```
* Test code
```ruby
img = Magick::Image.new(20, 20)
img.recolor([1, 1, 2, 1])
end
GC.start
```

Fix memory leak in Image#recolor

---

test/Image1.rb
test/Image2.rb
test/Image3.rb
test/Image_attributes.rb

This patch will improve coverage of rmimage.c
* Before
- Line coverage : 84.4 %
- Functions : 98.4 %
* After
- Line coverage : 93.0 %
- Functions : 99.2 %

Add Image tests

---

.rubocop_todo.yml
test/Pixel.rb

This patch will improve coverage of rmpixel.c
* Before
- Line coverage : 65.1 %
- Functions : 40.9 %
* After
- Line coverage : 96.4 %
- Functions : 100.0 %

Add Pixel tests

---

test/Struct.rb

This patch will improve coverage of rmstruct.c
* Before
- Line coverage : 62.6 %
- Functions : 57.1 %
* After
- Line coverage : 94.9 %
- Functions : 100.0 %

Add Struct tests

---

.rubocop_todo.yml
examples/identify.rb

Fix https://github.com/rmagick/rmagick/issues/573
This PR will change following things.
1. Use valid constant. (GrayColorspace -> GRAYColorspace)
2. Use Kernel.sprintf instead of Kernel.format. 
Because this example adds method in `Magick::Image` using monkey patch.
However,  `Magick::Image` already `format` method as property and this example calls `Magick::Image#format`, after then raises ArugmentError exception.

Fix a bug that `identify.rb` example doesn't work

---

ext/RMagick/rmimage.c

Fix #572
The method has passed Ruby object into ImageMagick API directly.
The Ruby object might has huge address for ImageMagick API.
So, ImageMagick API will raise following exception.
```
Caught exception: width or height exceeds limit `../doc/ex/images/model.miff[0]' @ error/cache.c/SetPixelCacheNexusPixels/5171
```
This patch will pass expected value into ImageMagick API.

Fix a bug in Image#reduce_noise which might cause SEGV

---

examples/vignette.rb

Save image for non-X11 environment instead of display in `examples/vignette.rb`

---

ext/RMagick/rminfo.c

This PR deprecates the group property of the Info class. This is no longer available in ImageMagick 7 and most likely not used by users of this library.

Deprecated the group property of the Info class.

---

ext/RMagick/rmimage.c

This PR deprecates the blur property of the Image class. This is no longer available in ImageMagick 7 and most likely not used by users of this library.

Deprecated the blur property of the Image class.

---

examples/constitute.rb
examples/crop_with_gravity.rb
examples/demo.rb
examples/histogram.rb
examples/image_opacity.rb

It is easy to handle when saved in the general PNG format.

Save PNG format instead of ImageMagick miff format in example codes

---

ext/RMagick/rmimage.c
ext/RMagick/rminfo.c

Related to #578 and #579.
Attribute writer method should return self.
https://github.com/rmagick/rmagick/blob/f8215532d56487fe4229bccbdc3e77518fffaf60/ext/RMagick/rmagick.h#L423-L434
This patch will get rid of following warning message.
```
$ make
…
rmimage.c:1748:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
1 warning generated.
compiling rminfo.c
rminfo.c:1644:1: warning: control may reach end of non-void function [-Wreturn-type]
}
```

Attribute writer method should return self

---

ext/RMagick/rmimage.c

`GammaImage` no longer has an `char *` argument in ImageMagick 7. This PR modifies the `gamma_correct` method to do similar logic that is done inside `GammaImage` in ImageMagick 6 and call `GammaImageChannel` instead. With this modification it will be easier to make this method compatible with ImageMagick 7.

Use GammaImageChannel instead of GammaImage to prepare for ImageMagick 7.

---

lib/rmagick_internal.rb

Image#matte was marked as deprecate at https://github.com/rmagick/rmagick/commit/c00a81d377b31e0c2daf6bf80450663afd5e2dd6
This patch will get rid of following warning message.
```
$ ruby doc/ex/affine_transform.rb
/Users/watson/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/rmagick-3.1.0/lib/rmagick_internal.rb:918: warning: Image#matte is deprecated; use Image#alpha.
```

Use Image#alpha? instead of Image#matte in internal library

---

ext/RMagick/rmagick.h
ext/RMagick/rmenum.c
ext/RMagick/rmimage.c

This PR reintroduces an alternative for the `CompositeOperator_new` method that was removed in #587. This new method is called `CompositeOperator_find`. With this method we get type safety that we don't get with Enum_find and we only have `Enum_find(Class_CompositeOperator,` at one spot.

Add CompositeOperator_find that can be used to find the ruby value of  a CompositeOperator value.

---

test/test_all_basic.rb

Related to https://github.com/rmagick/rmagick/issues/588
Seems simplecov generate wrong report if it was required after 'test/unit’.
* Before
simplecov reports 33.0% covered in rmagick_internal.rb
* After
simplecov reports 74.8% covered in rmagick_internal.rb

Require 'simplecov' before 'test/unit' to retrives valid result

---

ext/RMagick/rmagick.h
ext/RMagick/rmenum.c
ext/RMagick/rmimage.c
test/Enum.rb

This PR fixes the issue that was reported in #593 for the virtual pixel enumeration.

Find the value of the virtual pixel enumeration instead of creating one.

---

ext/RMagick/rmimage.c
test/Image1.rb

While adding a unit test for #594 I found an issue. The storage type of the image should not be changed to undefined.

Don't allow undefined class.

---

ext/RMagick/rmagick.h
ext/RMagick/rmenum.c
ext/RMagick/rmimage.c
test/Enum.rb

This PR fixes the issue that was reported in #593 for the class type enumeration.

Find the value of the class type enumeration instead of creating one.

---

ext/RMagick/rmagick.h
ext/RMagick/rmimage.c
ext/RMagick/rmmain.c
lib/obsolete.rb
lib/rmagick_internal.rb

Renamed AlphaChannelType to AlphaChannelOption to prepare for ImageMagick 7 and added alias for backwards compatibility. 
I tried to put in a warning so we could deprecate it and remove it when a major bump is done but I could not figure out how to do that. I tried to use `rb_define_module_function` and do a warning in the method and return `rb_const_get(Module_Magick, rb_intern("AlphaChannelOption"))` but that does not work. It looks like only lowercase names can be used. Maybe you have some idea how to do this @Watson1978 and maybe you know how to do this in Ruby @mockdeep?

Renamed AlphaChannelType to AlphaChannelOption

---

doc/ex/coalesce.rb
doc/ex/get_pixels.rb
doc/ex/implode.rb
doc/ex/mask.rb
doc/ex/matte_fill_to_border.rb
doc/ex/matte_floodfill.rb
doc/ex/matte_replace.rb
examples/demo.rb
examples/find_similar_region.rb
examples/histogram.rb
examples/vignette.rb

Image#matte= was marked as deprecate at https://github.com/rmagick/rmagick/commit/c00a81d377b31e0c2daf6bf80450663afd5e2dd6
This patch will get rid of warning message when run examples.

Use Image#alpha instead of Image#matte= in examples

---

ext/RMagick/rmagick.h
ext/RMagick/rmenum.c
ext/RMagick/rmimage.c
test/Enum.rb

This PR fixes the issue that was reported in #593 for the filter types enumeration.

Find the value of the filter types enumeration instead of creating one.

---

ext/RMagick/rmagick.h
ext/RMagick/rmimage.c
ext/RMagick/rmmain.c
lib/obsolete.rb

Renamed DistortImageMethod to DistortMethod to prepare for ImageMagick 7 and added alias for backwards compatibility.

Renamed DistortImageMethod to DistortMethod

---

ext/RMagick/rmagick.h
ext/RMagick/rmdraw.c
ext/RMagick/rmimage.c
ext/RMagick/rminfo.c
ext/RMagick/rmmontage.c

As noticed in #585 there are attribute writers that return `self` instead of the `value` that was passed in. This PR fixes that for all the attribute writers.

Return value instead of self in attribute writers.

---

lib/rmagick_internal.rb
test/Draw.rb

This PR fixes the issue reported in #604. The name of the clip-path should be between quotes. Recent version of ImageMagick are more strict about this.

Fixed setting the name of the clip path.

---

ext/RMagick/rmagick.h
ext/RMagick/rmenum.c
ext/RMagick/rmimage.c
test/Enum.rb

This PR fixes the issue that was reported in #593 for the InterpolatePixelMethod enumeration.

Find the value of the InterpolatePixelMethod enumeration instead of creating one

---

.travis.yml
before_install_linux.sh

1. When run `rubocop`, it is unnecessary to install ImageMagick. This patch will remove the installation.
2. `rubocop` cache the result in `~/.cache/rubocop_cache`. This patch will set up rubocop cache directory to reduce running time.

CI: Boost STYLE_CHECKS running time

---

.travis.yml
before_install_linux.sh

Move Trusty environment to Xenial in order to use `addons:apt:packages:` in travis.yml
https://docs.travis-ci.com/user/reference/xenial/
`sudo apt-get update` update all repository information.
But, `addons:apt:...` way just update necessary information to install library.
Seems it will reduce set up time slightly.

CI: Reduce apt update time

---

.travis.yml

We have added cache mechanism at https://github.com/rmagick/rmagick/pull/521
It cache the build objects without ccache.
When the huge cache will be stored/retored, it will take a time slightly.
This patch will remove cache directory of ccache from travis.yml to remove redundant cache object and it will reduce the CI running time.

CI: Remove ccache dir from travis.yml

---

ext/RMagick/rmagick.h
ext/RMagick/rmenum.c
ext/RMagick/rmimage.c
ext/RMagick/rmmain.c
lib/obsolete.rb
test/Enum.rb
test/Image_attributes.rb

Renamed InterpolatePixelMethod to PixelInterpolateMethod to prepare for ImageMagick 7 and added alias for backwards compatibility.

Renamed InterpolatePixelMethod to PixelInterpolateMethod

---

ext/RMagick/rmagick.h
ext/RMagick/rmmain.c
ext/RMagick/rmpixel.c
test/Pixel.rb

This PR adds an alpha property to prepare for ImageMagick 7. After this has been merged the `opacity` property will become deprecated and users will be informed to use `alpha` instead.

Added alpha property to the pixel class.

---

ext/RMagick/rmagick.h
ext/RMagick/rmilist.c
ext/RMagick/rmmain.c
lib/obsolete.rb
test/ImageList2.rb

Renamed ImageLayerMethod to LayerMethod to prepare for ImageMagick 7 and added alias for backwards compatibility.

Renamed ImageLayerMethod to LayerMethod

---

ext/RMagick/rmmain.c

This patch will remove following warning message in compiling.
```
rmmain.c: In function 'test_Magick_version':
rmmain.c:1705:36: warning: passing argument 1 of 'GetMagickVersion' from incompatible pointer type [-Wincompatible-pointer-types]
version_str = GetMagickVersion(&version_number);
```

Use valid type to get rid of warning message

---

ext/RMagick/rmagick.c
ext/RMagick/rmagick.h
ext/RMagick/rmimage.c
ext/RMagick/rminfo.c
ext/RMagick/rmpixel.c
ext/RMagick/rmutil.c

This patch will remove following warning message in compiling.
```
rmagick.c:189:11: warning: explicitly assigning value of variable of type 'VALUE' (aka 'unsigned long') to itself [-Wself-assign]
class = class;      // defeat "never referenced" message from icc
~~~~~ ^ ~~~~~
```
We can indicate the unused variable to compiler using compiler attributes.
https://clang.llvm.org/docs/AttributeReference.html#maybe-unused-unused
This patch will introduce macro in
https://github.com/ruby/ruby/blob/7e72ce0f734113e3e215a74b440092443e957d45/st.c#L117-L125

Remove self assign warning message in compiling

---

ext/RMagick/extconf.rb

If we enforce C99, we can use c99 feature, we can use `snprintf` without checking
https://github.com/rmagick/rmagick/blob/e9ad483dc0a748cf42f59e32d612b66b942aa678/ext/RMagick/extconf.rb#L304

Enforce C99

---

ext/RMagick/rmpixel.c

This PR deprecates the opacity property of the Pixel class. This has been replaced with the new alpha property method. (#617).

Deprecated the opacity property of the Pixel class.

---

ext/RMagick/rmagick.h
ext/RMagick/rmilist.c
ext/RMagick/rmmain.c
test/ImageList1.rb

This PR adds the `combine` method to the `ImageList` class. This method is a replacement for the static `combine` method in the `Image` class. This is done because ImageMagick 7 needs a colorspace instead of channels. And with this new signature it is also still compatible with ImageMagick 6.
Making `combine` deprecated in the `Image` class should be a new PR after this one has been merged.

Added combine to the ImageList class.

---

ext/RMagick/extconf.rb
ext/RMagick/rmimage.c
ext/RMagick/rminfo.c
ext/RMagick/rmutil.c

1. have_func checking take a time slightly.
2. C99 support `snprintf` function by default.
https://en.wikipedia.org/wiki/C99
Now, RMagick will be built with C99 by https://github.com/rmagick/rmagick/pull/634

Remove have_func checking for snprintf

---

ext/RMagick/rmdraw.c
ext/RMagick/rminfo.c

This patch will get rid of following  overflow warning message.
```
rmdraw.c:1103:31: warning: '%s' directive writing up to 4095 bytes into a region of size between 4036 and 4080 [-Wformat-overflow=]
(void) sprintf(primitive, "image %s %g,%g,%g,%g '%s'", op, x, y, width, height, name);
^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Use snprintf to get rid of overflow warning message

---

ext/RMagick/rmagick.h

This patch will get rid of following warning message in compiling.
```
compiling ../../../../ext/RMagick/rmagick.c
In file included from /home/travis/.rvm/rubies/ruby-2.3.8/include/ruby-2.3.0/ruby/ruby.h:1988:0,
from /home/travis/.rvm/rubies/ruby-2.3.8/include/ruby-2.3.0/ruby.h:33,
from ../../../../ext/RMagick/rmagick.h:28,
from ../../../../ext/RMagick/rmagick.c:13:
/home/travis/.rvm/rubies/ruby-2.3.8/include/ruby-2.3.0/ruby/intern.h:923:29: warning: ‘struct timespec’ declared inside parameter list
void rb_timespec_now(struct timespec *);
```

Remove unnecessary header including to get rid of warning message

---

ext/RMagick/extconf.rb
ext/RMagick/rmagick.h

Ruby core also has used `sys/types.h` without any checking.
https://github.com/ruby/ruby/blob/c3cf1ef9bbacac6ae5abc99046db173e258dc7ca/ruby.c#L25
I think `sys/types.h` will be used on almost system.
By removing `have_header` checking, it will reduce a time slightly in generating Makefile.

Remove have_header for sys/types.h

---

ext/RMagick/rmenum.c

This PR removes `ENUM_SET_NAME` that is no longer used.

Removed ENUM_SET_NAME.

---

lib/obsolete.rb

This PR deprecates StaticGravity because this is nog longer supported in ImageMagick 7.  CenterGravity should be used instead.

Deprecated StaticGravity because this will be removed in ImageMagick 7.

---

ext/RMagick/rmimage.c

This PR deprecates the sync_profiles method of the Image class because this has been made private in ImageMagick 7.

Deprecated the sync_profiles method of the Image class

---

ext/RMagick/rmmain.c
lib/obsolete.rb
test/lib/Obsolete.rb

This PR adds the new MetricType values that will be used in ImageMagick 7 and adds aliases for backwards compatibility.

Added the new MetricType values that will be used in ImageMagick 7

---

.travis.yml

By using preinstalled ruby, we will cut a time to set up Ruby in Travis.
* Before
22.36 sec
* After
0.87 sec
Travis pre-installed following Ruby versions.
* ruby-2.3.8
* ruby-2.4.5
* ruby-2.5.3
https://travis-ci.org/rmagick/rmagick/jobs/528851394#L154

CI: Use preinstalled ruby in Travis

---

ext/RMagick/rminfo.c
test/Info.rb

The view value of the Info class should be freed before it is overwritten to prevent a memory leak and this PR fixes that.

Fix memory leak when overwritting the view value of the Info class.

---

ext/RMagick/rmimage.c

This PR deprecates the `combine` method of the `Image` class. This has been replaced with the new `combine` method in the `ImageList` class (#589).

Deprecated the combine method of the Image class.

---

ext/RMagick/rminfo.c
test/Info.rb

This PR changes the setter of the authenticate property to also allow an empty string.

Allow empty string for authenticate

---

ext/RMagick/rmagick.h
ext/RMagick/rmmain.c
lib/obsolete.rb
test/Magick.rb

This PR adds new alpha constants to prepare for ImageMagick 7 and deprecates OpaqueOpacity and TransparentOpacity.

Add new alpha constants to prepare for ImageMagick 7

---

ext/RMagick/rmenum.c
test/Enum.rb

If StorageType enum is added in ImageMagick, we have to inssert switch/case expression.
This patch will avoid that.

Refactor StorageType_name() function

---

ext/RMagick/rmenum.c
test/Enum.rb

If StretchType enum is added in ImageMagick, we have to inssert switch/case expression.
This patch will avoid that.

Refactor StretchType_name() function

---

ext/RMagick/rmenum.c
test/Enum.rb

If StyleType enum is added in ImageMagick, we have to inssert switch/case expression.
This patch will avoid that.

Refactor StyleType_name() function

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#bezier has been accepted any value.
If wrong value was given, it doesn't notice the mistakes until bezier primitive is performed by Draw#draw.
```
draw.stroke('red')
draw.bezier(20, 'x', 20, 30, 320, 330, 320, 180)
draw.draw(img)
#=> test.rb:9:in `draw': non-conforming drawing primitive definition `bezier' @ error/draw.c/RenderMVGContent/4336 (Magick::ImageMagickError)
from test.rb:9:in `<main>'
```
Draw#bezier should check the parameter value and raise exception if wrong value was given.

Draw#bezier should raise exception if wrong value was given

---

ext/RMagick/rmimage.c
lib/rmagick_internal.rb
test/Image2.rb

This PR deprecates the Image#opacity method and informs the user to use Image#alpha instead. And this also removes the use of this method from the code.

Deprecated Image#opacity.

---

lib/rmagick_internal.rb
test/Draw.rb
test/Image1.rb
test/Image2.rb
test/ImageList1.rb
test/Magick.rb

This PR changes the code to use the new enumeration names in the unit tests and refactors some of the unit tests to use a different method.

Use the new enumeration names in the unit tests 

---

ext/RMagick/extconf.rb

ImageMagick might use X11 library.
However, RMagick has not used it directly.

Remove unnecessary X11 library checking

---

ext/RMagick/rmimage.c

This PR fixes a possible memory leak in Image_sparse_color where `new_image` will leak when `CHECK_EXCEPTION()` is called and an exception is raised.

Fixed memory leak in Image_sparse_color.

---

ext/RMagick/rmimage.c
test/Image2.rb

This PR changes the order from an unsigned integer into an integer to allow checking for negative values and report an argument error instead of trying to do an allocation.

Change order for convolve into an integer and check for negative values.

---

ext/RMagick/rmimage.c

This PR adds set_image_mask that will also have an implementation with different arguments in ImageMagick 7. Merging this first will give a better difference in the ImageMagick 7 merge.

Added set_image_mask to prepare for ImageMagick 7.

---

ext/RMagick/rmimage.c

The call to `rm_check_image_exception` should be moved because this could otherwise result in leaking `exception` and `new_image`. And there should be a check if `image->exception` will throw an exception and then free `new_image` before calling `rm_check_image_exception`

Changed order to fix memory leaks.

---

ext/RMagick/extconf.rb

This PR uses Use `gnu99` instead of `c99` for `__GNUC__` to fix the following compiler warnings:
```
/usr/local/include/ruby-2.6.0/ruby/intern.h:928:29: warning: 'struct timespec' declared inside parameter list will not be visible outside of this definition or declaration
void rb_timespec_now(struct timespec *);
```

Use gnu99 instead of c99 for __GNUC__.

---

test/Magick.rb

Font#{style, stretch} might return nil.
```
Failure:
<nil> expected to be instance_of?
<Magick::StyleType> but was
<NilClass>.
test_fonts(MagickUT)
/Users/watson/prj/rmagick/test/Magick.rb:82:in `block in test_fonts'
79:       assert_instance_of(String, f.name)
80:       assert_instance_of(String, f.description) unless f.description.nil?
81:       assert_instance_of(String, f.family)
=> 82:       assert_instance_of(Magick::StyleType, f.style)
83:       assert_instance_of(Magick::StretchType, f.stretch)
84:       assert_kind_of(Integer, f.weight)
85:       assert_instance_of(String, f.encoding) unless f.encoding.nil?
```
This PR will fix above error with running tests.

Fix test_font

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#color has been accepted any value as (x, y) coordinates.
If wrong value was given, it doesn't notice the mistakes until the primitive is performed by Draw#draw.
```
draw.color('x', 20, Magick::PointMethod)
draw.draw(img)
#=> t.rb:8:in `draw': non-conforming drawing primitive definition `color' @ error/draw.c/RenderMVGContent/4336 (Magick::ImageMagickError)
```

Draw#color should raise exception if wrong value was given

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#coopacitylor has been accepted any value.
```
draw.opacity('xxx')
draw.fill('tomato')
draw.rectangle(10, '10', 100, 100)
draw.draw(img)
```

Draw#opacity should raise exception if wrong value was given

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#fill_opacity has been accepted any value.
```
draw.fill_opacity('xxx')
draw.fill('blue')
draw.rectangle(10, '10', 100, 100)
draw.draw(img)
```

Draw#fill_opacity should raise exception if wrong value was given

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#stroke_opacity has been accepted any value.
```
draw.stroke_opacity('xxx')
draw.stroke('blue')
draw.stroke_width(10)
draw.rectangle(10, '10', 100, 100)
draw.draw(img)
```

Draw#stroke_opacity should raise exception if wrong value was given

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#font_weight has been accepted any value.
```
draw.font_weight('xxx')
draw.text(10, 100, 'Hello world')
draw.draw(img)
```

Draw#font_weight should raise exception if wrong value was given

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#pattern has been accepted any value.
```
draw.pattern('hat', 'x', 0, 20, 20) {}
draw.draw(img)
```

Draw#pattern should raise exception if wrong value was given

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#point has been accepted any value.
```
draw.point(10, 'x')
draw.draw(img)
```

Draw#point should raise exception if wrong value was given

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#font_size has been accepted any value.
```
draw.font_size('x')
draw.draw(img)
```

Draw#font_size should raise exception if wrong value was given

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#polygon has been accepted any value.
```
draw.polygon('x', 0, 8, 16, 16, 0, 0, 0)
draw.draw(img)
```

Draw#polygon should raise exception if wrong value was given

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#polyline has been accepted any value.
```
draw.polyline('x', 0, 16, 16)
draw.draw(img)
```

Draw#polyline should raise exception if wrong value was given

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#rotate has been accepted any value.
```
draw.rotate('x')
draw.draw(img)
```

Draw#rotate should raise exception if wrong value was given

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#scale has been accepted any value.
```
draw.scale('x', 2.0)
draw.draw(img)
```

Draw#scale should raise exception if wrong value was given

---

ext/RMagick/rmagick.h
ext/RMagick/rmimage.c
ext/RMagick/rmutil.c
test/Image3.rb

To have a smooth transition from ImageMagick 6 to ImageMagick 7 some of the arguments need to change from an opacity value to an alpha value. And after a chat @mockdeep and me came up with the following idea make sure the user will know that this is happening:
Instead of only a `Quantum` value
```ruby
img.transparent('white', Magick::TransparentOpacity)
```
A named argument should be used.
```ruby
img.transparent('white', alpha: Magick::TransparentAlpha)
```
If only a value is passed in the value will be changed from opacity to alpha and a warning will be raised to inform the user that they should use a named argument and switch from opacity to alpha.
This is the only idea we had to make sure that the user knows that they should change their opacity value into an alpha value. If you have …

Deprecated the use of an unnamed argument for the opacity value of Image#transparent

---

ext/RMagick/rmimage.c
test/Image1.rb
test/Image3.rb

To have a smooth transition from ImageMagick 6 to ImageMagick 7 some of the arguments need to change from an opacity value to an alpha value. Instead of only a `Quantum` value a named argument should be used. If only a value is passed in the value will be changed from opacity to alpha and a warning will be raised to inform the user that they should use a named argument and switch from opacity to alpha.

Deprecated the use of an unnamed argument for the opacity value of Image#black_threshold and Image#white_threshold.

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#stroke_dashoffset has been accepted any value.
```
draw.stroke_dashoffset('x')
draw.draw(img)
```

Draw#stroke_dashoffset should raise exception if wrong value was given

---

ext/RMagick/rmagick.h
ext/RMagick/rmimage.c
ext/RMagick/rmmain.c
lib/rmagick_internal.rb
test/Image2.rb

To have a smooth transition from ImageMagick 6 to ImageMagick 7 some of the arguments need to change from an opacity value to an alpha value. Instead of only a `Quantum` value a named argument should be used. If only a value is passed in the value will be changed from opacity to alpha and a warning will be raised to inform the user that they should use a named argument and switch from opacity to alpha.

Deprecated the use of an unnamed argument for the opacity value of Image#matte_flood_fill.

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#translate has been accepted any value.
```
draw.translate('x', 300)
draw.draw(img)
```

Draw#translate should raise exception if wrong value was given

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#text has been accepted any value.
```
draw.text('x', 50, 'Hello world')
draw.draw(img)
```

Draw#text should raise exception if wrong value was given

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#stroke_width has been accepted any value.
```
draw.stroke_width('x')
draw.draw(img)
```

Draw#stroke_width should raise exception if wrong value was given

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#matte has been accepted any value.
```
draw.matte(10, 'xxx', Magick::PointMethod)
draw.draw(img)
```

Draw#matte should raise exception if wrong value was given

---

ext/RMagick/rmimage.c
test/Image1.rb
test/Image3.rb

This PR renames some of the hash keys to have a consistent API as discussed in #711

Always use alpha as the key for the hash to have a consistent API.

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

Draw#{skewx, skewy} has been accepted any value.
```
draw.skewx('x')
draw.circle(100, 100, 125, 125)
draw.rectangle(65, 150, 135, 300)
draw.draw(img)
```

Draw#{skewx, skewy} should raise exception if wrong value was given

---

ext/RMagick/rmimage.c
test/Image2.rb

To have a smooth transition from ImageMagick 6 to ImageMagick 7 some of the arguments need to change from an opacity value to an alpha value. Instead of only a Quantum value a named argument should be used. If only a value is passed in the value will be changed from opacity to alpha and a warning will be raised to inform the user that they should use a named argument and switch from opacity to alpha.

Deprecated the use of an unnamed argument for the opacity value of Image#paint_transparent.

---

ext/RMagick/rmimage.c
test/Image3.rb

Fix #19
This patch will fix that Image#thumbnail keeps the aspect ratio of image.
```ruby
image = Magick::ImageList.new('./Flower_Hat.jpg').first
img = image.thumbnail(100, 100)
img.write('thumbnail.png')
```
* Result
Before | After
-- | -- 
(By ImageMagick)
```
$ convert Flower_Hat.jpg -thumbnail 100x100 test.png
```
* Original Image

Fix Image#thumbnail to keep image aspect ratio like ImageMagick

---

ext/RMagick/rmimage.c

To have consistent API that uses alpha instead of opacity we need to rename some of the arguments. This PR renames the arguments for Image#shadow and Image#tint.

Renamed arguments for Image#shadow and Image#tint.

---

ext/RMagick/rmimage.c

This PR corrects the documentation to show keywords instead of a value.

Use keywords in the documentation.

---

ext/RMagick/rmimage.c
test/Image3.rb

To have a smooth transition from ImageMagick 6 to ImageMagick 7 some of the arguments need to change from an opacity value to an alpha value. Instead of only a Quantum value a named argument should be used. If only a value is passed in the value will be changed from opacity to alpha and a warning will be raised to inform the user that they should use a named argument and switch from opacity to alpha.

Deprecated the use of an unnamed argument for the opacity value of Image#transparent_chroma.

---

ext/RMagick/rmdraw.c
test/Draw.rb

A buffer to generate geometry string is too small in edge case.
* OS : Ubuntu 19.04
* Compiler : gcc 8.3
```
img = Magick::Image.new(100, 100)
draw.annotate(img, 2**63, 2**63, 2**62, 2**62, 'Hello world')
```
```
$ rake build
$ CFLAGS='-g -O0 -fno-omit-frame-pointer -fsanitize=address -static-libasan' gem i pkg/rmagick-3.1.0.gem
$ LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libasan.so.5 LSAN_OPTIONS="detect_leaks=0" ruby test.rb
=================================================================
==15907==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffc73906d42 at pc 0x7f542c9bc415 bp 0x7ffc73906af0 sp 0x7ffc73906280
WRITE of size 80 at 0x7ffc73906d42 thread T0
#0 0x7f542c9bc414 in vsprintf (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x9d414)
#1 …
```

Fix stack-buffer-overflow in Draw#annotate

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

This PR adds `Draw#alpha` that replaces `Draw#matte` in ImageMagick 7.

Add Draw#alpha.

---

lib/rmagick_internal.rb

Draw#matte has been removed in ImageMagick 7 and should be marked as deprecated.

Mark Draw#matte as deprecated

---

lib/rmagick_internal.rb
test/lib/internal/Draw.rb

This PR will add missing method about  image primitive in ImageMagick.
* Sample
```
img = Magick::Image.new(200, 200)
draw.rectangle(5, 0, 195, 200)
draw.image(Magick::PlusCompositeOp, 10, 0, 180, 200, 'doc/ex/images/Flower_Hat.jpg')
draw.draw(img)
img.write('sample.png')
```
* Result

Add Draw#image

---

ext/RMagick/extconf.rb

pacman in ArchLinux will install `pkg-config` of ImageMagick 6 into `/usr/lib/imagemagick6/pkgconfig` which can't be searched by default.
```
FROM archlinux/base:latest
RUN pacman -Syy --noconfirm pkg-config make gcc ruby libmagick6 libxml2
WORKDIR /opt/rmagick
```
```
ImageMagick++-6.Q16HDRI.pc  ImageMagick++.pc  Magick++-6.Q16HDRI.pc    MagickCore.pc  MagickWand-6.Q16HDRI.pc  Wand-6.Q16HDRI.pc
ImageMagick-6.Q16HDRI.pc    ImageMagick.pc    MagickCore-6.Q16HDRI.pc  Magick++.pc    MagickWand.pc	       Wand.pc
```
```
WARNING:  You don't have /root/.gem/ruby/2.6.0/bin in your PATH,
gem executables will not run.
Building native extensions. This could take a while...
ERROR:  Error installing rmagick-3.1.0.gem:
ERROR: Failed to build gem native extension.
current directory: …
```

Add ArchLinux support

---

benchmarks/memory/README.md
benchmarks/memory/image_new.rb
benchmarks/memory/rmagick.gnuplot
ext/RMagick/extconf.rb
ext/RMagick/rmmain.c

This patch aims to goal to get Ruby's GC to work well.
For example, Ruby indicates Magick::Image object is only 40 bytes.
```ruby
require 'objspace'
puts ObjectSpace.memsize_of(img) #=> 40 bytes
```
However, ImageMagick allocates a lot of memory and associates to Magick::Image object.
And Ruby doesn't know that.
Please execute the following code. 
```ruby
4000.times do
end
```
Ruby will recognize that 40 * 4000 = 156 KB of memory has been allocated.
It may be low value as a threshold to run GC mark/sweep.
However, in fact, RMagick has been allocating more memory (156 KB + ImageMagick allocated memory).
When Ruby knows the correct memory usage, the GC works properly, and it makes system working more …

Enable managed memory feature

---

ext/RMagick/rmimage.c
test/Image1.rb
test/Image2.rb
test/Image3.rb

This PR adds extra checks to make sure that it is not allowed to add extra arguments to the methods that now require a named argument for alpha.

Check the number of arguments in the methods that now require a named argument for alpha.

---

ext/RMagick/rmimage.c
test/Image2.rb

If Image object doesn't have profile, Image#each_profile will cause a SEGV.
```ruby
img = Magick::Image.new(10, 10)
p img.each_profile do |name, value|
end
```
```
$ ruby test.rb
test.rb:4: [BUG] Segmentation fault at 0x0000000000000023
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-darwin18]
* ~/Library/Logs/CrashReporter
* /Library/Logs/CrashReporter
* ~/Library/Logs/DiagnosticReports
* /Library/Logs/DiagnosticReports
for more details.
Don't forget to include the above Crash Report log file in bug reports.
-- Control frame information -----------------------------------------------
c:0003 p:---- s:0009 e:000008 CFUNC  :p
c:0002 p:0041 …
```

Fix SEGV in Image#each_profile

---

ext/RMagick/rmimage.c

`Data_Get_Struct()` was already called in `rm_check_destroyed()`
https://github.com/rmagick/rmagick/blob/ac388ae931e6cf32a85d555670fb6fd1c636cf1e/ext/RMagick/rmimage.c#L9316
This patch will remove redundant assignment by `Data_Get_Struct()`.

Remove redundant assignment

---

examples/vignette.rb

`CopyOpacityCompositeOp` was marked as deprecated in #627

Example: Use CopyAlphaCompositeOp instead of deprecated CopyOpacityCompositeOp

---

examples/identify.rb

Image#matte was marked as deprecated in #530 and removed in #736

Example: Use Image#alpha instead of Image#matte

---

lib/rvg/rvg.rb

Pixel#opacity= was marked as deprecated in #619 and removed in #735
TransparentOpacity was marked as deprecated in #651
You can confirm with
```
$ cd doc/ex
$ ruby InitialCoords.rb
/Users/watson/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/rmagick-3.2.0/lib/rvg/rvg.rb:66: warning: constant Magick::TransparentOpacity is deprecated
```

 RVG: Use Pixel#alpha= and QuantumRange instead

---

examples/histogram.rb

Pixel#opacity= was marked as deprecated in #619 and removed in #735

Example: Use Pixel#alpha= instead

---

rmagick.gemspec

The RubyGems property rubyforge_project is removed without a replacement.

Gemspec: Drop EOL'd property rubyforge_project

---

ext/RMagick/rmimage.c
spec/rmagick/image/dissolve_spec.rb

ImageMagick 6.9 pulls the 'compose:args' artifact from the canvas image instead of the overlay image. The special_composite function now sets the 'compose:args' artifact in both images for 6.8 and 6.9 compatibility.
Added rspec test for Image#dissolve.

Dissolve on ImageMagick 6.9

---

ext/RMagick/rmenum.c

When RMagick prepares Enum object as a constant, the objects will keep alive because there have reference.
https://github.com/rmagick/rmagick/blob/fffaf1bce49f86edc5a2671d14f803e5acf12aff/ext/RMagick/rmmain.c#L40
However, Enum objects generated by the user calling `Enum#|` might become unnecessary.
In this case, garbaged objects cause memory leaks because there is no deallocator in Enum class.
This patch will fix memory leak in `Enum#|` by adding Enum deallocator.
* Before
```
$ ruby test.rb
Process: 48440: RSS = 244 MB
```
* After
```
$ ruby test.rb
Process: 49603: RSS = 12 MB
```
* Test code
```ruby
5000000.times do
enum1 = Magick::Enum.new(:foo, Random.rand(2**30))
enum2 = Magick::Enum.new(:bar, Random.rand(2**30))
enum3 = enum1 | enum2
end
GC.start
rss = `ps -o rss= …
```

Fix memory leak in Enum#|

---

ext/RMagick/rmimage.c

In ImageMagick 6 there are "overloads" for methods to only work on the specified channel. Those methods are no longer available in ImageMagick 7. To only change a specific channel a mask needs to be set. This PR adds some macros to make it easier to temporary change the channel mask.

Add macros for temporarily changing the channel mask of an image.

---

ext/RMagick/rmagick.h
ext/RMagick/rmfill.c
ext/RMagick/rmilist.c
ext/RMagick/rmimage.c

This PR adds the define that was spoken about in the PR where the changes in rmimage.c for ImageMagick 7 were merged.

Add define to check for ImageMagick 6 instead of using !defined(IMAGEMAGICK_7)

---

lib/rmagick_internal.rb

We don't need to declare instance variables in this way in Ruby, as
they'll be magically allocated as soon as they are referenced.

CodeQuality: remove instance variable declarations

---

spec/rmagick/image/channel_entropy_spec.rb
test/Import_Export.rb
test/Preview.rb
test/test_all_basic.rb

These create noise when running the tests that distract from test
failures and warnings.

remove some outputs from tests

---

ext/RMagick/rmdraw.c

This PR fixes the issue that was reported here: https://github.com/rmagick/rmagick/issues/800#issuecomment-536305385. The call to StringValuePtr will now be done before calling `AcquireExceptionInfo` to avoid a memory leak when `text` is `nil`.

Fix possible memory leak by calling StringValuePtr earlier.

---

ext/RMagick/rmimage.c

This PR fixes the problem report here: https://github.com/rmagick/rmagick/issues/800#issuecomment-536268649. In ImageMagick 7 the return value of `SeparateImage` should be used.

Use the return value of SeparateImage in ImageMagick 7.

---

rmagick.gemspec
spec/spec_helper.rb
test/test_all_basic.rb

with this we can toss a `binding.pry` into our ruby code when we're
testing for easier debugging.

add pry as a dev dependency

---

test/ImageList2.rb
test/lib/internal/Draw.rb

We've been seeing [warnings in our tests][1] about missing fonts. Rather
than expecting a specific font to be present across all systems, we can
select from one of the existing fonts on the system.
```
/home/circleci/repo/test/lib/internal/Draw.rb:267: warning: RMagick: unable to read font `Arial' @ warning/annotate.c/RenderType/90
```
[1]: https://circleci.com/gh/rmagick/rmagick/1415

fix font warnings in specs

---

ext/RMagick/rmimage.c
spec/rmagick/image/constitute_spec.rb

We can't check for negatives with `unsigned long`, but the numbers here
should really be `long` anyway, so this changes their type and removes a
cast later in the function.

Check for negative dimensions in Image#constitute

---

.gitignore

- I've had an ubuntu logfile showing up in my git, so ignore all `.log`
files
- `Makefile` and `extconf.h` are auto-generated based on the user's
environment, so ignoring those as well.

Add some additional files to .gitignore

---

rmagick.gemspec
test/Draw.rb
test/Enum.rb
test/Fill.rb
test/Image1.rb
test/Image2.rb
test/Image3.rb
test/ImageList1.rb
test/ImageList2.rb
test/Image_attributes.rb
test/Import_Export.rb
test/Info.rb
test/KernelInfo.rb
test/Magick.rb
test/Pixel.rb
test/PolaroidOptions.rb
test/Preview.rb
test/Struct.rb
test/appearance/Montage.rb
test/appearance/appearance_assertion.rb
test/lib/internal/Draw.rb
test/lib/internal/Geometry.rb
test/lib/internal/Magick.rb
test/test_all_basic.rb

This changes the existing unit test framework from `Test::Unit` to
`Minitest`. The primary reason for this is to ease the transition to
RSpec, since `Minitest` [has a spec syntax][1] not far off from that of
`RSpec`. This should allow for a faster swap in terms of test syntax,
and easier diffs as we can make simple, sweeping changes.
I added a few aliases here as Minitest has fewer assertions. Since these
will be switching to the RSpec `expect` syntax before long, I don't
think it's worth the effort to switch them at the call site now, and the
aliases help reduce the diff as well.
In subsequent commits, I plan to start adding new matcher aliases that
map to the `RSpec` syntax and changing the file structures to the
`Minitest` spec syntax. I have been refactoring the tests as I've …

switch from Test::Unit to Minitest

---

test/Draw.rb
test/Enum.rb
test/Fill.rb
test/Image1.rb
test/Image2.rb
test/Image3.rb
test/ImageList1.rb
test/ImageList2.rb
test/Image_attributes.rb
test/Info.rb
test/Magick.rb
test/Pixel.rb
test/Struct.rb
test/lib/internal/Draw.rb
test/lib/internal/Geometry.rb
test/lib/internal/Magick.rb
test/test_all_basic.rb
test/tmpnam_test.rb

This demonstrates the approach I want to take with converting tests to
RSpec. Rather than trying to convert tests file-by-file, we can sweep
through all of the tests and replace the matchers with the RSpec syntax.
Subsequent commits will continue to replace the existing `assert` style
matchers with `expect`. Once that is finished, we can swap in `minitest`
`spec` style, then move everything to the `spec/` folder, and finally
split the tests up and refactor them in place.

Replace `assert_equal` with RSpec style matcher

---

.rubocop.yml
test/Draw.rb
test/Enum.rb
test/Fill.rb
test/Image1.rb
test/Image2.rb
test/Image3.rb
test/ImageList1.rb
test/ImageList2.rb
test/Image_attributes.rb
test/Info.rb
test/KernelInfo.rb
test/Magick.rb
test/Pixel.rb
test/PolaroidOptions.rb
test/Preview.rb
test/lib/internal/Draw.rb
test/lib/internal/Geometry.rb
test/test_all_basic.rb
test/tmpnam_test.rb

https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/built-in-matchers/raise-error-matcher

Replace `assert_raise(s)` with RSpec style matcher

---

test/Draw.rb
test/Enum.rb
test/Fill.rb
test/Image1.rb
test/Image2.rb
test/Image3.rb
test/ImageList1.rb
test/ImageList2.rb
test/Image_attributes.rb
test/Info.rb
test/Magick.rb
test/Pixel.rb
test/PolaroidOptions.rb
test/Preview.rb
test/lib/internal/Draw.rb
test/test_all_basic.rb
test/tmpnam_test.rb

https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/built-in-matchers/raise-error-matcher#expect-no-error-at-all

Replace `assert_nothing_raised` with RSpec style matcher

---

test/Draw.rb
test/Enum.rb
test/Fill.rb
test/Image1.rb
test/Image2.rb
test/Image3.rb
test/ImageList1.rb
test/ImageList2.rb
test/Image_attributes.rb
test/KernelInfo.rb
test/Magick.rb
test/Preview.rb
test/Struct.rb
test/lib/internal/Magick.rb
test/test_all_basic.rb

https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/built-in-matchers/type-matchers#be-(an-)instance-of-matcher

Replace `assert_instance_of` with RSpec style matcher

---

test/Image1.rb
test/Image2.rb
test/Image3.rb
test/ImageList1.rb
test/test_all_basic.rb

https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/built-in-matchers/equality-matchers#compare-using-be-(equal?)

Replace `assert_same` with RSpec style matcher

---

.rubocop.yml
test/Image1.rb
test/Image2.rb
test/Image3.rb
test/ImageList1.rb
test/ImageList2.rb
test/KernelInfo.rb
test/test_all_basic.rb

I disabled the `Rails/RefuteMethods` rule as it wants us to use
`assert_not_same`.
https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/built-in-matchers/equality-matchers#compare-using-be-(equal?)

Replace `assert_not_same` with RSpec style matcher

---

test/Enum.rb
test/Image1.rb
test/Image2.rb
test/Image3.rb
test/ImageList1.rb
test/Image_attributes.rb
test/Info.rb
test/KernelInfo.rb
test/lib/internal/Geometry.rb

In this case I decided to use `to be(nil)` rather than `to be_nil`. Both
are available in RSpec, and they are essentially equivalent. The reason
I chose `be(nil)` was to be syntactically consistent with `be(true)` and
`be(false)`, since there is no longer a `be_true` in RSpec, only a
`be_truthy` which is less strict about the return value. In this latter
case I prefer to avoid `be_truthy` and be more explicit about what is
expected, either via `be(true)` or `eq(something_more_specific)`.
https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/built-in-matchers/equality-matchers#compare-using-be-(equal?)
https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/built-in-match …

Replace `assert_nil` with RSpec style matcher

---

test/Enum.rb
test/Image1.rb
test/Image2.rb
test/ImageList1.rb
test/ImageList2.rb
test/Image_attributes.rb
test/Info.rb
test/Magick.rb
test/Pixel.rb
test/lib/internal/Geometry.rb
test/test_all_basic.rb

https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/built-in-matchers/type-matchers#be-(a-)kind-of-matcher

Replace `assert_kind_of` with RSpec style matcher

---

test/Image_attributes.rb
test/Import_Export.rb
test/Pixel.rb
test/appearance/appearance_assertion.rb
test/test_all_basic.rb

I removed the test descriptions for now. I think these can be made a
little more clear once the RSpec transition is completed.
https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/built-in-matchers/be-within-matcher

Replace `assert_in_delta` with RSpec style matcher

---

test/Enum.rb
test/Image1.rb
test/Pixel.rb
test/Struct.rb
test/lib/internal/Magick.rb
test/test_all_basic.rb

https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/built-in-matchers/match-matcher

Replace `assert_match` with RSpec style matcher

---

test/Enum.rb
test/Image1.rb
test/ImageList1.rb
test/ImageList2.rb
test/Image_attributes.rb
test/Pixel.rb
test/test_all_basic.rb

https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/built-in-matchers/equality-matchers#compare-using-eq-(==)

Replace `assert_not_equal` with RSpec style matcher

---

test/Image1.rb
test/Image2.rb
test/Image3.rb
test/test_all_basic.rb

In this case I replaced `assert_block` calls with a handful of other
matchers, mostly `to be(true)` and `to be(false)`. I also added a
`respond_to` matcher. There is an `all` matcher, but I didn't want to
get down the rabbit hole of trying to implement that, so I left the
`all?` with a `be(true)` matcher as well.
https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/built-in-matchers/respond-to-matcher
https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/built-in-matchers/all-matcher

Replace `assert_block` with RSpec style matcher

---

test/Enum.rb
test/Image1.rb
test/Image2.rb
test/Image3.rb
test/ImageList1.rb
test/Image_attributes.rb
test/Info.rb
test/Magick.rb
test/Pixel.rb
test/lib/internal/Magick.rb
test/test_all_basic.rb

This changes `assert`, `assert_not_nil`, `assert_true`, and
`assert_false` assertions to use mostly `be(true)`, `be(false)` and
`be(nil)` checks, with the introduction of `have_key` and `include` checks
as well.
This should be the last step in switching the matchers to use RSpec syntax.
Next up is switching the test files to use `spec` syntax.
https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/built-in-matchers/predicate-matchers#should-have-key-(based-on-hash#has-key?) 
https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/built-in-matchers/include-matcher

Replace remaining assertions with RSpec style matcher

---

.rubocop.yml
test/Draw.rb
test/Enum.rb
test/Fill.rb
test/Image1.rb
test/Image2.rb
test/Image3.rb
test/ImageList1.rb
test/ImageList2.rb
test/Image_attributes.rb
test/Import_Export.rb
test/Info.rb
test/KernelInfo.rb
test/Magick.rb
test/Pixel.rb
test/PolaroidOptions.rb
test/Preview.rb
test/Struct.rb
test/appearance/Montage.rb
test/lib/internal/Draw.rb
test/lib/internal/Geometry.rb
test/lib/internal/Magick.rb
test/test_all_basic.rb
test/tmpnam_test.rb

This switches all of our test files to use the `minitest/spec` syntax,
which is more or less the same as RSpec. It's pretty brute force at this
point. I used `it 'works'` blocks everywhere rather than a better
description. I'll flesh them out more after they have been split up by
method. Most of the `test_` methods referenced method names, but a few
were more descriptive. I changed them all to the same format, however,
with the intention of cleaning all of that up again after they're all on
RSpec. There were also a handful of test methods that were not prefixed
with `test_` (see `find_all` and `flatten_images`), so this actually
enables a little more testing for those cases.
This commit is best viewed with the `-w` option to hide whitespace
changes.

RSpec: convert all tests to minitest spec

---

rmagick.gemspec

I think almost users do not refer test/document/example files in gem package and the users refer this repository directly if needed.
```
$ rake build
$ ls -lh pkg/rmagick*
-rw-r--r--  1 watson  staff   1.9M 11 28 01:36 pkg/rmagick-4.1.0.rc2.gem
```
```
$ rake build
$ ls -lh pkg/rmagick*
-rw-r--r--  1 watson  staff   230K 11 28 01:37 pkg/rmagick-4.1.0.rc2.gem
```

Reduce gem package size by removing test/document/example files

---

ext/RMagick/rmdraw.c
ext/RMagick/rmimage.c
ext/RMagick/rmpixel.c
lib/rmagick_internal.rb
spec/draw_spec.rb
spec/image_2_spec.rb
spec/image_list_2_spec.rb
spec/pixel_spec.rb

`Object#tainted?` has been marked as deprecated as Ruby 2.7 and it will always return `false`.
https://github.com/ruby/ruby/blob/1140625cd31f7ad74c42dc625b9dab389b12653c/object.c#L1169-L1173
So we should remove taint logic from RMagick.

Remove taint logic which will be deprecated in Ruby

---

ext/RMagick/rmimage.c
ext/RMagick/rmpixel.c
ext/RMagick/rmutil.c

This patch will eliminate following compiler warnings with Ruby 2.7
```
../../../../ext/RMagick/rmimage.c:11630:43: warning: passing argument 3 of ‘rb_rescue’ from incompatible pointer type [-Wincompatible-pointer-types]
1955         file = rb_rescue(rb_String, file, file_arg_rescue, file);
1956                                           ^~~~~~~~~~~~~~~
1957In file included from /home/travis/.rvm/rubies/ruby-2.7.0-preview3/include/ruby-2.7.0/ruby.h:33:0,
1958                 from ../../../../ext/RMagick/rmagick.h:25,
1959                 from ../../../../ext/RMagick/rmimage.c:13:
1960/home/travis/.rvm/rubies/ruby-2.7.0-preview3/include/ruby-2.7.0/ruby/ruby.h:1987:7: note: expected ‘VALUE (*)(VALUE,  VALUE) {aka long unsigned int (*)(long unsigned int,  long unsigned int)}’ but argument is …
```

Eliminate compiler warnings with Ruby 2.7

---

spec/rmagick/image/class_type_writer_spec.rb
spec/rmagick/image/element_assignment_spec.rb
spec/rmagick/image/element_reference_spec.rb
spec/rmagick/image/properties_spec.rb

This corrects the spec naming and splits out some specs into more
appropriately named files.
One of the somewhat awkward things about having one spec file per method
is the file naming for methods that have symbols like `[]` and `thing=`.
Having a filename like `[]_spec.rb` is a recipe for disaster, so we have
to come up with proper names for them. For setters in ruby it is
typically `thing_writer_spec.rb`. For the square braces operators I'm
using the naming [from the ruby docs][1], `element_reference_spec.rb`
and `element_assignment_spec.rb`.
[1]: https://ruby-doc.org/core-2.6.5/Hash.html#method-i-5B-5D

RSpec: tidy up some of the existing specs

---

ext/RMagick/rmimage.c

Support for ruby `taint` has been removed.

remove reference to taint from comment

---

ext/RMagick/rmpixel.c

This patch will eliminate following compiler warnings.
```
$ clang -v
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin19.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ ruby extconf.rb
checking for brew... yes
checking for clang... yes
checking for pkg-config... yes
checking for outdated ImageMagick version (<= 6.7.7)... no
Usage: file [bcCdEhikLlNnprsvzZ0] [-e test] [-f namefile] [-F separator] [-m magicfiles] [-M magicfiles] file...
file -C -m magicfiles
Try `file --help' for more information.
checking for __GNUC__... yes
checking for Ruby version >= 2.3.0... yes
checking for MagickCore/MagickCore.h... yes
checking for GetImageChannelEntropy() in …
```

Eliminate compiler warnings with clang for ImageMagick 7

---

spec/magick_spec.rb

macOS assigns `256` as maximum number of open files per process.
```c
#include <stdio.h>
#include <unistd.h>
int main()
{
printf("files = %ld\n", sysconf(_SC_OPEN_MAX));
return 0;
}
```
```
$ /usr/bin/sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.2
BuildVersion:	19C57
$ ./a.out
files = 256
```
ImageMagick calculates and assigns the limit from the upper limit specified by OS platform with following codes.
```c
(void) SetMagickResourceLimit(FileResource,MagickMax((size_t)
(3*files/4),64));
```
https://github.com/ImageMagick/ImageMagick6/blob/8b3bf460054d8769104139b28d863202e70eb26c/magick/resource.c#L1426-L1427
So, in macOS platform, `192` will be assinged as default limit value for `file` resource.
This patch relaxes expected value to fix following failure on macOS.
```
Failures:
1) …
```

Relax expected value in spec of Magick.limit_resource for macOS

---

before_install_linux.sh

This patch fix following error.
```
wget https://www.imagemagick.org/download/releases/ImageMagick-6.7.7-10.tar.xz
--2019-12-21 08:10:09--  https://www.imagemagick.org/download/releases/ImageMagick-6.7.7-10.tar.xz
Resolving www.imagemagick.org (www.imagemagick.org)... 198.72.81.86
Connecting to www.imagemagick.org (www.imagemagick.org)|198.72.81.86|:443... connected.
ERROR: no certificate subject alternative name matches
requested host name ‘www.imagemagick.org’.
To connect to www.imagemagick.org insecurely, use `--no-check-certificate'.
The command "/bin/bash before_install_$TRAVIS_OS_NAME.sh" failed and exited with 5 during .
```

CI: Fix certificate error

---

.travis.yml

Travis CI has following pre-installed Ruby on bionic platform.
```
Pre-installed Ruby versions
ruby-2.4.9
ruby-2.5.3
ruby-2.5.7
ruby-2.6.5
```
https://travis-ci.org/rmagick/rmagick/jobs/627579147#L160
If we can them, it will reduce setup time.

CI: Use pre-installed Ruby

---

.rubocop_todo.yml
spec/rmagick/image/_dump_spec.rb
spec/rmagick/image/_load_spec.rb
spec/rmagick/image/composite_affine_spec.rb
spec/rmagick/image/composite_bang_spec.rb
spec/rmagick/image/composite_channel_spec.rb
spec/rmagick/image/composite_mathematics_spec.rb
spec/rmagick/image/composite_tiled_spec.rb
spec/rmagick/image/compress_colormap_bang_spec.rb
spec/rmagick/image/contrast_spec.rb
spec/rmagick/image/contrast_stretch_channel_spec.rb
spec/rmagick/image/convolve_channel_spec.rb
spec/rmagick/image/convolve_spec.rb
spec/rmagick/image/copy_spec.rb
spec/rmagick/image/crop_bang_spec.rb
spec/rmagick/image/crop_spec.rb
spec/rmagick/image/cycle_colormap_spec.rb

This pulls the first batch of spec blocks from `image_2_spec.rb` into
files.
* `composite_spec.rb` already existed, so I left it as-is. It already
looks decent.
* I'm leaving `image_2_spec.rb` unchanged for the moment to make it
easier to manage parallel pull requests. I'll remove it at the end.

RSpec: convert "_*" and "c*" Image specs to files

---

.rubocop_todo.yml
spec/rmagick/image/decipher_spec.rb
spec/rmagick/image/define_spec.rb
spec/rmagick/image/deskew_spec.rb
spec/rmagick/image/despeckle_spec.rb
spec/rmagick/image/destroy_bang_spec.rb
spec/rmagick/image/destroy_spec.rb
spec/rmagick/image/difference_spec.rb
spec/rmagick/image/displace_spec.rb
spec/rmagick/image/distort_spec.rb
spec/rmagick/image/distortion_channel_spec.rb
spec/rmagick/image/dup_spec.rb
spec/rmagick/image/each_profile_spec.rb
spec/rmagick/image/edge_spec.rb
spec/rmagick/image/emboss_spec.rb
spec/rmagick/image/enhance_spec.rb
spec/rmagick/image/equalize_channel_spec.rb
spec/rmagick/image/equalize_spec.rb
spec/rmagick/image/erase_bang_spec.rb
spec/rmagick/image/excerpt_spec.rb
spec/rmagick/image/export_pixels_spec.rb
spec/rmagick/image/export_pixels_to_str_spec.rb
spec/rmagick/image/extent_spec.rb

This pulls the second batch of spec blocks from `image_2_spec.rb` into
files.
* `dissolve_spec.rb` already existed, so I left it as-is. It already
looks decent.
* I'm leaving `image_2_spec.rb` unchanged for the moment to make it
easier to manage parallel pull requests. I'll remove it at the end.

RSpec: convert "d*" and "e*" Image specs to files

---

.rubocop_todo.yml
spec/rmagick/image/find_similar_region_spec.rb
spec/rmagick/image/flip_bang_spec.rb
spec/rmagick/image/flip_spec.rb
spec/rmagick/image/flop_bang_spec.rb
spec/rmagick/image/flop_spec.rb
spec/rmagick/image/frame_spec.rb
spec/rmagick/image/function_channel_spec.rb
spec/rmagick/image/fx_spec.rb
spec/rmagick/image/gamma_channel_spec.rb
spec/rmagick/image/gamma_correct_spec.rb
spec/rmagick/image/gaussian_blur_channel_spec.rb
spec/rmagick/image/gaussian_blur_spec.rb
spec/rmagick/image/get_exif_by_entry_spec.rb
spec/rmagick/image/get_exif_by_number_spec.rb
spec/rmagick/image/get_pixels_spec.rb
spec/rmagick/image/gray_predicate_spec.rb
spec/rmagick/image/histogram_predicate_spec.rb
spec/rmagick/image/implode_spec.rb
spec/rmagick/image/import_pixels_spec.rb

This pulls the third batch of spec blocks from `image_2_spec.rb` into
files.
* I'm leaving `image_2_spec.rb` unchanged for the moment to make it
easier to manage parallel pull requests. I'll remove it at the end.

RSpec: convert "f*" through "i*" Image specs to files

---

.rubocop_todo.yml
spec/rmagick/image/level2_spec.rb
spec/rmagick/image/level_channel_spec.rb
spec/rmagick/image/level_colors_spec.rb
spec/rmagick/image/level_spec.rb
spec/rmagick/image/levelize_channel_spec.rb
spec/rmagick/image/liquid_rescale_spec.rb
spec/rmagick/image/magnify_spec.rb
spec/rmagick/image/marshal_spec.rb
spec/rmagick/image/mask_spec.rb
spec/rmagick/image/matte_fill_to_border_spec.rb
spec/rmagick/image/matte_floodfill_spec.rb
spec/rmagick/image/matte_replace_spec.rb
spec/rmagick/image/matte_reset_bang_spec.rb
spec/rmagick/image/median_filter_spec.rb
spec/rmagick/image/minify_spec.rb
spec/rmagick/image/modulate_spec.rb
spec/rmagick/image/monochrome_predicate_spec.rb
spec/rmagick/image/morphology_channel_spec.rb
spec/rmagick/image/morphology_spec.rb
spec/rmagick/image/motion_blur_spec.rb

This pulls the fourth batch of spec blocks from `image_2_spec.rb` into
files.
* The original specs for `liquid_rescale` were commented out. I
uncommented them, but they errored out with a complaint about a
delegate library. I added a `skip` for now.
* I'm leaving `image_2_spec.rb` unchanged for the moment to make it
easier to manage parallel pull requests. I'll remove it at the end.

RSpec: convert "l*" and "m*" Image specs to files

---

spec/rmagick/image/profile_bang_spec.rb
spec/rmagick/image/quantize_spec.rb
spec/rmagick/image/quantum_operator_spec.rb
spec/rmagick/image/radial_blur_channel_spec.rb
spec/rmagick/image/radial_blur_spec.rb
spec/rmagick/image/raise_spec.rb
spec/rmagick/image/random_threshold_channel_spec.rb
spec/rmagick/image/recolor_spec.rb
spec/rmagick/image/reduce_noise_spec.rb
spec/rmagick/image/remap_spec.rb
spec/rmagick/image/resample_bang_spec.rb
spec/rmagick/image/resample_spec.rb
spec/rmagick/image/resize_bang_spec.rb
spec/rmagick/image/resize_spec.rb
spec/rmagick/image/resize_to_fill_spec.rb
spec/rmagick/image/resize_to_fit_bang_spec.rb
spec/rmagick/image/resize_to_fit_spec.rb
spec/rmagick/image/roll_spec.rb
spec/rmagick/image/rotate_bang_spec.rb
spec/rmagick/image/rotate_spec.rb

This pulls spec blocks for methods starting with p-r from
`image_3_spec.rb` into files.

RSpec: convert "p*" through "r*" Image specs to files

---

spec/rmagick/image/sample_bang_spec.rb
spec/rmagick/image/sample_spec.rb
spec/rmagick/image/scale_bang_spec.rb
spec/rmagick/image/scale_spec.rb
spec/rmagick/image/segment_spec.rb
spec/rmagick/image/selective_blur_channel_spec.rb
spec/rmagick/image/separate_spec.rb
spec/rmagick/image/sepiatone_spec.rb
spec/rmagick/image/set_channel_depth_spec.rb
spec/rmagick/image/shade_spec.rb
spec/rmagick/image/shadow_spec.rb
spec/rmagick/image/sharpen_channel_spec.rb
spec/rmagick/image/sharpen_spec.rb
spec/rmagick/image/shave_bang_spec.rb
spec/rmagick/image/shave_spec.rb
spec/rmagick/image/shear_spec.rb
spec/rmagick/image/sigmoidal_contrast_channel_spec.rb
spec/rmagick/image/signature_spec.rb
spec/rmagick/image/sketch_spec.rb
spec/rmagick/image/solarize_spec.rb
spec/rmagick/image/sparse_color_spec.rb
spec/rmagick/image/splice_spec.rb
spec/rmagick/image/spread_spec.rb
spec/rmagick/image/stegano_spec.rb
spec/rmagick/image/stereo_spec.rb
spec/rmagick/image/store_pixels_spec.rb
spec/rmagick/image/strip_bang_spec.rb
spec/rmagick/image/swirl_spec.rb

This pulls spec blocks for methods starting with s from
`image_3_spec.rb` into files.

RSpec: convert "s*" Image specs to files

---

ext/RMagick/rmimage.c

Forgot to handle opacity value in https://github.com/rmagick/rmagick/pull/871

Retrieve opacity value properly in Image#get_pixels

---

ext/RMagick/extconf.rb
ext/RMagick/rmmain.c

This PR is yet another implementation that solves the same problem as #832.
#832 requires adding new API in Ruby, and it might not be merged.
So, this implements custom allocation handler using `rb_gc_adjust_memory_usage()` Ruby's API.
The API notify memory usage in RMagick/ImageMagick to Ruby GC and GC works properly. 
`rb_gc_adjust_memory_usage()` can be used since Ruby 2.4.
So this PR will support many platform than #832.

Add aligned malloc/free handler for Ruby 2.4+ 

---

ext/RMagick/rmpixel.c

This patch will eliminate compiler warnings on ImageMagick 6 which is same with #864

Eliminate compiler warnings with clang for ImageMagick 6

---

ext/RMagick/rmilist.c

This patch will eliminate compiler warnings for unused function.
```
$ CFLAGS='-Wall' ruby extconf.rb
$ make
compiling rmagick.c
compiling rmdraw.c
compiling rmenum.c
compiling rmfill.c
compiling rmilist.c
rmilist.c:827:1: warning: unused function 'imagelist_scene_eq' [-Wunused-function]
imagelist_scene_eq(VALUE imagelist, VALUE scene)
^
1 warning generated.
compiling rmimage.c
rmimage.c:16401:21: warning: enumeration value 'StaticGravity' not handled in switch [-Wswitch]
switch (gravity)
^
rmimage.c:16401:21: note: add missing switch cases
switch (gravity)
^
1 warning generated.
compiling rminfo.c
compiling rmkinfo.c
compiling rmmain.c
compiling rmmontage.c
compiling rmpixel.c
compiling rmstruct.c
compiling rmutil.c
linking shared-object RMagick2.bundle
```

Remove unused function

---

ext/RMagick/rmimage.c

The AddressSanitizer indicates heap-buffer-overflow at https://github.com/rmagick/rmagick/blob/655f48ff2fdc980be63bf656f2f5bef393c8d182/ext/RMagick/rmimage.c#L16057
```
$ CFLAGS='-O0 -g -fsanitize=address -fno-omit-frame-pointer' rake
...
==52655==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61d00082bc00 at pc 0x00011ae6566d bp 0x7ffee11df090 sp 0x7ffee11df088
READ of size 4 at 0x61d00082bc00 thread T0
#0 0x11ae6566c in Image_wet_floor rmimage.c:16057
#1 0x10f25bdf9 in call_cfunc_m1 vm_insnhelper.c:2336
#2 0x10f23aaa9 in vm_call_cfunc_with_frame vm_insnhelper.c:2514
#3 0x10f21bf8b in vm_call_cfunc vm_insnhelper.c:2539
#4 0x10f219e74 in vm_call_method_each_type vm_insnhelper.c:2925
#5 0x10f219649 in vm_call_method vm_insnhelper.c:3028
#6 0x10f1bf95c in vm_call_general …
```

Fix heap-buffer-overflow in Image#wet_floor with ImageMagick 7

---

.simplecov
spec/spec_helper.rb

Fix #889
Now, `simplecov` displays `888 / 1011 LOC (87.83%) covered.` as proper measured value.
```
$ COVERAGE=true rake
install -c tmp/x86_64-darwin19/RMagick2/2.6.5/RMagick2.bundle lib/RMagick2.bundle
cp tmp/x86_64-darwin19/RMagick2/2.6.5/RMagick2.bundle tmp/x86_64-darwin19/stage/lib/RMagick2.bundle
/Users/watson/.rbenv/versions/2.6.5/bin/ruby -I/Users/watson/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-support-3.9.2/lib:/Users/watson/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/lib /Users/watson/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-core-3.9.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
[COVERAGE] Running with SimpleCov HTML Formatter
Randomized with seed 22005
........................................................................... …
```

Ensure starting simplecov before loading RMagick library in rspec

---

ext/RMagick/rmimage.c

Fix #897
In ImageMagick 6, `PolaroidImage()` retrives caption value in inside.
```c
value=GetImageProperty(image,"Caption");
```
https://github.com/ImageMagick/ImageMagick6/blob/4dc6b70d5d24653468d474ab2d1c184f05edcfab/magick/fx.c#L4226

Pass caption value into ImageMagick 7 API in Image#polaroid

---

doc/ex/transparent.rb

This patch should fix following error in example of transparent.rb.
```
$ ruby transparent.rb
Traceback (most recent call last):
transparent.rb:27:in `<main>': uninitialized constant Magick::TransparentOpacity (NameError)
Did you mean?  Magick::TransparentColorspace
```

Example: Fix “uninitialized constant Magick::TransparentOpacity” error

---

ext/RMagick/rmilist.c

Revert removed RemapImages() calling in ImageList#remap for ImageMagick 6

---

ext/RMagick/extconf.rb

When run `ruby extconf.rb` on macOS,  it did not specify an appropriate file with `file` command.
it just shown the help message.
```
Usage: file [bcCdEhikLlNnprsvzZ0] [-e test] [-f namefile] [-F separator] [-m magicfiles] [-M magicfiles] file...
file -C -m magicfiles
Try `file --help' for more information.
```

Detect the proper ARCHFLAGS on macOS

---

ext/RMagick/rmmain.c

This patch will eliminate following warning message.
```
../../../../ext/RMagick/rmmain.c:128:12: warning: implicit declaration of function '_aligned_msize'; did you mean '_aligned_free'? [-Wimplicit-function-declaration]
128 |     return _aligned_msize(ptr, CACHE_LINE_SIZE, 0);
|            ^~~~~~~~~~~~~~
|            _aligned_free
```

Eliminate compiler warnings on Windows

---

ext/RMagick/rmimage.c

To remove condition, this checks the argument whether it is valid within a switch statement in advance

Remove unnecessary condition in acquiring image data

---

.rubocop.yml
.rubocop_todo.yml
spec/rmagick/image/read_spec.rb

This rule requires that we use `be(true)` instead of `be_truthy`.
`be_truthy` allows *any* truthy value, such as `0`, `[]` or `fie`, as
opposed to `be(true)`, which ensures that the value is, in fact, `true`.
https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecpredicatematcher

Rubocop: enable RSpec/PredicateMatcher

---

.rubocop_todo.yml
doc/ex/writing_mode01.rb
doc/ex/writing_mode02.rb
lib/rmagick_internal.rb

This makes us wrap our hashes like so.
https://rubocop.readthedocs.io/en/stable/cops_layout/#layoutfirsthashelementlinebreak

Rubocop: enable Layout/FirstHashElementLineBreak

---

ext/RMagick/extconf.rb
ext/RMagick/rmmain.c

posix_memalign() is enough for allocating aligned memory and it might cause an error in free() on some platform

Remove memalign()

---

.rubocop_todo.yml
spec/rmagick/image_list/from_blob_spec.rb

I left the exclude for `RVG#to_c` because the method isn't currently
under test and I want to make sure I don't break existing logic.

Rubocop: enable AutoResourceCleanup rule in specs

---

spec/rmagick/draw/image_spec.rb

The unit test fails with recent versions of ImageMagick because `BlurCompositeOp` needs `compose:args` to work. This did not fail with earlier version of ImageMagick because we recently improved the error reporting. This PR will change the unit test to skip `BlurCompositeOp`.

Skip BlurCompositeOp in unit test.

---

.rubocop.yml
.rubocop_todo.yml

The `AlignLeftLetBrace` and `AlignRightLetBrace` rules require that when
there are multiple `let` blocks that they align their braces like so:
```rb
let(:one_thing)     { make_a_thing       }
let(:another_thing) { make_another_thing }
```
This looks more tidy, but it can cause diff churn when we add or remove
a line:
```diff
- let(:one_thing)     { make_a_thing       }
- let(:another_thing) { make_another_thing }
+ let(:one_thing)            { make_a_thing              }
+ let(:another_thing)        { make_another_thing        }
+ let(:another_longer_thing) { make_another_longer_thing }
```
For the sake of having a clean history, it's probably better not
to align things.

RSpec: disable LetBrace rubocop rules

---

ext/RMagick/rmilist.c

`images_from_imagelist()` creates a list to pass ImageMagick API.
When handles Images which appended using `ImageList#<<`, the images will be cloned in some cases.
https://github.com/rmagick/rmagick/blob/ad63bf86df475853a73158369d27be161ee6977f/ext/RMagick/rmilist.c#L804
The list created by `AppendImageToList()` will be finalized in `rm_split()`.
However, cloned images will not be destroyed.
This patch will wrap cloned images with Ruby object.
Then, the wraped images will be destroyed using Ruby's GC if they were wasted.
* Before
```
$ ruby leak.rb
Process: 9392: RSS = 2998 MB
```
* After
```
$ ruby leak.rb
Process: 10240: RSS = 537 MB
```
* Test code
```ruby
1000.times do
img = Magick::Image.new(500, 500)
list << img
list << img …
```

Fix memory leak in images_from_imagelist()

---

.rubocop_todo.yml
spec/rmagick/image_list_spec.rb

This rule requires us to use the `described_class` test helper rather
than explicitly naming the class being tested. The benefit of using
`described_class`, aside from being a little shorter in many cases, is
that it helps prevent false positives when we copy and paste tests if we
forget to change the class name under test.

RSpec: enable DescribedClass rubocop rule

---

.rubocop_todo.yml
spec/rmagick/image/destroy_bang_spec.rb

The `ExpectActual` rule doesn't like a constant being passed into
`expect` while a variable is passed into the test predicate. It wants
the unknown value to be passed to `expect`. It's a bit awkward in this
situation since there's no `be_included_in` matcher. However, I used
this as an excuse to refactor the test for clarity, so the violation is
gone now.

Rubocop: enable ExpectActual rubocop rule

---

.rubocop_todo.yml
spec/rmagick/image/export_pixels_spec.rb

`IteratedExpectation` wants us to use `all(some_matcher)` rather than
looping through and matching against each element. Also:
- Removed the outer `not_to raise_error`, as it is implied. The test
will fail if it raises an error. Also, when one of the expectations
fails it raises an error, so the `raise_error` matcher makes the
message more confusing when an internal test fails.
- Enabled the `MultipleDescribes` and `HooksBeforeExamples` rubocop
rules. These are both passing now after the transition to individual
spec files.

Rubocop: enable IteratedExpectation rubocop rule

---

ext/RMagick/rmimage.c

Get rid of warning in comparison between signed and unsigned value

---

.github/workflows/ci.yml

I'd like to make the builds required, but it's kind of tricky if the
patch version changes, since each version check is a separate build
requirement. Removing the patch version for Ruby at least makes that a
little less painful. It'll still be a problem with ImageMagick patch
versions, but I'll continue to think on it.

CI: don't specify ruby patch version

---

spec/spec_helper.rb

Because when run spec on CI, `rake` generate Makefile twice.
```
$ rake
mkdir -p tmp/x86_64-darwin19/RMagick2/2.3.8
cd tmp/x86_64-darwin19/RMagick2/2.3.8
/Users/watson/.rbenv/versions/2.3.8/bin/ruby -I. ../../../../ext/RMagick/extconf.rb
checking for brew... yes
checking for clang... yes
checking for pkg-config... yes
checking for outdated ImageMagick version (<= 6.7.7)... no
checking for __GNUC__... yes
checking for Ruby version >= 2.3.0... yes
checking for MagickCore/MagickCore.h... no
checking for magick/MagickCore.h... yes
checking for rb_gc_adjust_memory_usage() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... no
checking for GetImageChannelEntropy() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
checking …
```

Remove unnecessary `extconf.rb’ require

---

.rubocop.yml
spec/rmagick/image/charcoal_spec.rb

Increased min digits on Rubocop rule so that it won't complain about pixel values.

Add test for Image#charcoal with zero arguments

---

ext/RMagick/rmdraw.c
ext/RMagick/rmimage.c
ext/RMagick/rminfo.c
ext/RMagick/rmstruct.c

If the wrong format specifier is used, the correct value may not be output and cause a problem.

Replace to correct format specifiers for size_t/ssize_t value

---

ext/RMagick/rmimage.c

Get rid of warning “enumeration value ‘StaticGravity’ not handled in switch”

---

ext/RMagick/extconf.rb

MinGW platform uses special printf() and it does not recognize `z` format specifier.
Refer https://sourceforge.net/p/mingw-w64/wiki2/gnu%20printf/

Add __USE_MINGW_ANSI_STDIO definition to avoid `warning: unknown conversion type character 'z' in format’

---

ext/RMagick/extconf.rb
ext/RMagick/rmagick.h
ext/RMagick/rmdraw.c
ext/RMagick/rmimage.c
ext/RMagick/rminfo.c
ext/RMagick/rmstruct.c
ext/RMagick/rmutil.c

Seems Ruby's printf() format specifiers are wrong for old MinGW platform.
This PR uses  proper format specifiers for MinGW.

Use proper format specifiers within MinGW

---

.github/workflows/ci.yml

I think this is all we need. Because I'm pushing to branches on the main
repo, on my branches I see almost 70 checks. 33 for `push` and 33 for
`pull_request`. This will remove the duplicate `push` checks.

CI: run builds only on pull request

---

ext/RMagick/rmimage.c

Fix warning of “warning: explicitly assigning value of variable of type 'int' to itself”

---

ext/RMagick/rmdraw.c

These variables are only used inside of a particular block, so this
moves them to be declared in the block where they are used.

CPPCheck: reduce scope of variables in rmdraw.c

---

.github/workflows/ci.yml

This changes the `matrix` options for `imagemagick-version` to be
structured as an object. The goal of using this approach is that the job
name can be consistent when we increase the patch or build numbers. This
will allow us to make the build steps required without needing to update
the required steps every time we update them.

CI: use object syntax in matrix 

---

spec/rmagick/draw/draw_spec.rb
spec/rmagick/draw/marshal_dump_spec.rb
spec/rmagick/image/colors_spec.rb
spec/rmagick/image/colorspace_spec.rb
spec/rmagick/image/mask_spec.rb
spec/rmagick/image/mean_error_per_pixel_spec.rb
spec/rmagick/image/mime_type_spec.rb
spec/rmagick/image/scene_spec.rb
spec/rmagick/image_list/coalesce_spec.rb
spec/rmagick/image_list/fill_spec.rb
spec/rmagick/image_list/last_spec.rb
spec/rmagick/image_list/montage_spec.rb
spec/rmagick/image_list/push_spec.rb
spec/rmagick/image_list/reject_spec.rb
spec/rmagick/image_list/reverse_bang_spec.rb
spec/rmagick/image_list/reverse_spec.rb
spec/rmagick/image_list/uniq_bang_spec.rb
spec/rmagick/image_list/uniq_spec.rb
spec/rmagick/image_list/values_at_spec.rb
spec/rmagick/pixel/clone_spec.rb
spec/rmagick/pixel/dup_spec.rb
spec/rmagick/pixel/eql_predicate_spec.rb
spec/rmagick/pixel/spaceship_spec.rb

This adds a number in situations where we assign a new variable based on
an instance variable with the same name. So something like:
```rb
list = @list.clone
```
changes to:
```rb
list2 = @list.clone
```
The reason for this, aside from greater clarity, is that I want to
remove the instance variables. Instead, we will instantiate them locally
in the test, or use `let` blocks where appropriate.

RSpec: number repeated test variables

---

.rubocop.yml
.rubocop_todo.yml

This rule dictates how we should align assignment across multiple lines.
The default wants us to indent the block on the next line, like so:
```rb
foo =
if expression
'bar'
end
```
There is a configuration for `same_line` which would instead expect us
to format our code like so:
```rb
foo = if expression
'bar'
end
```
I kind of prefer the first option, but all of our code is in line with
the second option, `same_line`, so I went with that instead. You can see
the impact to our codebase if we were to use the first option in
#971.
rubocop.readthedocs.io/en/stable/cops_layout/#layoutmultilineassignmentlayout

 Rubocop: move multi-line assignment to next line

---

.github/workflows/ci.yml

Recently, `C:\Strawberry\c\bin/gmake.exe` has been used in Windows platform.
It is one of Perl platform in Windows (http://strawberryperl.com) and its make command (`gmake`) will fail to compile Ruby extension.
To ensure using `make` command in msys/MinGW, this PR set `MAKE` environment variable.
(Refer https://github.com/rmagick/rmagick/pull/1020)

CI: Set `MAKE` environment variable to avoid build error

---

ext/RMagick/rmimage.c

This patch fix memory leak which introduced in https://github.com/rmagick/rmagick/pull/1023
The intermediate image should be destroyed.

Fix memory leak in Image#resample and fix initial blur value

---

ext/RMagick/rminfo.c
ext/RMagick/rmpixel.c

I thought there were a bunch more of these, but these are the only ones
that are showing up on Codacy right now.

CPPCheck: reduce scope of remaining variables

---

.github/workflows/ci.yml

`bundler` will be installed at https://github.com/rmagick/rmagick/blob/e48d78ab81f6d3fab502a8c24ca9edb65921c87c/before_install_linux.sh#L5

CI: Remove unnecessary "gem install bundler"

---

ext/RMagick/rmilist.c

Fix warning of unused variable

---

doc/ex/colors.rb

This patch will fix following error in example.
```sh
$ ruby colors.rb
Creating colors.miff. This may take a few seconds...
Creating color swatches...
colors.rb:23:in `block in <main>': undefined method `opacity' for #<Magick::Pixel:0x00007fe243940cf0> (NoMethodError)
from colors.rb:16:in `colors'
from colors.rb:16:in `<main>’
```

Example: Fix “undefined method `opacity’”

---

.github/workflows/ci.yml

The default timeout on Github Actions is 360 minutes (6 hours). This
shortens it to 10 minutes so that we don't have to wait forever for
things to fail when they stall.

CI: add timeout-minutes setting

---

.rubocop.yml
.rubocop_todo.yml

It's passing now. There was some weird stuff with it for a bit.

Rubocop: re-enable RSpec/FilePath

---

.rubocop_todo.yml
doc/ex/arcs01.rb

This rule requires that the closing paren is after the opening heredoc
tag.
https://rubocop.readthedocs.io/en/stable/cops_layout/#layoutheredocargumentclosingparenthesis

Rubocop: enable HeredocArgumentClosingParenthesis

---

spec/rmagick/draw/class_methods/_dummy_img__spec.rb
spec/rmagick/draw/fill_pattern_writer_spec.rb
spec/rmagick/draw/interline_spacing_spec.rb
spec/rmagick/draw/interline_spacing_writer_spec.rb
spec/rmagick/draw/interword_spacing_spec.rb
spec/rmagick/draw/interword_spacing_writer_spec.rb
spec/rmagick/draw/kerning_spec.rb
spec/rmagick/draw/kerning_writer_spec.rb
spec/rmagick/draw/marshal_dump_spec.rb
spec/rmagick/draw/stroke_pattern_writer_spec.rb
spec/rmagick/image/blue_shift_spec.rb
spec/rmagick/image/channel_entropy_spec.rb
spec/rmagick/image/composite_spec.rb
spec/rmagick/image/constitute_spec.rb
spec/rmagick/image/dispatch_spec.rb
spec/rmagick/image/dissolve_spec.rb
spec/rmagick/image/element_assignment_spec.rb
spec/rmagick/image/element_reference_spec.rb
spec/rmagick/image/from_blob_spec.rb
spec/rmagick/image/properties_spec.rb

I've been moving in the  direction of avoiding `let` blocks as they
create indirection in the tests that can make it hard to fully
understand what the test is testing. Instead, I will err on the side of
a little more duplication in the tests. In cases where there is a lot of
setup logic to use over and over, I will often pull it out into helper
methods either in the specific test file, or in a higher level file for
use across multiple specs. More detailed argument against `let` blocks
in [this thoughtbot article][1].
[1]: https://thoughtbot.com/blog/lets-not

RSpec: eliminate `let` blocks

---

.rubocop_todo.yml
Rakefile
examples/describe.rb
examples/histogram.rb
examples/image_opacity.rb
examples/import_export.rb
examples/pattern_fill.rb
examples/rotating_text.rb
examples/spinner.rb
examples/thumbnail.rb
ext/RMagick/extconf.rb
lib/rvg/to_c.rb

This rule requires that we use the "squiggly" heredoc (`<<~`), which
allows us to indent the heredoc. It will trim left spacing in the
heredoc.
https://infinum.com/the-capsized-eight/multiline-strings-ruby-2-3-0-the-squiggly-heredoc
https://rubocop.readthedocs.io/en/stable/cops_layout/#layoutheredocindentation

Rubocop: enable IndentHeredoc

---

spec/magick_spec.rb
spec/rmagick/class_methods/colors_spec.rb
spec/rmagick/class_methods/fonts_spec.rb
spec/rmagick/image/auto_gamma_channel_spec.rb
spec/rmagick/image/auto_level_channel_spec.rb
spec/rmagick/image/clut_channel_spec.rb
spec/rmagick/image/composite_mathematics_spec.rb
spec/rmagick/image/composite_tiled_spec.rb
spec/rmagick/image/excerpt_spec.rb
spec/rmagick/image/level_colors_spec.rb
spec/rmagick/image/levelize_channel_spec.rb
spec/rmagick/image/liquid_rescale_spec.rb
spec/rmagick/image/mask_spec.rb
spec/rmagick/image/opaque_channel_spec.rb
spec/rmagick/image/paint_transparent_spec.rb
spec/rmagick/image/radial_blur_channel_spec.rb
spec/rmagick/image/resize_to_fit_spec.rb
spec/rmagick/image/selective_blur_channel_spec.rb
spec/rmagick/image/to_blob_spec.rb

`not_to raise_error` is implied, as tests will fail if it raises an
error. So unless we're specifically testing that it doesn't raise an
error, we don't need to do it all over the place.
that a particular action doesn't raise an error, it's not necessary.

RSpec: don't check for errors when assigning res

---

.rubocop_todo.yml
lib/rvg/misc.rb

This rule requires that each key-value pair in a multi-line hash is on a
separate line.
https://rubocop.readthedocs.io/en/stable/cops_layout/#layoutmultilinehashkeylinebreaks

Rubocop: enable MultilineHashKeyLineBreaks

---

rmagick.gemspec

We don't have a `bin/` directory nor any executables.

Gem: remove `executables` config

---

.rubocop_todo.yml
lib/rmagick_internal.rb

This rule disallows returning a value in a context where the return
value will be ignored. In the case of setter methods, Ruby always
returns what was passed into the method, ignoring any return values.
https://rubocop.readthedocs.io/en/stable/cops_lint/#lintreturninvoidcontext

Rubocop: enable ReturnInVoidContext

---

.rubocop_todo.yml
lib/rmagick_internal.rb
lib/rvg/embellishable.rb

This rule disallows implicit returns in methods that ignore return
values. In particular, `initialize` returns `self` implicitly and
ignores any return value, and setter methods implicitly return the
passed in value.
https://rubocop.readthedocs.io/en/stable/cops_lint/#lintvoid

Rubocop: enable Lint/Void

---

lib/rmagick_internal.rb

This is a protected method. The Rubocop rule `Naming/PredicateName`
prefers that we don't use `is_` prefixes in the method name. In this
case it's not used as a boolean check, as we never use the return
result. I also removed the `true` value being returned.
https://rubocop.readthedocs.io/en/stable/cops_naming/#namingpredicatename

Rubocop: rename is_an_image -> assert_image

---

.rubocop_todo.yml
ext/RMagick/extconf.rb

The `Naming/PredicateName` rubocop rule doesn't like methods named with
`have_`. Conveniently, the last usage of these methods was removed in
6c997e5 (PR #434), so we can remove these methods as well.
https://rubocop.readthedocs.io/en/stable/cops_naming/#namingpredicatename

Rubocop: remove unused `have_enum_` methods

---

.rubocop_todo.yml
spec/rmagick/image/dissolve_spec.rb

https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecemptylineafterexample

Rubocop: enable RSpec/EmptyLineAfterExample

---

spec/rmagick/image_list/mosaic_spec.rb

The copy here doesn't appear to serve any purpose.

RSpec: remove unecessary copy

---

ext/RMagick/rmagick.h
ext/RMagick/rmmain.c

yard parses C language files with ruby and it unable to expand the macro.
If `rb_define_method` is found, it is determined that the method is defined.

Yardoc: Use rb_define_method() directly instead of macro to define method

---

ext/RMagick/rmagick.h
ext/RMagick/rmimage.c
ext/RMagick/rminfo.c
ext/RMagick/rmpixel.c

yardoc parser written by ruby and it cannot recognize/expand C macro.
To describe Yardoc document, it need to expose symbol without C macro.
Similar with https://github.com/rmagick/rmagick/pull/1092
Close https://github.com/rmagick/rmagick/issues/784

Yardoc: Describe attributes symbol directly instead of C macro against to yardoc parser

---

ext/RMagick/rmpixel.c

Same with https://github.com/rmagick/rmagick/pull/1102

Yardoc: Describe attributes symbol directly in rmpixel.c instead of C macro against to yardoc parser

---

ext/RMagick/rmdraw.c

Yardoc: Fix unexpected syntax in @return tag

---

ext/RMagick/rminfo.c

Same with https://github.com/rmagick/rmagick/pull/1102

Yardoc: Describe attributes symbol directly in rminfo.c instead of C macro against to yardoc parser

---

.rubocop.yml
.rubocop_todo.yml
doc/ex/colors.rb
doc/ex/implode.rb
lib/rmagick_internal.rb
lib/rvg/pathdata.rb

The default of this rule is to require using `format`. However, we have
a method `Image#format` which can conflict with this, so I chose
`sprintf` instead.
https://rubocop.readthedocs.io/en/stable/cops_style/#styleformatstring

Rubocop: enable Style/FormatString

---

ext/RMagick/rmkinfo.c

Revert wrong removing of declaration in https://github.com/rmagick/rmagick/pull/1109

Revert removed UnityAddKernelInfo declaration

---

ext/RMagick/rmimage.c

This method has following Ruby usage.
Obviously 0 arguments are assumed.
```
* Ruby usage:
*   - @verbatim Image#export_pixels @endverbatim
*   - @verbatim Image#export_pixels(x) @endverbatim
*   - @verbatim Image#export_pixels(x, y) @endverbatim
*   - @verbatim Image#export_pixels(x, y, cols) @endverbatim
*   - @verbatim Image#export_pixels(x, y, cols, rows) @endverbatim
*   - @verbatim Image#export_pixels(x, y, cols, rows, map) @endverbatim
```

Fix exception message because #export_pixels accept 0 argument

---

ext/RMagick/rmimage.c
spec/rmagick/image_list/new_image_spec.rb

Because It is determined to be true even if nil was given as an argument.
In Ruby, nil and false should have same behavior in condition

Fix default value of `fill` argument in Image#initialize

---

ext/RMagick/rmdraw.c
ext/RMagick/rmimage.c
ext/RMagick/rminfo.c
ext/RMagick/rmmontage.c
ext/RMagick/rmpixel.c

Because yard show the warning message with @!attribute in C lang.

Yardoc: Remove unnecessary attributes annotation

---

ext/RMagick/rmmain.c
lib/rmagick_internal.rb

Because yard doesn't recognize it correctly.

Yardoc: Mix Observable module into Pixel class on Ruby land

---

before_install_linux.sh
before_install_osx.sh

- All tar ball files of recently release are on ImageMagick site
- ImageMagick team forget tagging and then we fail to get from Github

CI: Download ImageMagick tar ball from official site only

---

lib/rmagick_internal.rb

Close https://github.com/rmagick/rmagick/pull/1148
#collect is overridden but #map is not. it is confusing.

Add ImageList#map

---

ext/RMagick/rmimage.c

StringValuePtr() performs implicit string conversion internally.
In here, it is unnecessary.

Use RSTRING_PTR() to retrieve a pointer of String object for buffer

---

ext/RMagick/rmagick.h

Because RSTRING_PTR() just return raw pointer in String object which might not have null-terminate in string.
It might cause a crash in magick_clone_string()

Use StringValueCStr() to get null-terminated C-lang string

---

ext/RMagick/rmagick.h
ext/RMagick/rmimage.c
ext/RMagick/rminfo.c
ext/RMagick/rmmain.c
ext/RMagick/rmmontage.c
ext/RMagick/rmutil.c

Because the same behavior function is implemented in Ruby core

Use rb_String() instead which converts object using #to_s method

---

ext/RMagick/rmimage.c
spec/rmagick/image/convolve_channel_spec.rb
spec/rmagick/image/store_pixels_spec.rb

If non array object was given, rm_check_ary_len() will cause a SEGV.
So, this patch will convert object to Array implicitly.

Fix SEGV in rm_check_ary_len() with unexpected argument value

---

ext/RMagick/rmimage.c
spec/rmagick/image/marshal_load_spec.rb

If non String object was given, RSTRING_PTR() will cause a SEGV.
So, this patch will convert object to String implicitly.

Fix SEGV in Image#marshal_load

---

spec/rmagick/image/charcoal_spec.rb
spec/spec_helper.rb
spec/support/matchers.rb
spec/support/matchers/match_pixels_matcher.rb

This introduces a new `match_pixels` test matcher that accepts a delta argument.
These tests produce varying results on different operating systems and versions of ImageMagick, so we set the delta to 1..
We're filtering out ImageMagick 6.7 because it produces a black and white image.

Flesh out tests for Image#charcoal

---

.github/workflows/ci.yml

Because `eregon/use-ruby-action` fails
https://github.com/rmagick/rmagick/pull/1182/checks?check_run_id=533577828

CI: Use setup-ruby instead

---

.github/workflows/ci.yml

Some changes have been made to Windows
and wget is no longer available by default.

CI: Install wget on windows lane

---

.github/workflows/ci.yml

Error about cached directory. I don't know what caused it….
https://github.com/rmagick/rmagick/pull/1194/checks?check_run_id=561661438

CI: Remove caching Ruby dependencies

---

ext/RMagick/rmimage.c

Related to https://github.com/rmagick/rmagick/issues/483
```
$ rake
......
Failures:
1) Magick::Image#read issue #483 can read PDF file
Failure/Error: expect { described_class.read(File.join(FIXTURE_PATH, 'sample.pdf')) }.not_to raise_error
expected no Exception, got #<Magick::ImageMagickError: FailedToExecuteCommand `'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dN...6N_yZ6expfC7' '-f/tmp/magick-62170WQ3NHSoRCQb'' (-1) @ error/delegate.c/ExternalDelegateCommand/478> with backtrace:
Finished in 24.13 seconds (files took 0.6694 seconds to load)
649 examples, 1 failure, 4 pending
$ uname -a
FreeBSD watson-ghostbsd-pc 12.1-STABLE FreeBSD 12.1-STABLE GENERIC  amd64
```

Add workaround for FreeBSD that it isn't able to process PDF

---

.github/workflows/ci.yml

Sometimes the cache breaks and the test fails.
https://github.com/rmagick/rmagick/runs/601806135
The test will continue to fail unless  we update the cache key or get rid of the broken cache..
So, This PR disable the cache action because it looks unstable.
(If it becomes stable, we can revert this PR)

CI: Disable cache

---

ext/RMagick/rmmain.c

Related to https://github.com/rmagick/rmagick/issues/1210
This patch will show the error message, like
```
$ ruby rmagick-sample.rb
Traceback (most recent call last):
2: from rmagick.rb:1:in `<main>'
1: from /Users/watson/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/watson/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- rmagick (LoadError)
9: from rmagick.rb:1:in `<main>'
8: from /Users/watson/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
7: from /Users/watson/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
6: from /Users/watson/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/core_ …
```

Updated error messages if runtime ImageMagick version was not matched with when installed rmagick

---

ext/RMagick/rmfill.c
spec/rmagick/texture_fill/initialize_spec.rb

Fix #1215
If exception was raised in TextureFill.new,
rm_TextureFill structure might not be initialized properly.
Then, the assertion failed error will be occurred when destroy Image object
in uninitialized structure member.

Fix assertion failed in Magick::TextureFill.new with with unexpected argument

---

before_install_linux.sh
before_install_osx.sh
spec/rmagick/image/liquid_rescale_spec.rb

Magick::Image#liquid_rescale requires ImageMagick feature which need to install liblqr (http://liblqr.wikidot.com).
seems that Windows version of ImageMagick binary have liblqr as built-in.

RSpec: Enable spec of Magick::Image#liquid_rescale

---

spec/spec_helper.rb

The existing message doesn't give any context as to why it's skipped, so this adds some explanation.
**Before:**
```
Pending: (Failures listed here are expected and do not affect your suite's status)
1) Magick::Image#channel_entropy raises an error on earlier versions
```
**After:**
```
Pending: (Failures listed here are expected and do not affect your suite's status)
1) Magick::Image#channel_entropy raises an error on earlier versions
```

Add messages to `unsupported_before` and `supported_before` helpers

---

spec/rmagick/image/changed_predicate_spec.rb

Discovered that there is no way for an image to transition from changed to not changed.
Added a test to document this behavior by saving an image and verifying that `changed?` still returns true.

Flesh out changed_predicate_spec.

---

.github/workflows/ci.yml
ext/RMagick/rmdraw.c
ext/RMagick/rmilist.c
ext/RMagick/rminfo.c
ext/RMagick/rmutil.c
spec/rmagick/image/new_spec.rb

It is a correction of #699 
If the block has no arguments, it will be called in the usual way.
If the block has arguments, it is called using yield.
This will ensure compatibility.
Also, there are some places where it is difficult to access from inside the block with the same behavior, so we changed it as well.
Please check when you have time

Call with yield if block in Image.new has arguments (#699)

---

.github/workflows/ci.yml

Related to https://github.com/rmagick/rmagick/runs/1106626777
```
1) Magick::Image#read issue #483 can read PDF file
Failure/Error: expect { described_class.read(File.join(FIXTURE_PATH, 'sample.pdf')) }.not_to raise_error
expected no Exception, got #<Magick::ImageMagickError: FailedToExecuteCommand `"gswin64c.exe" -q -dQUIET -dSAFER -dBATCH -dNOPAU...TuB"' (The system cannot find the file specified.
) @ error/delegate.c/ExternalDelegateCommand/475> with backtrace:
```

CI: Use ghostscript 9.50 on Windows to avoid command exection failure in ImageMagick

---

spec/rmagick/image/format_spec.rb

The test code checks whether if #format= works properly.
The format name is not so important in there.
So, this RP removed the code.
See: https://github.com/rmagick/rmagick/pull/1231#issuecomment-702759185

RSpec: Remove MPEG format because it was renamed at 6.9.11-31 and 7.0.10-31

---

ext/RMagick/rmimage.c

Seems that it takes time in blur process.
So, this PR will apply blur only if necessary.
When it resize the image without blur, it reduce time to 1/2.
```ruby
require 'benchmark/ips'
puts Magick::Long_version
Benchmark.ips do |x|
image = Magick::ImageList.new('./Flower_Hat.jpg').first
x.report("resize") do
image.resize(150, 150)
end
end
```
```
This is RMagick 4.1.2 ($Date: 2009/12/20 02:33:33 $) Copyright (C) 2009 by Timothy P. Hunter
Built with ImageMagick 6.9.11-18 Q16 x86_64 2020-06-24 https://imagemagick.org
Built for ruby 2.7.2
Web page: http://rmagick.rubyforge.org
Email: rmagick@rubyforge.org
Warming up --------------------------------------
resize    22.000  i/100ms
Calculating -------------------------------------
resize    231.228  (± 2.6%) i/s -      1.166k …
```

Improve Image#resize performance with ImageMagick 7

---

.github/workflows/ci.yml

Seems that the mirroring of the Windows installer file has stopped at https://ftp.icm.edu.pl/pub/graphics/ImageMagick/binaries/ .
I have stopped updating the latest version of Windows.

Ci: Update ImageMagick version

---

.github/workflows/ci.yml
ext/RMagick/rmagick.h
ext/RMagick/rmmain.c
ext/RMagick/rmutil.c

Seems that ImageMagick might call back in a different thread than Ruby is running in.
If it is a different thread, it would not have a Ruby GVL and it could not retrieve properly Ruby stack.
Unfortunately, there is no API available to check if the current thread has a GVL, so the thread id was checked in here.
There is a private API to check whether the current thread has a GVL :(
https://github.com/ruby/ruby/blob/06b44f819eb7b5ede1ff69cecb25682b56a1d60c/thread.c#L1908-L1919
Related to https://github.com/rmagick/rmagick/issues/464

Avoid crash with monitor feature on Ruby 3.0 

---

ext/RMagick/extconf.rb

Because if there is `rmagick.h` in the list of files to be force recompile,
the build will fail before running tests with `rake test` in mswin environment.
This PR will fix error in https://github.com/rmagick/rmagick/runs/1636694056
(See https://github.com/rmagick/rmagick/pull/1254)

CI: Remove rmagick.h from forced recompile checking

---

README.md

We have been tested with IM 7.0.8 or later.
https://github.com/rmagick/rmagick/issues/256
I will specify support version clearly because earlier IM version might not work.

Doc: Describe IM7 version strictly in requirements of README

---

ext/RMagick/rmutil.c

At least with glibc 2.32, compiling with -O2 causes the following error:
```
In file included from /usr/include/features.h:465,
from /usr/include/assert.h:35,
from rmagick.h:19,
from rmutil.c:13:
/usr/include/pthread.h: In function 'rm_current_thread_id':
/usr/include/pthread.h:1180:1: error: nested function 'pthread_equal' declared 'extern'
1180 | __NTH (pthread_equal (pthread_t __thread1, pthread_t __thread2))
| ^~~~~
/usr/include/pthread.h:1180:1: error: static declaration of 'pthread_equal' follows non-static declaration
In file included from rmutil.c:1895:
/usr/include/pthread.h:255:12: note: previous declaration of 'pthread_equal' was here
255 | extern int pthread_equal (pthread_t __thread1, pthread_t __thread2)
|            ^~~~~~~~~~~~~
make: *** [Makefile:245: rmutil.o] Error 1 …
```

Fix compilation with optimization on glibc

---

CHANGELOG.md

We didn't really document this anywhere, so for now the `CHANGELOG`
seems like probably a reasonable place for people to look.

Release: add context to CHANGELOG for deprecation

---

.github/workflows/ci.yml

This doesn't seem like a huge deal, but I came across this
[`workflow_dispatch` trigger][trigger] for Github Actions that allows
you to trigger a build manually through the interface.
I also changed the `pull_request` setting to trigger for all branches,
not just PRs to `main`. Also not a big deal, since I don't think we've
made a PR to another branch in a while.
[trigger]: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

CI: add workflow_dispatch CI trigger

---

ext/RMagick/rmdraw.c
ext/RMagick/rmilist.c
ext/RMagick/rminfo.c
ext/RMagick/rmutil.c

Fixes #1270
There are a lot of references to `self.` [still in the RMagick
codebase][still] and documentation, so until we get around to cleaning
all of that up and testing it we can remove the deprecation to avoid
creating a lot of noise in people's logs for things they have no control
over.
[still]: https://github.com/rmagick/rmagick/issues/1270

Remove deprecation warning about block syntax

---

doc/comtasks.html
doc/draw.html
doc/ilist.html
doc/image1.html
doc/image3.html
doc/imusage.html
doc/info.html
doc/usage.html

Continued #1279 
"self\.(\w+)" → 'options.#{$1}'
"{\s*self\.(\w+)" → '{ |options| options.#{$1}'

Replace blocks that do not receive arguments in document

---

ext/RMagick/rmilist.c
ext/RMagick/rmmontage.c

`Magick::Montage` does not exist.
Probably a mistake.

Doc: Replace Magick::Montage with Magick::ImageList::Montage

---

.github/workflows/ci.yml

Because older binary for windows can't be retrieved any more from https://ftp.icm.edu.pl/pub/graphics/ImageMagick/binaries/
And it fails to run test-windows (ref. https://github.com/rmagick/rmagick/actions/runs/713707132)
So, this PR stops to run test-windows lane temporary.

CI: Stop to run test-windows because older binary for windows can't be retrieved any more from ftp.icm.edu.pl

---

doc/ex/shadow.rb

Fix #1294
https://github.com/ImageMagick/ImageMagick/blob/75be18b28a037f37aa0c58dd81a044ac113c98e4/MagickCore/visual-effects.c#L2128-L2131
Seems that `ShadowImage()` holds the offset position as layer information, it is not absolute pixel position.
And it needs to be creative when merging images.
It may be easier to use `ImageList#flatten_images` for this case.

Update shadow example

---

ext/RMagick/extconf.rb

This PR escapes the backslashes in the error message and fixes #1295.

Escaped the backslashes in error message.

---

ext/RMagick/rmimage.c
spec/rmagick/image/matte_floodfill_spec.rb

The alpha channel of the target pixel should be set to make sure a proper match can be found. This fixes the issue reported in #1296. And the alpha_trait of the fill pixel should also be set to make sure the alpha channel of the resulting image will be enabled.

Also set the alpha value of the target pixel (#1296).

---

ext/RMagick/rmpixel.c

This patch sets the `alpha_trait` to `BlendPixelTrait`. This makes sure that setting the `background_fill_opacity` in issue #1292 now works with IM7.

Set alpha_trait to BlendPixelTrait when the alpha value of the pixel is not opaque.

---

ext/RMagick/rmagick.h
ext/RMagick/rmimage.c
ext/RMagick/rmpixel.c
ext/RMagick/rmstruct.c
ext/RMagick/rmutil.c

This is a minor refactoring of the previous pull requests and introduces a new method that will set the alpha_trait value when the alpha channel is not fully opaque.

Introduced new method that only sets the alpha_trait of a PixelInfo value when the alpha value is not opaque.

---

ext/RMagick/rmimage.c

This patch will fix wrong description of documentation of Magick::Image#crop .

Doc: Fix documentation of Magick::Image#crop

---

ext/RMagick/rmagick.h
ext/RMagick/rmstruct.c

This patch will suppress following compilation warning messages with clang compiler.
```
rmimage.c:3032:34: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'unsigned int' [-Wshorten-64-to-32]
IMPLEMENT_ATTR_READER(Image, colors, ulong);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
./rmagick.h:453:44: note: expanded from macro 'IMPLEMENT_ATTR_READER'
return C_##type##_to_R_##type(ptr->attr);\
~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
./rmagick.h:439:43: note: expanded from macro 'C_ulong_to_R_ulong'
#define C_ulong_to_R_ulong(attr) UINT2NUM(attr) /**< C unsigned long -> Ruby unsigned long */
~~~~~~~~ ^~~~
```

Suppress compilation warning messages

---

rmagick.gemspec

To fix following error when run the spec with Ruby 3.2.0-dev, this patch will update pry gem version.
```
$ ruby -v
ruby 3.2.0dev (2022-03-19T05:33:04Z master fafa40997e) [x86_64-linux]
$ bundle exec rake
/usr/bin/gmake install target_prefix=
/usr/bin/install -c -m 0755 RMagick2.so /home/watson/prj/rmagick/lib
cp tmp/x86_64-linux/RMagick2/3.2.0/RMagick2.so tmp/x86_64-linux/stage/lib/RMagick2.so
/home/watson/.rbenv/versions/3.2.0-dev/bin/ruby -I/home/watson/.rbenv/versions/3.2.0-dev/lib/ruby/gems/3.2.0+0/gems/rspec-core-3.11.0/lib:/home/watson/.rbenv/versions/3.2.0-dev/lib/ruby/gems/3.2.0+0/gems/rspec-support-3.11.0/lib /home/watson/.rbenv/versions/3.2.0-dev/lib/ruby/gems/3.2.0+0/gems/rspec-core-3.11.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
An error occurred while loading …
```

Fix error in running spec with Ruby 3.2 under development

---

ext/RMagick/rmimage.c
spec/rmagick/image/profile_bang_spec.rb

Fix https://github.com/rmagick/rmagick/issues/1324
Since RMagick 4.x, the using API in `Image#profile!` was changed from `ProfileImage` to `DeleteImageProfile`.
This PR will revert it.

Fix Image#profile! that can't delete exif data

---

ext/RMagick/extconf.rb

Some ImageMagick installations (e.g. on Gentoo Linux when installed
with the package manager) don't return any -L options in pkg-config.
Including an empty rpath is a security risk and should be avoided.
Fixes #1332

Guard against an empty rpath

---

.github/workflows/ci.yml

Restrict the GitHub token permissions only to the required ones.
Even if the attackers will succeed in compromising workflow, they won’t be able to do much.
Ref. https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

CI: Set permissions for GitHub actions

---

rmagick.gemspec

Seems that `test_files` attribute has been deprecated.
If we can remove it from gemspec file, it would reduce distribute gem package size.
Related:
- https://github.com/rubygems/guides/issues/90
- https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecdeprecatedattributeassignment

Remove test_files to reduce gem package size

---

before_install_linux.sh
before_install_osx.sh

Looks like the ImageMagick download URL was changed recently.

CI: Update ImageMagick download URL and fix build error in macOS env

---

.devcontainer/Dockerfile
.devcontainer/ImageMagick6/devcontainer.json
.devcontainer/ImageMagick7/devcontainer.json
.devcontainer/setup-repo.sh
.devcontainer/setup-user.sh

This pull requests add codespaces configuration so that someone could make changes to our code and run the unit tests in the browser without needing to install anything themselves. This is done automatically but they user will need to wait for this. This PR adds two configurations one for ImageMagick 6 and another one for ImageMagick 7. But both configurations are using Ruby 3.1.2. We cannot use the pre-build configuration because we are using a custom configuration but I hope that will become available in the future so users don't need to wait for this.

Added codespaces configurations

---

before_install_osx.sh

Seems that libxml2 in Homebrew has been broken and it fails to build ImageMagick.
https://github.com/rmagick/rmagick/runs/8168706294
Remove libxml installation since we haven't been tested with ImageMagick features that depend on libxml2.

CI: Do not install libxml2 for macOS environment

---

.devcontainer/devcontainer.json

Moving this file makes the ImageMagick 7 devcontainer the default container when someone creates a codespace without configuring it.

Make ImageMagick 7 the default devcontainer.

---

ext/RMagick/rmimage.c
ext/RMagick/rminfo.c

These methods need to be removed to support releasing GVL.
https://github.com/rmagick/rmagick/pull/1352

Mark Magick::{Image, Image::Info}#monitor= as deprecated

---

lib/rmagick_internal.rb

This method needs to be removed to support Ractor feature.
https://github.com/rmagick/rmagick/pull/1351

Mark Magick.trace_proc= as deprecated

---

ext/RMagick/extconf.rb

Fix https://github.com/rmagick/rmagick/issues/1358
If incorrect pkg-config file installed on the system, `pkg-config --list-all` commands triggers a SEGV and rmagick installation fails.
Therefore, `pkg-config --list-all` should not be used in this PR.

Improve installer in order to avoid SEGV within pkg-config command

---

ext/RMagick/rmdraw.c
ext/RMagick/rmilist.c
ext/RMagick/rminfo.c
ext/RMagick/rmutil.c

- ❌ `img.to_blob` { self.quality = 75 }`
- ✔️ `img.to_blob { |image| image.quality = 75 }`

Remove deprecated #instance_eval calling when block was given with Magick::ImageList#montage, Magick::Image::Info.new and more

---

ext/RMagick/extconf.rb
ext/RMagick/rmagick.h
ext/RMagick/rmagick_gvl.h
ext/RMagick/rmdraw.c
ext/RMagick/rmfill.c
ext/RMagick/rmilist.c
ext/RMagick/rmimage.c
ext/RMagick/rmkinfo.c
ext/RMagick/rmutil.c

With releasing GVL, it would improve performance when processing images in a multi-thread.
Fix https://github.com/rmagick/rmagick/issues/243
```ruby
t1 = Thread.new do
1000.times do
img = Magick::Image.read('Flower_Hat.jpg').first
thumbnail = img.resize(76, 76)
end
end
t2 = Thread.new do
1000.times do
img = Magick::Image.read('Flower_Hat.jpg').first
thumbnail = img.resize(76, 76)
end
end
t1.join
t2.join
```
Before | After
-- | --
3.455 sec | 1.766 sec
- Linux
- Manjaro Linux x86_64
- Kernel: 6.0.2-2-MANJARO
- AMD Ryzen 7 5800H
- gcc version 12.2.0
- Ruby 3.1.2
```
$ time ruby thread.rb
ruby thread.rb  3.30s user 0.09s system 98% cpu 3.455 total
```
```
$ time ruby thread.rb
ruby thread.rb  3.32s user 0.07s system 192% cpu 1.766 total
```

Improve multi-thread performance by releasing GVL

---

ext/RMagick/rmagick.h
ext/RMagick/rmdraw.c
ext/RMagick/rmenum.c
ext/RMagick/rmfill.c
ext/RMagick/rmilist.c
ext/RMagick/rmimage.c
ext/RMagick/rminfo.c
ext/RMagick/rmkinfo.c
ext/RMagick/rmmain.c
ext/RMagick/rmmontage.c
ext/RMagick/rmpixel.c
ext/RMagick/rmutil.c
lib/rmagick.rb
lib/rmagick/version.rb
lib/rmagick_internal.rb
spec/magick_spec.rb

[Ractor](https://docs.ruby-lang.org/en/3.0/Ractor.html) was introduced at Ruby 3.0.
This PR will support `Ractor` feature.
See [Appendix F. Ractor support](https://github.com/ruby/ruby/blob/v3_0_0/doc/extension.rdoc#appendix-f-ractor-support-) for details.
```ruby
1000.times do
img = Magick::Image.read('Flower_Hat.jpg').first
thumbnail = img.resize_to_fit(76, 76)
end
1000.times do
img = Magick::Image.read('Flower_Hat.jpg').first
thumbnail = img.resize_to_fill(76, 76)
end
```
```ruby
r1 = Ractor.new do
1000.times do
img = Magick::Image.read('Flower_Hat.jpg').first
thumbnail = img.resize_to_fit(76, 76)
end
end
r2 = Ractor.new do
1000.times do
img = Magick::Image.read('Flower_Hat.jpg').first
thumbnail = img.resize_to_fill(76, 76)
end
end
r1.take
r2.take …
```

Add Ractor support

---

ext/RMagick/extconf.rb

* This can cause a lot of headaches and break compilation.
* For instance it causes https://github.com/oracle/truffleruby/issues/2779
* Remove old workaround for Ruby 1.8.5

Avoid overriding compilation variables

---

README.md
before_install_osx.sh
ext/RMagick/extconf.rb
rmagick.gemspec

RMagick installation fails if pkg-config command is not installed.
Therefore, we remove the dependency on the command and instead use the ruby gem to get the same functionality.

Remove pkg-config command dependency

---

before_install_osx.sh

We would like to run the test with ImageMagick 6.9 in IM6.9 lane, however, it has been ran with the version that is pre-installed.
https://github.com/rmagick/rmagick/actions/runs/3452753745/jobs/5762871081

CI: Uninstall preinstalled ImageMagick on macOS

---

spec/rmagick/image/preview_spec.rb
spec/rmagick/image_list/montage_spec.rb

https://github.com/actions/virtual-environments/issues/5998
Now, seems that `ubuntu-latest` has been ran under ubuntu 22.04 image.
(It may just be a switch in some of the repositories at forked.)
The old ImageMagick fails following error with newer ghostscript.
```
Magick::ImageMagickError:
`%s' (%d) "gs" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" -g132x24  "-sOutputFile=/tmp/magick-C0LV427g--0000001" "-f/tmp/magick-lZG6pHGl" "-f/tmp/magick-OkJdSSuv" @ error/utility.c/SystemCommand/1890
```
(Ref. https://github.com/Watson1978/rmagick/actions/runs/3559587617/jobs/5979044625)
So, this PR will skip the failure specs.

CI: Support ubuntu 22.04

---

before_install_osx.sh

GitHub's macOS images now install libraw by default.
If libraw exists ImageMagick will be configured to use it, however ImageMagick 7.0 will cause a build error.
RMagick tests has not been used RAW files, so this PR disable libraw to solve build errors.

CI: Fix IM 7.0 build error on macOS

---

doc/image1.html
ext/RMagick/rmmain.c

This PR adds the missing `OnAlphaChannel` and `OffAlphaChannel` values to the `AlphaChannelOption` enumeration to fix the issue reported in #1376.

Add OnAlphaChannel and OffAlphaChannel to the AlphaChannelOption enumeration.

---

lib/rmagick_internal.rb

when a directory is specified in the PATH environment variable where ImageMagick is not properly installed, `RubyInstaller::Runtime.add_dll_directory` will raise an exception.
```
C:\tmp>SET PATH=C:\ImageMagick;%PATH% & ruby -r rmagick -e "puts Magick::Version"
C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/ruby_installer/runtime/dll_directory.rb:104:in `add_dll_directory_winapi': AddDllDirectory failed for C:/ImageMagick (RubyInstaller::Runtime::DllDirectory::WinApiError)
from C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/ruby_installer/runtime/dll_directory.rb:64:in `initialize'
from C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/ruby_installer/runtime/singleton.rb:12:in `new'
from C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/ruby_installer/runtime/singleton.rb:12:in `add_dll_directory'
from …
```

Windows: Fix RubyInstaller::Runtime::DllDirectory::WinApiError

---

.github/workflows/ci.yml
before_install_linux.sh

When we have been using actions/cache@v1, it sometimes went bad.
But v3 may be more stable.
ref. https://github.com/rmagick/rmagick/pull/1195, https://github.com/rmagick/rmagick/pull/1208

CI: Add actions/cache@v3

---

ext/RMagick/rmdraw.c

Fix wrong rb_gc_location() usage in https://github.com/rmagick/rmagick/pull/1388

Fix rb_gc_location() usage

---

before_install_osx.sh

liblqr requires glib, however, it seems that it breaks dependency in github runner.
Sometimes, it causes the following error.
```
/usr/local/Cellar/liblqr/0.4.2_1/include/lqr-1/lqr.h:26:10: fatal error: 'glib.h' file not found
#include <glib.h>
^~~~~~~~
```

CI: Add path for glib on macOS

---

spec/magick_spec.rb

ruby_xmalloc is called when ImageMagick requires memory. 
Seems that it causes lock condition at rb_native_mutex_lock with running ractor on Ruby 3.0 sometimes.
```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
* frame #0: 0x00000001911b2bc8 libsystem_kernel.dylib`__psynch_mutexwait + 8
frame #1: 0x00000001911ed0c4 libsystem_pthread.dylib`_pthread_mutex_firstfit_lock_wait + 84
frame #2: 0x00000001911eaa5c libsystem_pthread.dylib`_pthread_mutex_firstfit_lock_slow + 248
frame #3: 0x0000000104409b64 ruby`rb_native_mutex_lock(lock=0x000000012a00d630) at thread_pthread.c:397:14
frame #4: 0x00000001044a3564 ruby`vm_lock_enter(cr=0x0000000129e05100, vm=0x000000012a00d600, locked=false, no_barrier=false, lev=0x000000012a00d678) at vm_sync.c:56:9
frame #5: …
```

Spec: Run ractor spec with Ruby 3.1 or later

---

ext/RMagick/rmdraw.c

Fix https://github.com/rmagick/rmagick/issues/1401
Before | After
-- | --
```ruby
3000.times do |i|
img = Magick::Image.new(1000, 1000)
gc = Magick::Draw.new
gc.text(0, 67, 'Hello world!!')
gc.draw(img)
end
```

Fix memory leak in `Magick::Draw` for recentry ImageMagick 6 by removing unnecessary `GetDrawInfo()` calling

---

.github/workflows/ci.yml

The latest [github-actions](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md) have been bundled jpeg-turbo library.
However, it causes build error with un-maintenance imagemagick version on macOS by the library.
https://github.com/ImageMagick/ImageMagick/issues/6514
So, this PR will remove 7.0.11-14 lane which is un-maintenance imagemagick version.

CI: Remove 7.0.11-14 lane in macOS

---

rmagick.gemspec

The observer gem will be changed bundled gem since Ruby 3.4.0. https://github.com/ruby/ruby/commit/6500f85927135901f365d2ba1186c5c4f2881f8e
To use bundled gem, it  requires to specify the dependency in Gemfile.
This patch will fix following warning with Ruby 3.3.0
```
/Users/watson/prj/rmagick/lib/rmagick_internal.rb:24: warning: observer which will be not part of the default gems since Ruby 3.4.0
```

Add observer gem as dependency

---

Gemfile

The latest version of `parser` gem depends on methods introduced in Ruby 2.5.
It causes following error when run lint lane in CI.
```
undefined method `delete_suffix' for "        END_EXHTMLHEAD":String
/home/runner/work/rmagick/rmagick/vendor/bundle/ruby/2.3.0/gems/parser-3.3.0.0/lib/parser/lexer/literal.rb:250:in `delimiter?'
/home/runner/work/rmagick/rmagick/vendor/bundle/ruby/2.3.0/gems/parser-3.3.0.0/lib/parser/lexer/literal.rb:138:in `nest_and_try_closing'
/home/runner/work/rmagick/rmagick/vendor/bundle/ruby/2.3.0/gems/parser-3.3.0.0/lib/parser/lexer-strings.rb:3[78](https://github.com/Watson1978/rmagick/actions/runs/7414039270/job/20211269955#step:4:79)9:in `advance'
:
```
https://github.com/Watson1978/rmagick/actions/runs/7414039270/job/20211269955

CI: Fix parser gem version in order to run rubocop with Ruby 2.3

---

ext/RMagick/rmagick.c
ext/RMagick/rmagick.h
ext/RMagick/rmdraw.c
ext/RMagick/rmenum.c
ext/RMagick/rmfill.c
ext/RMagick/rmimage.c
ext/RMagick/rminfo.c
ext/RMagick/rmkinfo.c
ext/RMagick/rmmain.c
ext/RMagick/rmmontage.c
ext/RMagick/rmpixel.c

The name of `class`  can only be used to define a class in C++.

Rename `class` variable names because it is reserved word in C++

---

ext/RMagick/extconf.rb

Because the installer does not refer to the path specified by `--with-opt-dir`.

Fix error message of installation failed on Windows

---

Gemfile

The parser gem has still supported Ruby 2.0+
https://github.com/whitequark/parser/pull/986
This reverts commit 6f906a811a2530f7ae512340ae35ac92e2f2428c.

Revert "CI: Fix parser gem version in order to run rubocop with Ruby 2.3 (#1422)"

---

ext/RMagick/rmdraw.c
ext/RMagick/rmilist.c
ext/RMagick/rmimage.c

The following code is written in places:
```c
CompositeOperator operator = OverCompositeOp;
```
The `operator` has been used by operator overloading in C++.
So, the variable name `operator` causes conflict as operator overloading.

Rename `operator` variable names for C++

---

ext/RMagick/extconf.rb
ext/RMagick/rmagick.c
ext/RMagick/rmagick.h
ext/RMagick/rmenum.c
ext/RMagick/rmimage.c
ext/RMagick/rmmain.c
ext/RMagick/rmpixel.c
ext/RMagick/rmutil.c

In C++, type checking is strictly enforced when function pointer is given as an argument if functions have `ANYARGS` type.

Add type casting of function pointer for C++

---

ext/RMagick/rmagick.h
ext/RMagick/rmdraw.c
ext/RMagick/rmenum.c
ext/RMagick/rmilist.c
ext/RMagick/rmimage.c
ext/RMagick/rmmontage.c
ext/RMagick/rmpixel.c
ext/RMagick/rmstruct.c
ext/RMagick/rmutil.c

The C++ compiler requires strict type for cast.

Add type casts  for disambiguation

---

doc/constants.html
ext/RMagick/rmmain.cpp

Defined in https://github.com/ImageMagick/ImageMagick/blob/92c93c30aded7dbdbc1e5f2ec9b9774da0bf20b9/MagickCore/resample.h#L77-L78

Add aliases of filter type

---

ext/RMagick/rmdraw.cpp
ext/RMagick/rmimage.cpp

Doing reinterpret_cast from pointer type to enum type causes unexpected results on big endian arch because their sizes differ.
So once do reinterpret_cast to intptr_t, which has the same size as pointer type, then do static_cast to the desired type.
Fixes #1447

FIX: fix invalid cast between different size variables

---

ext/RMagick/extconf.rb

Fix https://github.com/rmagick/rmagick/issues/1459
It seems that in some environments it is not possible to determine the language used in the source code by the file extension.

Use x flag to use C++ compiler in order to create Makefile

---

ext/RMagick/rmpixel.cpp
spec/rmagick/pixel/spaceship_spec.rb

Now, Pixel#<=> raises a TypeError exception if other class instance was given.
```
irb(main):001:0> require 'rmagick'
=> true
irb(main):002:0> pixel = Magick::Pixel.from_color('brown')
=> #<Magick::Pixel:0x000000010197dae0>
irb(main):003:0> pixel <=> 1234
(irb):3:in `<=>': wrong argument type Integer (expected Magick::Pixel) (TypeError)
```
However, Ruby built-in classes (ex. String#<=>) accept that.
```
irb(main):001:0> "hello" <=> 1234
=> nil
```
So this patch will fix Pixel#<=> behavior to make more Ruby flavor.

Fix Pixel#<=> which should accept other class instance

---

ext/RMagick/extconf.rb

'-x c++' should be added before we call try_link(). Otherwise it fails on some versions of clang with:
```
DYLD_FALLBACK_LIBRARY_PATH=.:/nix/store/3ryrxm7jlpprln40mcqagvb366plx182-ruby-3.2.2/lib "clang -o conftest -I/nix/store/3ryrxm7jlpprln40mcqagvb366plx182-ruby-3.2.2/include/ruby-3.2.0/arm64-darwin22 -I/nix/store/3ryrxm7jlpprln40mcqagvb366plx182-ruby-3.2.2/include/ruby-3.2.0/ruby/backward -I/nix/store/3ryrxm7jlpprln40mcqagvb366plx182-ruby-3.2.2/include/ruby-3.2.0 -I../../../../ext/RMagick -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_CHANNEL_MASK_DEPTH=32 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/nix/store/hgdbh1i3bqlc2ns7279708n3d6d05nqi-imagemagick-7.1.1-19-dev/include/ImageMagick-7 -fdeclspec -O3 -fno-fast-math -ggdb3 …
```

Fix makefile generation in nix

---

ext/RMagick/rmfill.cpp
spec/rmagick/gradient_fill/fill_spec.rb
spec/rmagick/texture_fill/fill_spec.rb

Magick::HatchFill#fill accepts Magick::ImageList object.
```
irb(main):001:0> require 'rmagick'
=> true
irb(main):002:0> imgl = Magick::ImageList.new
=>
[]
...
irb(main):003:0> imgl.new_image(10, 10)
=>
[  10x10 DirectClass 16-bit]
scene=0
irb(main):004:0> gradient = Magick::HatchFill.new('white', 'lightcyan2')
irb(main):005:0> gradient.fill(imgl)
=> 10
```
However, Magick::GradientFill#fill does not accept it.
```
irb(main):001:0> require 'rmagick'
=> true
irb(main):002:0> imgl = Magick::ImageList.new
=>
[]
...
irb(main):003:0> imgl.new_image(10, 10)
=>
[  10x10 DirectClass 16-bit]
scene=0
irb(main):004:0> gradient = Magick::GradientFill.new(0, 0, 0, 0, '#900', '#000')
irb(main):005:0> gradient.fill(imgl)
(irb):5:in `fill': wrong argument type Magick::ImageList (expected Magick::Image) …
```

Fix Magick::GradientFill#fill and Magick::TextureFill#fill to accept ImageList object

---

.rubocop_todo.yml
lib/rmagick_internal.rb

When it call ImageList method via method_missing even if the method return self in Image method, it will return Image object.
```
imgl = Magick::ImageList.new("Flower_Hat.jpg")
p imgl.resize!(0.50).class # => Magick::Image
```
This patch will return ImageList object.

Return self with ImageList if Image's method return self

---

ext/RMagick/rminfo.cpp
lib/rmagick_internal.rb

Standard Ruby attribute writers return the given value as-is
```
class Foo
attr_writer :bar
end
obj = Foo.new
obj.send(:bar=, nil) #=> nil
```
However, some RMagick attribute writers return self object.
```
info.send(:density=, nil) #=> #<Magick::Image::Info:0x0000000104fcae40>
```
This patch will change them to standard Ruby behavior.

Attribute writer methods should return passed value

---

ext/RMagick/rmmain.cpp

PolaroidOptions and DrawOptions have shared methods for attribute writer. However, PolaroidOptions is missing #tile=.
This patch will add missing attribute writer in PolaroidOptions

Add Image::PolaroidOptions#tile=

---

ext/RMagick/rmmain.cpp

Same with https://github.com/rmagick/rmagick/pull/1474
PolaroidOptions and DrawOptions have shared methods for attribute writer. However, PolaroidOptions is missing #affine=.
This patch will add missing attribute writer in PolaroidOptions

Add Image::PolaroidOptions#affine=

---

ext/RMagick/rmmain.cpp

Same with https://github.com/rmagick/rmagick/pull/1474
PolaroidOptions and DrawOptions have shared methods of Draw class for attribute writer.
This patch will add missing attribute writers in DrawOptions and PolaroidOptions

Add missing attribute writer methods in Image::{DrawOptions, PolaroidOptions}

---

lib/rmagick_internal.rb
spec/rmagick/image_list/spaceship_spec.rb

Standard Ruby implementation returns nil when it can't compare
```
p "aaa" <=> "xxx"      # => -1
p "aaa" <=> "aaa"      # => 0
p "aaa" <=> Object.new # => nil
```
This patch follows that behaviour.

Fix ImageList#<=> that should return nil if can't compare

---

.rubocop_todo.yml
lib/rmagick_internal.rb

Standard Ruby implementation of ! method returns self. However, ImageList#sort! has wrong behaviour.
```
imgl = Magick::ImageList.new
p imgl.object_id       # => 60
p imgl.sort!.object_id # => 80
```
This patch follows that behaviour.

Fix ImageList#sort! that should return self

---

lib/rmagick_internal.rb
spec/rmagick/draw/stroke_dasharray_spec.rb
spec/rmagick/draw/stroke_miterlimit_spec.rb

The Draw method implemented in magick_internal.rb can implicitly convert objects with #to_f.

Fix Draw#{stroke_dasharray, stroke_miterlimit} to accept object which has #to_f method

---

.gitignore
ext/RMagick/extconf.rb

You can use appropriate code completion via clangd, etc.
If you use Visual Studio Code, you can use [clangd](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd) extension.

Generate compile_flags.txt for clangd for development

---

lib/rmagick_internal.rb
spec/rmagick/draw/interline_spacing_spec.rb
spec/rmagick/draw/interword_spacing_spec.rb
spec/rmagick/draw/kerning_spec.rb

For example, it would not work correctly when passed Rational object.
```
draw.interline_spacing(1/4r)
```

Fix Draw#{interline_spacing, interword_spacing, kerning} to correctly handle arguments that can be converted to Float

---

lib/rmagick_internal.rb
spec/rmagick/draw/fill_opacity_spec.rb
spec/rmagick/draw/opacity_spec.rb
spec/rmagick/draw/stroke_opacity_spec.rb

Similar with https://github.com/rmagick/rmagick/pull/1491

Fix Draw#{fill_opacity, opacity, stroke_opacity} to correctly handle arguments

---

lib/rmagick_internal.rb
spec/rmagick/draw/clip_path_spec.rb
spec/rmagick/draw/define_clip_path_spec.rb
spec/rmagick/draw/encoding_spec.rb
spec/rmagick/draw/font_family_spec.rb
spec/rmagick/draw/font_spec.rb
spec/rmagick/draw/path_spec.rb
spec/rmagick/draw/pattern_spec.rb

String interpolation, it will convert object to string using #to_s automatically. Unexpected objects are accepted because all object have #to_s.
```
irb(main):001> "hello #{Object.new}"
=> "hello #<Object:0x000000011dd30770>"
```

Coerce to string where pass object into string interpolation

---

lib/rmagick_internal.rb

This patch unify behaviour because some methods also accept Symbol.
Similar with https://github.com/rmagick/rmagick/pull/1494

Implicit conversion to string with methods that expect a string

---

doc/image2.html
ext/RMagick/rmimage.cpp
spec/rmagick/image/modulate_spec.rb

By this patch, Image#modulate will accept “NN%” form string like Image#watermark.

Improve Image#modulate to accept "NN%" form string

---

lib/rvg/misc.rb

font_stretch and font_style methods accept Symbol object.
So, this patch will accept Symbol at font_weight as well.

Improve GraphicContext#font_weight to accept Symbol object

---

lib/rmagick_internal.rb
spec/rmagick/image_list/new_image_spec.rb

The first argument of `HatchFill.new` accepts a Pixel object.
However, the second does not.
So, this patch make arguments same behavior.

Improve HatchFill.new to accept Pixel object as color

---

ext/RMagick/rmimage.cpp

Because implicit type conversion and type check are performed by NUM2LONG().
Similar with https://github.com/rmagick/rmagick/pull/1489

Remove unnecessary type check in Image#{morphology, morphology_channel}

---

ext/RMagick/rmmain.cpp

We have been checked that ImageMagick major, minor and patch versions match when compiled and run.
1. We haven't been switched RMagick functionality with each of the latest ImageMagick patch versions. Therefore, I consider it sufficient to check up to the minor version.
2. If user accidentally updates ImageMagick, and the patch version is updated, an error will occur at runtime, which is inconvenient.
- It raises exception like `This installation of RMagick was configured with ImageMagick 6.9.12 but ImageMagick 6.9.13-7 is in use. (RuntimeError)`.
And this remove the RMAGICK_BYPASS_VERSION_TEST logic as I don't think anyone uses it.

Loosen ImageMagick version check between compiled and runtime

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
before_install_linux.sh
ext/RMagick/extconf.rb
ext/RMagick/rmagick.h
ext/RMagick/rmimage.cpp
ext/RMagick/rmmain.cpp
lib/rmagick/version.rb
spec/rmagick/image/channel_mean_spec.rb

Ubuntu 14.04 installs ImageMagick 6.7 via `apt install` command. https://launchpad.net/ubuntu/trusty/+package/imagemagick
However, Ubuntu 14.04 will be EOL in April 2024.
https://wiki.ubuntu.com/Releases
Finally, we can drop ImageMagick 6.7 support.

Drop ImageMagick 6.7 support

---

ext/RMagick/extconf.rb

To use the following APIs, the header files should have been checked in advance
```ruby
memory_api = %w[
posix_memalign
malloc_usable_size
malloc_size
_aligned_msize
]
```

Fix header checks in order to use aligned_malloc expectedly

---

doc/ex/font_styles.rb
doc/ex/get_type_metrics.rb
doc/ex/text.rb
doc/ex/text_antialias.rb
doc/ex/watermark.rb
doc/ex/wet_floor.rb
ext/RMagick/extconf.rb
spec/magick_spec.rb
spec/rmagick/class_methods/formats_spec.rb
spec/rmagick/class_methods/init_formats_spec.rb

As a Ruby runtime environment on Windows, there is MINGW and MSWIN.
I think almost everyone uses [RubyInstaller](https://rubyinstaller.org/) to run Ruby, and it is MINGW environment.
MSWIN sets up the compiler itself and compiles Ruby from source code to create the environment.
I believe that this is very difficult and only some Ruby committers do that.
I will drop MSWIN support because it become difficult (related to https://github.com/rmagick/rmagick/pull/1585)

Drop ruby-mswin environment support on Windows

---

ext/RMagick/rmimage.cpp

Fix https://github.com/rmagick/rmagick/issues/1339

Fix truncating of values that causes pixels 65534.9609375 to become 65534 instead of 65535 (#1339).

---

CHANGELOG.md
doc/struct.html
ext/RMagick/rmpixel.cpp
ext/RMagick/rmutil.cpp
spec/rmagick/image/background_color_spec.rb
spec/rmagick/image/border_color_spec.rb
spec/rmagick/image/colormap_spec.rb
spec/rmagick/image/info/background_color_spec.rb
spec/rmagick/image/info/border_color_spec.rb
spec/rmagick/image/info/matte_color_spec.rb
spec/rmagick/image/info/transparent_color_spec.rb
spec/rmagick/image/pixel_color_spec.rb
spec/rmagick/image_list/montage_spec.rb
spec/rmagick/pixel/to_color_spec.rb

Fix https://github.com/rmagick/rmagick/issues/1400
The some methods to get color information returned either a hex string or a color name.
Depending on the image settings, the color names were not  returned as expected.
So, this patch will always return hex string as color information.
The methods affected by this change are as follows:
- Image#background_color
- Image#border_color
- Image#colormap
- Image#matte_color
- Image#transparent_color
- Info#background_color
- Info#border_color
- Info#matte_color
- Info#transparent_color
----
- Change default value of hex argument for Pixel#to_color

Change method that returns a color name to return a hex string

---

CHANGELOG.md
ext/RMagick/rmutil.cpp

Fix https://github.com/rmagick/rmagick/issues/46
If colorspace is set through Image#colorspace, the image will be transformed properly.
However, if use Info#colorspace, it is not. It should be transformed as well.
```ruby
image = Magick::Image.read('doc/ex/images/Button_0.gif').first
image.colorspace = Magick::GRAYColorspace
image.write('Image_colorspace_eq.gif')
image = Magick::Image.read('doc/ex/images/Button_0.gif') { |info| info.colorspace = Magick::GRAYColorspace }.first
image.write('Info_colorspace_eq.gif')
```
The result with before changing:
- Image_colorspace_eq.gif
- ![Image_colorspace_eq](https://github.com/rmagick/rmagick/assets/199156/76a22bb7-6504-4b56-923f-ccaf4345fcd7)
- Info_colorspace_eq.gif
- ![Info_colorspace_eq](https://github.com/rmagick/rmagick/asse …

Transform image according to Info#colorspace

---

README.md

ImageMagick Installer has been changed the checkbox label.
Related to https://github.com/rmagick/rmagick/pull/1588

Update screenshot in README for Windows

---

Rakefile

I wanted `rake install` and added it at https://github.com/rmagick/rmagick/pull/1458/files#diff-ee98e028c59b193d58fde56ab4daf54d43c486ae674e63d50ddf300b07943e0f
However, `bundler/gem_tasks` also has release tasks, which overlap with our own tasks. Each tasks would be executed when invoke `release`

Rakefile: Fix duplicate release tasks

---

rmagick.gemspec

Ref. https://guides.rubygems.org/specification-reference/#metadata

Add metadata in gemspec for bug tracker, documentation and changelog URLs

---

before_install_osx.sh

This PR specifies installed dir of ghostscript font .
(Related to https://github.com/rmagick/rmagick/issues/279)

Update build script to use fonts correctly

---

examples/demo.rb
examples/find_similar_region.rb
examples/histogram.rb
examples/identify.rb
examples/import_export.rb
ext/RMagick/rmagick.h

GraphicsMagick support had been removed at RMagick 2.0.
https://github.com/rmagick/rmagick/blob/6795bc4dd79c768a7982287cb4b4985674682daa/CHANGELOG.md?plain=1#L872

Remove codes for GraphicsMagick

---

.rubocop_todo.yml
lib/rmagick_internal.rb

Before Ruby 2.4 in RubyInstaller (https://rubyinstaller.org/), it raises a LoadError exception because it does not have `ruby_installer.rb`.
Remove unnecessary `rescue` due to be stopped support. https://github.com/rmagick/rmagick/pull/1540

Rubocop: Fix Lint/SuppressedException

---

Rakefile

The C++ code is not recompiled, so the latest state is not loaded. 
It delete the task because it is not used for above reason.

Rakefile: Remove unused task

---

ext/RMagick/extconf.rb

Fix https://github.com/rmagick/rmagick/issues/1615
The `-fno-omit-frame-pointer` is set in the Windows environment, and a flag is added to revert it.
Maybe it's a GCC issue in a Windows environment, but I'm not sure of the details.

Add `-fomit-frame-pointer` in order to fix compile error with GCC 14

---

ext/RMagick/extconf.rb

macOS  bundles Ruby 2.6, even macOS 15 beta.
```
$ sw_vers
ProductName:		macOS
ProductVersion:		15.0
BuildVersion:		24A5264n
$ /usr/bin/ruby -v
ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin24]
```
RMagick does not support this version.
The configuration for universal build that is not set as expected because $ARCH_FLAG returns an empty string with system bundled ruby.
```
$ irb
WARNING: This version of ruby is included in macOS for compatibility with legacy software.
In future versions of macOS the ruby runtime will not be available by
default, and may require you to install an additional package.
irb(main):001:0> RUBY_VERSION
=> "2.6.10"
irb(main):002:0> require 'mkmf'
=> true
irb(main):003:0> $ARCH_FLAG
=> ""
```

Remove universal build configuration for system bundled ruby in macOS

---

ext/RMagick/extconf.rb

If use old ruby to install, it show the following message.
```
$ gem install ./rmagick-6.0.1.gem
ERROR:  Error installing ./rmagick-6.0.1.gem:
There are no versions of rmagick (= 6.0.1) compatible with your Ruby & RubyGems
rmagick requires Ruby version >= 3.0.0. The current ruby version is 2.7.8.225.
```
It is in https://github.com/rubygems/rubygems/blob/a15e2cb599e1415d0e9577eb7ca2d0df985a4c38/lib/rubygems/request_set.rb#L199
The supported ruby version check is invoked at rubygems system at first before calling assert_minimum_ruby_version!.
So, this patch will remove redundant version check.

Remove unnecessary minimum ruby version check

---

README.md
doc/struct.html
doc/usage.html
ext/RMagick/rmagick.h
ext/RMagick/rmilist.cpp
lib/rmagick_internal.rb

Because `RMagick.rb` was removed at https://github.com/rmagick/rmagick/pull/1361

Doc: Fix file name in documents

---

doc/index.html
doc/usage.html

At least since Ruby 2, rubygem is automatically required

Doc: Remove unnecessary `require 'rubygems'`

---

ext/RMagick/extconf.rb

If ImageMagick is not installed, installer show the following exception:
```
$ ruby extconf.rb
checking for brew... yes
/Users/watson/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:504:in `parse_pc': .pc doesn't exist: <MagickCore> (PackageConfig::NotFoundError)
from /Users/watson/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:348:in `declaration'
from /Users/watson/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:289:in `requires'
from /Users/watson/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:545:in `block in required_packages'
from /Users/watson/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/pkg-config-1.5.6/lib/pkg-config.rb:374:in …
```

Suppress exception at installation if ImageMagick is not installed

---

ext/RMagick/extconf.rb

It might be easier to understand if it output the pc_config path to be used.
Here is example of output:
```
$ ruby extconf.rb
checking for brew... yes
Detected ImageMagick packages:
- /Users/watson/imagemagick7.1/lib/pkgconfig/ImageMagick-7.Q16HDRI.pc
- /Users/watson/imagemagick6.9/lib/pkgconfig/ImageMagick-6.Q16.pc
checking for forced use of ImageMagick 6... no
```

Output the pc_config file path

---

.github/workflows/ci.yml
before_install_linux.sh

ubuntu-latest now uses ubuntu 24.04 image.
CI no longer works as expected with ubuntu 24.04, so this will be fixed.

CI: fix for Ubuntu 24.04

---

doc/index.html

Because https://www.imagemagick.org/discourse-server/ is just archive.
So, this will change the link to proper discussion page.

Doc: Fix link to discussion page

---

ext/RMagick/rmimage.cpp

This patch will raise a RuntimeError exception if read incorrect PDF file.
```
irb(main):001:0> require 'rmagick'
=> true
irb(main):002:0> Magick::Image.read('s.uploading_0001.pdf')
**** Error: Couldn't initialise file.
Output may be incorrect.
No pages will be processed (FirstPage > LastPage).
(irb):2:in `read': ImageMagick library function failed to return a result. (RuntimeError)
from (irb):2:in `<main>'
from /usr/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
from /usr/bin/irb:25:in `load'
from /usr/bin/irb:25:in `<main>'
```
The old ghostscript will ignore the error,
however, the new ghostscript will stop reading with incorrect PDF.
Then, ImageMagick will return NULL and caused a SEGV in rmagick land.
Fix https://github.com/rmagick/rmagick/issues/1670

Fix SEGV if read incorrect PDF file

---

examples/histogram.rb
lib/rvg/rvg.rb

Fix Lint/UselessConstantScoping error.
This cop was introduced at https://github.com/rubocop/rubocop/releases/tag/v1.72.0

Rubocop: Fix Lint/UselessConstantScoping

---

examples/identify.rb
lib/rvg/rvg.rb

This PR will fix following error with rubocop 1.75.5:
```
examples/identify.rb:117:45: C: [Correctable] Style/RedundantParentheses: Don't use parentheses around a method argument.
puts "\tFilesize: #{sprintf('%.1f', (size / 1_048_576.0))}mb\n"
^^^^^^^^^^^^^^^^^^^^
examples/identify.rb:119:45: C: [Correctable] Style/RedundantParentheses: Don't use parentheses around a method argument.
puts "\tFilesize: #{sprintf('%.0f', (size / 1024.0))}kb\n"
^^^^^^^^^^^^^^^
lib/rvg/rvg.rb:117:17: C: [Correctable] Style/RedundantParentheses: Don't use parentheses around a method argument.
print(('   ' * indent), cmd, "\n")
^^^^^^^^^^^^^^^^
```

Rubocop: Fix Style/RedundantParentheses

---

.github/ISSUE_TEMPLATE/report.yml

The template used so far has been obsoleted and it is no longer available.
So, this PR will add new template.

GitHub: Add new issue template

---

ext/RMagick/rmdraw.cpp

RVG adds all objects to be drawn as primitives to a Magick::Draw object. This is a multi-line String object.
When many draw commands are executed, there is a performance bottleneck when concating to the string. Fortunately it's easy to fix.
I have a GUI program which draws some big PDF417 2D codes and it takes several seconds to do so. Almost all time is spend in `Magick::Draw#primitive`:
```
$ stackprof stackprof-cpu-myapp.dump 
==================================
Mode: cpu(1000)
Samples: 4074 (1.90% miss rate)
GC: 1146 (28.13%)
==================================
TOTAL    (pct)     SAMPLES    (pct)     FRAME
2412  (59.2%)        2412  (59.2%)     Magick::Draw#primitive
807  (19.8%)         807  (19.8%)     (sweeping)
400   (9.8%)         400   (9.8%)     (marking)
118   (2.9%)         118 …
```

Fix performance issue with RVG

---

.devcontainer/ImageMagick6/devcontainer.json
.devcontainer/devcontainer.json
.github/workflows/ci.yml
ext/RMagick/extconf.rb
ext/RMagick/rmilist.cpp
ext/RMagick/rmimage.cpp

With ImageMagick 7.1.2-1, it causes following error with CI on Windows.
```
1) Magick::Image#write works
Failure/Error: image1.write(f) { |options| options.format = 'JPEG' }
Magick::ImageMagickError:
unable to open image 'test.0': Permission denied @ error/blob.c/OpenBlob/3596
2) Magick::ImageList#write works
Failure/Error: image_list.write(f) { |options| options.format = 'JPEG' }
Magick::ImageMagickError:
unable to open image 'test.0': Permission denied @ error/blob.c/OpenBlob/3596
3) Magick::ImageList#write issue #1375
Failure/Error: image_list.write(f)
Magick::ImageMagickError:
unable to open image 'C:/Users/watso/AppData/Local/Temp/out.gif': Permission denied @ error/blob.c/OpenBlob/3596
```
The problem in the test was fixed with https://github.com/rmagick/rmagick/pull/1705.

Fixed an error with ImageMagick 7.1.2 on Windows when saving images using file descriptor

---

ext/RMagick/extconf.rb

Fix https://github.com/rmagick/rmagick/issues/1694
Seems `RbConfig::CONFIG['CXX']` has `"false"` string if C++ compiler is not exists since Ruby 3.0.
https://bugs.ruby-lang.org/issues/21111

Improve check whether C++ compiler exists
