.travis.yml, before_install_linux.sh
=> more robust #177(Fix for ImageMagick 404)

ext/RMagick/extconf.rb, ext/RMagick/rmmain.c, test/Magick.rb
Hello,
I tried to add the -alpha remove flag to close #63. Is it correct? Do I need to add tests or other things? I pretty much have no C experience but the change I did works.
Thanks.
=> Added missing -alpha remove flag

.rubocop.yml, lib/rmagick_internal.rb, test/Image2.rb, test/Magick.rb
Hello, I trimmed the trailing whitespace and fixed the indentation. It looks like a lot of changes but if you `git diff 529cfc913b7939ee4330df099d189b65aceaab50..HEAD -w` you will see nothing was changed otherwise apart from `.rubocop.yml`. :smile:
=> Rubocop whitespace fix

lib/rvg/clippath.rb, lib/rvg/container.rb, lib/rvg/deep_equal.rb, lib/rvg/describable.rb, lib/rvg/embellishable.rb, lib/rvg/misc.rb, lib/rvg/paint.rb, lib/rvg/pathdata.rb, lib/rvg/rvg.rb, lib/rvg/stretchable.rb, lib/rvg/stylable.rb, lib/rvg/text.rb, lib/rvg/transformable.rb, lib/rvg/units.rb, test/Image1.rb, test/Image2.rb, test/Image3.rb, test/ImageList2.rb, test/Image_attributes.rb, test/Info.rb, test/Magick.rb, test/Pixel.rb, test/Preview.rb
As mentioned at #210 
Refactor based on style-guides: 
* https://github.com/styleguide/ruby
* https://github.com/bbatsov/ruby-style-guide
PS: There's a lot more to be done!
=> Change indentation style follow ruby style guide (2 spaces)

.travis.yml, README.textile, before_install_linux.sh, ext/RMagick/extconf.rb, ext/RMagick/rmagick.h, lib/rmagick/version.rb, rmagick.gemspec
Both versions have reaches their EOL
=> Drop support for Ruby 1.8 and 1.9

doc/draw.html
https://github.com/rmagick/rmagick/issues/237
=> Update docs for get_type_metrics

README.textile
add documentation link to Using RMagick section for beginner.
I look Using RMagick section, but it mentioned `require 'rmagick'`. so i colud not know that how to use `RMagick`
=> add documentation link to Using RMagick section for beginner

ext/RMagick/rmagick.h, ext/RMagick/rmenum.c, ext/RMagick/rmimage.c, ext/RMagick/rmkinfo.c, ext/RMagick/rmmain.c
Copy of https://github.com/rmagick/rmagick/pull/40
We really need to merge this awesome contribution by @naquad. But it has no tests. @mockdeep, could you cover this with RSpec?
To update this changeset, please open pull requests to the `morphology` branch.
Closes #21 and #24.
=> Morphology

examples/rotating_text.rb
When testing this example no text was coming through, adding a fill setting seems to fix it
=> Text needed a fill in order to be seen

test/Image1.rb, test/Image2.rb, test/Image3.rb, test/Image_attributes.rb
This fixes the tests in Ubuntu Bionic with Ruby 2.5
=> Expect FrozenError starting with Ruby 2.5

ext/RMagick/rmimage.c
If invalid pixels were given in `Image#store_pixels`, `Data_Get_Struct(new_pixel, Pixel, pixel);` will raise exception at https://github.com/rmagick/rmagick/blob/5c2e6a153f963ca67ae9a953fd47b6008fa1cab2/ext/RMagick/rmimage.c#L13166.
Then, `ExceptionInfo` object which is allocated by `AcquireExceptionInfo()` causes memory leak.
* Before
```
$ ruby test.rb
Process: 64765: RSS = 399 MB
```
* After
```
$ ruby test.rb
Process: 64977: RSS = 15 MB
```
* Test code
```ruby
pixels = image.get_pixels(0, 0, image.columns, 1)
pixels[0] = 'x'
begin
image.store_pixels(0, 0, image.columns, 1, pixels)
rescue
end
end
GC.start
```
=> Fix memory leak in Image#store_pixels

CONTRIBUTING.md
Also add our current CI checks and reword a couple of sections.
=> Docs: remove develop from CONTRIBUTING docs

ext/RMagick/rmagick.c
Magick.{color, fonts} methods accept `Proc` to run user's code.
If raise exception in `Proc`, the memory area allocated by ImageMagick API (`GetColorInfoList()`, `GetTypeInfoList()`) can't be released.
* Before
```
$ ruby test.rb
Process: 47987: RSS = 142 MB
```
* After
```
$ ruby test.rb
Process: 49359: RSS = 21 MB
```
* Test code
```ruby
10000.times do
begin
Magick.colors { |color| raise }
rescue
end
begin
Magick.fonts { |font| raise }
rescue
end
end
GC.start
```
=> Fix memory leak in Magick.{color, fonts}

before_install_linux.sh
Instead error and exit out of script when no version is specified.
=> CI: remove latest IM from before_install_linux.sh

ext/RMagick/rmenum.c, ext/RMagick/rmmain.c, test/Image3.rb
Add some enum values of ColorspaceType declared in ImageMagick 6.8.9.
=> Add ColorspaceType enum values

ext/RMagick/rmenum.c, ext/RMagick/rmmain.c, test/Image_attributes.rb
Add some enum values of CompressionType declared in ImageMagick 6.8.9.
=> Add CompressionType enum values

ext/RMagick/rmenum.c, ext/RMagick/rmmain.c, test/Image3.rb, test/Image_attributes.rb
Add some enum values of FilterTypes declared in ImageMagick 6.8.9.
=> Add FilterTypes enum values

ext/RMagick/rmagick.h, ext/RMagick/rmimage.c, ext/RMagick/rmmain.c, test/Image3.rb
Add some enum values of QuantumExpressionOperator declared in ImageMagick 6.8.9.
=> Add QuantumExpressionOperator enum values

doc/ex/sparse_color.rb, ext/RMagick/rmmain.c
Add some enum values of SparseColorMethod declared in ImageMagick 6.8.9.
=> Add SparseColorMethod enum values

ext/RMagick/rmmain.c
Add some enum values of MorphologyMethod declared in ImageMagick 6.8.9.
=> Add MorphologyMethod enum values

ext/RMagick/rmkinfo.c, ext/RMagick/rmmain.c
Add some enum values of KernelInfoType declared in ImageMagick 6.8.9.
=> Add KernelInfoType enum values

ext/RMagick/rmmain.c, test/Image1.rb, test/Image2.rb
Add some enum values of MetricType declared in ImageMagick 6.8.9.
=> Add MetricType enum values

ext/RMagick/rmenum.c, ext/RMagick/rmmain.c
Add some enum values of InterpolatePixelMethod declared in ImageMagick 6.8.9.
=> Add InterpolatePixelMethod enum values

ext/RMagick/rmimage.c
The allocated memory area using `ALLOC_N()` and `AcquireExceptionInfo()` cause memory leak.
* Before
```
$ ruby test.rb
Process: 27355: RSS = 185 MB
```
* After
```
$ ruby test.rb
Process: 30252: RSS = 14 MB
```
* Test code
```ruby
begin
image.recolor(['x', 1, 1, 1])
rescue
end
end
GC.start
```
=> Fix memory leak in Image#recolor

.rubocop_todo.yml, lib/rvg/misc.rb
https://rubocop.readthedocs.io/en/latest/cops_layout/#layoutalignhash
=> Rubocop: enable Layout/AlignHash rule

.rubocop_todo.yml, spec/rmagick/ImageList1_spec.rb, spec/rmagick/draw_spec.rb
https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecdescribedclass
=> Rubocop: enable RSpec/DescribedClass

ext/RMagick/rmimage.c
This pull request fixes two compiler warnings.
=> Fix compile warnings

ext/RMagick/rmagick.h, ext/RMagick/rmdraw.c, ext/RMagick/rmimage.c, ext/RMagick/rmpixel.c, ext/RMagick/rmutil.c
This also fixes some possible null reference issues and memory leaks.
=> Add rm_acquire_image to prepare for ImageMagick 7 

test/ImageList1.rb
So, if full path has the number, these tests might be failed.
Actually, forked my repository has `/home/travis/build/Watson1978/rmagick/...` path on Travis CI and it always fails.
=> Fix test using #filename method

ext/RMagick/rmutil.c
This PR improves the messages that are reported in the `rm_warning_handler` and the `rm_fatal_error_handler`.
=> Improve error reporting

.appveyor.yml, .gitignore, .rubocop.yml, .travis.yml
It slightly take a time to install depency gems.
This PR will cache the installed gems.
=> CI: Cache installed gems

ext/RMagick/rmimage.c, ext/RMagick/rmpixel.c, ext/RMagick/rmstruct.c, test/Image3.rb
This PR makes some changes to the places where Data_Get_Struct is used but the new method Color_ToPixelColor should be used instead.
=> Use conversion method

ext/RMagick/rmagick.h, ext/RMagick/rmfill.c, ext/RMagick/rmutil.c
This is a draft of changes that can be made after #523 has been merged. I created this draft PR so it can already be reviewed. Would love to get some feedback on the naming of the methods and enumeration. These methods have already been mentioned in #325. This PR includes the new methods and an example of how they can be used. I don't mind splitting this up in two pull requests but combining them will give a clearer view of how these methods will be used.
=> Fix rmfill leaks

test/Fill.rb, test/test_all_basic.rb
This patch will improve coverage of rmfill.c
* Before
- Line coverage : 0 %
- Functions : 0 %
* After
- Line coverage : 88.8 %
- Functions : 100 %
=> Add Fill tests

CHANGELOG.md, README.textile, lib/rmagick/version.rb
Also updated changelog and readme.
=> Bump version to 3.1

ext/RMagick/rmimage.c
=> Fix code style

ext/RMagick/rmagick.h, ext/RMagick/rmenum.c, ext/RMagick/rmimage.c, ext/RMagick/rmmain.c, lib/obsolete.rb, test/Enum.rb, test/Image3.rb, test/Image_attributes.rb
Renamed FilterTypes to FilterType to prepare for ImageMagick 7 and added alias for backwards compatibility.
=> Renamed FilterTypes to FilterType

ext/RMagick/rmdraw.c
Refactored the composite method of draw.
=> Refactored the composite method of draw.

test/Enum.rb
This PR renames the unit tests from #593 and #586 to something more descriptive.
=> Renamed the test methods to something more descriptive.

ext/RMagick/extconf.rb
Instead use `Gem::Version` to compare.
=> remove `MIN_RUBY_VERS_NO` constant

test/lib/Obsolete.rb, test/test_all_basic.rb
https://github.com/rmagick/rmagick/issues/588
=> Add tests of obsolete constants

test/Magick.rb, test/lib/internal/Magick.rb
https://github.com/rmagick/rmagick/issues/588
=> Add tests of Magick class

ext/RMagick/rmagick.h, ext/RMagick/rmenum.c, ext/RMagick/rmimage.c, ext/RMagick/rminfo.c, ext/RMagick/rmstruct.c, test/Enum.rb, test/Magick.rb
This PR fixes the problem for all enumeration that was reported in #593.
=> Enumerations should use the current list of values instead of creating new ones. 

ext/RMagick/rminfo.c
This PR refactors the authenticate property to have a syntax that is more similar with the view property.
=> Refactored the authenticate property.

ext/RMagick/rmimage.c
Use rm_should_raise_exception instead of checking image->exception.severity and some minor refactoring to prepare for ImageMagick 7.
=> Use rm_should_raise_exception instead of checking image->exception.severity

.rubocop_todo.yml, test/lib/internal/Geometry.rb
=> Add tests of Magick::Geometry

ext/RMagick/rmimage.c
This PR removes unnecessary calls to rm_check_image_exception.
=> Removed unnecessary calls to rm_check_image_exception

ext/RMagick/rmfill.c, ext/RMagick/rmimage.c, ext/RMagick/rmkinfo.c, ext/RMagick/rmpixel.c
This PR does a code cleanup of things that I found while working on adding support for ImageMagick 7. This also includes some minor refactor actions to get a slightly better diff with the ImageMagick 7 changes.
=> Code cleanup and some minor refactoring to prepare for ImageMagick 7.

test/lib/internal/Draw.rb
=> Add tests of Magick::Draw

ext/RMagick/rmagick.h
This is the first step in adding support for ImageMagick 7. This PR makes some changes to the rmagick.h header file that will be used in future pull requests.
=> Changes for ImageMagick 7 (rmagick.h)

ext/RMagick/rmimage.c
This pull requests fixes two compilation warnings due to the use of incorrect arguments.
=> Fix im7 compilation

.rubocop_todo.yml, spec/rmagick/image/properties_spec.rb
https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspechookargument
=> Rubocop: enable RSpec/HookArgument

test/test_all_basic.rb
As I started transitioning to `minitest/spec` syntax, I realized that
I'd need a somewhat more sophisticated return from the matcher methods,
rather than just a symbol. This does the trick.
=> RSpec: introduce new RSpecMatcher class

ext/RMagick/rmimage.c, spec/rmagick/image/store_pixels_spec.rb
This PR will support CMYK color in Image#store_pixels.
Related to #871
=> Support CMYK color in Image#store_pixels

spec/rmagick/image/get_pixels_spec.rb
=> Add spec to get proper alpha value in Image#get_pixels

ext/RMagick/rmimage.c, ext/RMagick/rmpixel.c, spec/rmagick/image/pixel_color_spec.rb
This patch will support to get CMYK color in Image#pixel_color.
Related to #871
=> Support to get CMYK color in Image#pixel_color

ext/RMagick/rmimage.c
=> Recognize invert option in Image#opaque_channel with ImageMagick 7

ext/RMagick/rmimage.c
=> Handle channel value with new image in Image#opaque_channel with ImageMagick 7

ext/RMagick/rmagick.h, ext/RMagick/rmimage.c, ext/RMagick/rmpixel.c, spec/rmagick/image/pixel_color_spec.rb
This patch will support to set CMYK color in Image#pixel_color.
Related to #871, #875
=> Support to set CMYK color in Image#pixel_color

examples/vignette.rb
=> Example: Fix alpha channel in examples/vignette.rb

doc/ex/coalesce.rb
=> Example: Fix alpha channel in doc/ex/coalesce.rb

ext/RMagick/rmpixel.c, spec/rmagick/pixel/to_color_spec.rb
=> Handle alpha value in Pixel#to_color

ext/RMagick/rmilist.c
=> Handle boolean value as dither option in ImageList#quantize

examples/demo.rb
=> Example: Remove unnecessary alpha setting

ext/RMagick/rmagick.c, ext/RMagick/rmagick.h, ext/RMagick/rmimage.c, ext/RMagick/rmpixel.c, ext/RMagick/rmutil.c
=> Add noreturn attribute to functions that only throws an exception

ext/RMagick/extconf.rb
This PR might reduce running time slightly on CI.
=> Skip some checking for generating Makefile on Windows

.github/workflows/ci.yml
Fix https://github.com/rmagick/rmagick/pull/989
=> Fix workflow to work GitHub action with Pull Request

ext/RMagick/rmagick.c, ext/RMagick/rmagick.h, ext/RMagick/rmimage.c, ext/RMagick/rmpixel.c, ext/RMagick/rmutil.c
=> Add noreturn attribute against old ImageMagick and clean up code style around noreturn attribute

ext/RMagick/rmagick.h
=> Disable GCC warning

.github/workflows/ci.yml
Refer https://github.com/ruby/setup-ruby
=> CI: Use setup action in official Ruby repository

ext/RMagick/rmimage.c
Fix https://github.com/rmagick/rmagick/issues/887
=> Fix Image#resample to use blur option properly with ImageMagick 7

ext/RMagick/rmilist.c, ext/RMagick/rminfo.c, ext/RMagick/rmmain.c, ext/RMagick/rmutil.c
Some of these might be able to in-line the assignment but I don't know
the C code well enought to judge the best format.
=> CPPCheck: reduce scope of variables in more files

ext/RMagick/rmimage.c
Related to https://github.com/rmagick/rmagick/issues/887
=> Refactor where generate blurred image before resample

ext/RMagick/rmimage.c
Fix https://github.com/rmagick/rmagick/issues/895
=> Fix Image#resize to use blur option properly with ImageMagick 7

ext/RMagick/rmenum.c, spec/rmagick/color/compliance_spec.rb
=> Fix that Color#compliance returns nil with undefined bit

ext/RMagick/extconf.rb, ext/RMagick/rmmain.c
Related to https://github.com/rmagick/rmagick/issues/1047
=> Check memory API properly on Windows

.rubocop_todo.yml, spec/rmagick/draw/clip_path_spec.rb
https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecrepeateddescription
=> Rubocop: enable RSpec/RepeatedDescription

spec/rmagick/image/read_spec.rb
https://github.com/rmagick/rmagick/pull/1072
=> Fix code comment in spec related to PDF problem

spec/rmagick/kernel_info/class_methods/builtin_spec.rb, spec/spec_helper.rb
https://github.com/rmagick/rmagick/issues/1052
=> Disable Magick::KernelInfo.builtin spec with old ImageMagick on Linux

.rubocop_todo.yml, doc/ex/composite_layers.rb, lib/rvg/to_c.rb
https://rubocop.readthedocs.io/en/stable/cops_style/#styleclassandmodulechildren
=> Rubocop: enable Style/ClassAndModuleChildren

ext/RMagick/rmagick.c
Related to https://github.com/rmagick/rmagick/issues/628
=> Yardoc: Replace Doxygen format in rmagick.c

.rubocop_todo.yml, doc/ex/composite_layers.rb, lib/rmagick_internal.rb, lib/rvg/embellishable.rb, lib/rvg/misc.rb, lib/rvg/transformable.rb, spec/rmagick/image/export_pixels_spec.rb, spec/rmagick/image/import_pixels_spec.rb, spec/rmagick/image_list/collect_spec.rb, spec/rmagick/image_list/find_all_spec.rb, spec/rmagick/image_list_spec.rb
https://rubocop.readthedocs.io/en/stable/cops_style/#stylecollectionmethods
=> Rubocop: enable Style/CollectionMethods

.rubocop_todo.yml, ext/RMagick/extconf.rb
https://rubocop.readthedocs.io/en/stable/cops_style/#styledatetime
=> Rubocop: enable Style/DateTime

.rubocop_todo.yml, lib/rmagick_internal.rb, lib/rvg/units.rb
https://rubocop.readthedocs.io/en/stable/cops_style/#styleevalwithlocation
=> Rubocop: enable Style/EvalWithLocation

before_install_linux.sh
Try to solve following error in setup script.
```
…
E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/i/icu/libicu-dev_64.2-0.1+ubuntu18.04.1+deb.sury.org+1_amd64.deb  404  Not Found [IP: 91.189.95.83 80]
316
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
317
Fetched 1942 kB in 2s (1203 kB/s)
```
=> CI: Add “sudo apt-get update” into setup script

ext/RMagick/rmfill.c
=> Yardoc: Replace Doxygen format in rmfill.c

ext/RMagick/rmdraw.c
=> Yardoc: Fix default value style

ext/RMagick/rmilist.c
=> Yardoc: Replace Doxygen format in rmilist.c

ext/RMagick/rmenum.c
=> Yardoc: Replace Doxygen format in rmenum.c

ext/RMagick/rmstruct.c
=> Yardoc: Replace Doxygen format in rmstruct.c

ext/RMagick/rmpixel.c
=> Yardoc: Replace Doxygen format in rmpixel.c

ext/RMagick/rmutil.c
=> Yardoc: Replace Doxygen format in rmutil.c

ext/RMagick/rmmontage.c
=> Yardoc: Replace Doxygen format in rmmontage.c

ext/RMagick/rmkinfo.c
=> Yardoc: Replace Doxygen format in rmkinfo.c

.rubocop.yml, .rubocop_todo.yml
https://rubocop.readthedocs.io/en/stable/cops_style/#styleguardclause
=> Rubocop: enable Style/GuardClause

ext/RMagick/rminfo.c
=> Yardoc: Replace Doxygen format in rminfo.c

.rubocop_todo.yml, lib/rvg/misc.rb
https://rubocop.readthedocs.io/en/stable/cops_style/#stylestringmethods
=> Rubocop: enable Style/StringMethods

ext/RMagick/rmimage.c
=> Yardoc: Replace Doxygen format in rmimage.c

ext/RMagick/rmagick.c, ext/RMagick/rmenum.c, ext/RMagick/rmimage.c, ext/RMagick/rmpixel.c
=> Yardoc: Fix collection type of array in @return and @param

ext/RMagick/rmdraw.c
=> Yardoc: Fix attribute method description

ext/RMagick/rmmain.c
Forgot to remove this at https://github.com/rmagick/rmagick/pull/1128
=> Remove unused observable variable

before_install_linux.sh
This patch will solve error in https://github.com/rmagick/rmagick/actions/runs/51627692
Refer to https://stackoverflow.com/a/39246092
=> Add workaround for “Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?” error

ext/RMagick/rmilist.c, ext/RMagick/rmimage.c
Because rm_ensure_result() is not called in some places.
=> Call rm_ensure_result() in creating Image object

ext/RMagick/rmdraw.c, ext/RMagick/rmfill.c, ext/RMagick/rmilist.c, ext/RMagick/rmimage.c, ext/RMagick/rmmontage.c
=> Yardoc: Fix description in the method using rm_cur_image

ext/RMagick/rmimage.c, ext/RMagick/rmutil.c
Reverts rmagick/rmagick#1146
https://github.com/rmagick/rmagick/pull/1146#discussion_r389346355
=> Revert "Call rm_ensure_result() in rm_set_user_artifact()"

ext/RMagick/rmagick.c, ext/RMagick/rmdraw.c, ext/RMagick/rmimage.c, ext/RMagick/rminfo.c, ext/RMagick/rmmontage.c, ext/RMagick/rmpixel.c, ext/RMagick/rmstruct.c, ext/RMagick/rmutil.c
Because StringValuePtr() returns C-lang string which might not have null-terminate.
And the string will cause a crash with almost APIs.
=> Use StringValueCStr() instead of StringValuePtr()

ext/RMagick/rmagick.c, ext/RMagick/rmdraw.c, ext/RMagick/rmilist.c
=> Yardoc: Fix description of return where overload methods return same value

ext/RMagick/rmdraw.c, spec/rmagick/draw/marshal_dump_spec.rb
Close https://github.com/rmagick/rmagick/issues/188
=> Fix SEGV in Magick::Draw#marshal_load

spec/rmagick/draw/annotate_spec.rb
Close https://github.com/rmagick/rmagick/issues/38
=> Add Draw#annotate spec

doc/ex/preview.rb
https://github.com/rmagick/rmagick/issues/1160
=> Example: Update preview example to generate all preview images

ext/RMagick/rmdraw.c, ext/RMagick/rmilist.c, ext/RMagick/rmimage.c, ext/RMagick/rmkinfo.c, ext/RMagick/rmmontage.c, ext/RMagick/rmpixel.c
=> Yardoc: Update methods description

.yardopts, lib/rvg/clippath.rb, lib/rvg/container.rb, lib/rvg/describable.rb, lib/rvg/embellishable.rb, lib/rvg/paint.rb, lib/rvg/pathdata.rb, lib/rvg/rvg.rb, lib/rvg/text.rb, lib/rvg/transformable.rb
=> Yardoc: Use @private primitive instead of :nodoc: for yard

lib/rmagick_internal.rb
=> Yardoc: Add missing document in Magick module

README.md
Close https://github.com/rmagick/rmagick/issues/31
=> Update setup operation

examples/pango.rb, examples/pango_sample.pango
Close https://github.com/rmagick/rmagick/issues/274
=> Add a sample that uses pango

spec/rmagick/image/add_profile_spec.rb
Close https://github.com/rmagick/rmagick/issues/286
=> Add Image#add_profile spec to check that the profile was added into image

before_install_osx.sh
Because the updating homebrew will spend a time.
=> CI: Install libraries without auto updating homebrew

.github/ISSUE_TEMPLATE.md
Imported from https://github.com/ImageMagick/ImageMagick/tree/master/.github
=> GitHub: Add Issue template

ext/RMagick/rmimage.c
The signal handler settings have a system-wide impact.
It seems that in some cases the app won't work properly if it just restore the signal handling to the default.
At least, the gem of CarrierWave gem is failed with RMagick 4.1.0.
To make more safety, this patch restores the handlers that had been configured instead of restoring the defaults.
Related https://github.com/rmagick/rmagick/pull/1072
=> Fix bug of signal handling internally

README.md
close https://github.com/rmagick/rmagick/issues/834
=> Add setup instruction for Arch Linux / Alpine Linux

ext/RMagick/extconf.rb, ext/RMagick/rmmain.c
https://github.com/rmagick/rmagick/issues/1197
=> Fix build error on Freebsd

spec/rmagick/image/channel_spec.rb, spec/rmagick/image/charcoal_spec.rb, spec/spec_helper.rb, spec/support/helpers.rb
Extracted helpers from charcoal_spec to use in channel_spec
=> RSpec: Flesh out channel_spec

.github/workflows/ci.yml
Related to https://github.com/rmagick/rmagick/issues/1210
=> CI: Update ImageMagick versions

spec/rmagick/draw/annotate_spec.rb, spec/rmagick/draw/composite_spec.rb, spec/rmagick/draw/draw_spec.rb, spec/rmagick/draw/get_multiline_type_metrics_spec.rb, spec/rmagick/draw/get_type_metrics_spec.rb, spec/rmagick/image/blend_spec.rb, spec/rmagick/image/compare_channel_spec.rb, spec/rmagick/image/composite_bang_spec.rb, spec/rmagick/image/composite_mathematics_spec.rb, spec/rmagick/image/composite_spec.rb, spec/rmagick/image/composite_tiled_spec.rb, spec/rmagick/image/difference_spec.rb, spec/rmagick/image/displace_spec.rb, spec/rmagick/image/dissolve_spec.rb, spec/rmagick/image/distortion_channel_spec.rb, spec/rmagick/image/find_similar_region_spec.rb, spec/rmagick/image/mask_spec.rb, spec/rmagick/image/remap_spec.rb, spec/rmagick/image/stegano_spec.rb, spec/rmagick/image/stereo_spec.rb, spec/rmagick/image/texture_floodfill_spec.rb, spec/rmagick/image/watermark_spec.rb, spec/rmagick/image_list/montage/texture_writer_spec.rb, spec/rmagick/image_list/remap_spec.rb, spec/rmagick/texture_fill/initialize_spec.rb
Related to https://github.com/rmagick/rmagick/issues/1211
=> RSpec: Add specs to confirm that the methods accept ImageList object as argument

spec/rmagick/image/read_spec.rb, spec/support/issue_200/app.rb
Because issue #200 should be solved by #351
=> RSpec: Enable Magick::Image#read spec

spec/rmagick/image/channel_entropy_spec.rb, spec/spec_helper.rb, spec/support/helpers.rb
Add `pixels` keyword argument to `build_image` helper
=> Flesh out channel_entropy_spec.

CODE_OF_CONDUCT.md
Taken from the [Contributor Covenant][covenant] without any edits, aside
from contact email.
[covenant]: https://www.contributor-covenant.org/
=> update code of conduct to version 2.0

ext/RMagick/extconf.rb, ext/RMagick/rmmain.c
This PR adds some new colorspaces. This fixes #1245.
=> Added new colorspaces.

.github/workflows/ci.yml, README.md
I just deleted the section from the README, since it no longer applies
to our current workflow.
=> update branch references from master to main

.github/workflows/ci.yml
The variable `$imagemagick_version_without_patch` is not used anywhere in `ci.yml` file, 
so I think don't need to define the variable.
Please consider this.
Thank you.
=> [delete] unused variable

.github/workflows/ci.yml, ext/RMagick/extconf.rb
https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/
This patch will avoid build error at https://github.com/rmagick/rmagick/issues/1314
Close https://github.com/rmagick/rmagick/issues/1314
=> Fix build error with Ruby 3.1 on macOS

ext/RMagick/extconf.rb
When installing and using ImageMagick 7 into an arbitrary path on Linux, it might fail to lookup dynamic lib of ImageMagick 7 from rmagick.
- Install ImageMagick7
```
$ ./configure --prefix=$HOME/imagemagick-7.1
$ make -j install
```
- Run rmagick spec
```
$ export PKG_CONFIG_PATH=$HOME/imagemagick-7.1/lib/pkgconfig
$ rake spec
mkdir -p tmp/x86_64-linux/RMagick2/3.1.1
cd tmp/x86_64-linux/RMagick2/3.1.1
/home/watson/.rbenv/versions/3.1.1/bin/ruby -I. -r.rake-compiler-siteconf.rb ../../../../ext/RMagick/extconf.rb
checking for brew... no
checking for pacman... no
checking for Ruby version >= 2.3.0... yes
checking for pkg-config... yes
checking for forced use of ImageMagick 6... no
checking for outdated ImageMagick version (<= 6.7.7)... no
checking for gcc... yes
checking for __GNUC__... yes …
```
=> Specify rpath linker option to fix dynamic lib lookup failure on Linux

.github/workflows/ci.yml
Ref. https://github.com/actions/checkout
=> CI: Update GitHub checkout action to v3

.rubocop_todo.yml, deprecated/RMagick.rb, ext/RMagick/rmmain.c, ext/RMagick/rmutil.c, rmagick.gemspec
- ❌ `require 'RMagick'`
- ✔️ `require 'rmagick'`
=> Remove deprecated RMagick.rb file

Rakefile, doc/image1.html
Added task to update website.
See https://github.com/rmagick/rmagick.github.io/pull/2, it was generated using this task.
=> Add website:update task to update RMagick website

README.md
Because it seems to be not worked.
=> README: Remove codacy badge

ext/RMagick/extconf.rb, ext/RMagick/rmdraw.c
This patch will suport GC compaction.
Ref. https://blog.peterzhu.ca/ruby-c-ext-part-7/
=> Support GC compaction

spec/spec_helper.rb
Close https://github.com/rmagick/rmagick/issues/1267
=> Spec: Verify GC compaction

doc/image1.html, doc/image2.html, doc/image3.html
Fix https://github.com/rmagick/rmagick/issues/1394
=> Doc: Fix wrong links

before_install_osx.sh
This patch will solve build error in https://github.com/rmagick/rmagick/actions/runs/5302266822/jobs/9597163050
=> CI: Fix build error on macOS

doc/constants.html, doc/index.html, ext/RMagick/rmmain.c
RubyForge already has been shutdown.
https://www.infoq.com/news/2009/10/rubyforge-phased-out-rubygemsorg/
=> Doc: Fix dead links

doc/constants.html, doc/image1.html, doc/imageattrs.html, doc/optequiv.html
This patch will add missing constants defined in rmmain.c into documents.
=> Doc: Add missing constants into documents

ext/RMagick/extconf.rb, ext/RMagick/rmagick.h, ext/RMagick/rmilist.c, ext/RMagick/rmimage.c, ext/RMagick/rmutil.c
https://github.com/ruby/ruby/pull/7916
=> Use rb_io_path() if exist because pathv attr was marked as deprecated at Ruby 3.3

ext/RMagick/rmenum.c, ext/RMagick/rmpixel.c
=> Rename `this` variable names because it is reserved word in C++

before_install_osx.sh
Related to https://github.com/rmagick/rmagick/actions/runs/7587638291/job/20668439388
=> CI: Disable JPEG-XL support to fix build error on macOS

.github/workflows/ci.yml, spec/rmagick/image/gamma_spec.rb
Fix https://github.com/rmagick/rmagick/issues/1429
=> CI: Update ImageMagick 7 outside Windows

.editorconfig, .github/workflows/ci.yml, .gitignore, .yardopts, ext/RMagick/extconf.rb, ext/RMagick/rmagick.cpp, ext/RMagick/rmagick.h, ext/RMagick/rmdraw.cpp, ext/RMagick/rmenum.cpp, ext/RMagick/rmfill.cpp, ext/RMagick/rmilist.cpp, ext/RMagick/rmimage.cpp, ext/RMagick/rminfo.cpp, ext/RMagick/rmkinfo.cpp, ext/RMagick/rmmain.cpp, ext/RMagick/rmmontage.cpp, ext/RMagick/rmpixel.cpp, ext/RMagick/rmstruct.cpp, ext/RMagick/rmutil.cpp, spec/magick_spec.rb, spec/rmagick/class_methods/formats_spec.rb, spec/rmagick/class_methods/init_formats_spec.rb
Fix https://github.com/rmagick/rmagick/issues/1419
=> Use C++ compiler

ext/RMagick/rmimage.cpp
Related to https://github.com/rmagick/rmagick/pull/1352
=> Release GVL in Image#contrast

ext/RMagick/extconf.rb
https://github.com/rmagick/rmagick/issues/1451
https://github.com/rmagick/rmagick/pull/1433
=> Check C++ compiler exists

ext/RMagick/rmimage.cpp, spec/rmagick/image/clut_channel_spec.rb
Similar with https://github.com/rmagick/rmagick/pull/1467
=> Fix Image#clut_channel to accept ImageList object

ext/RMagick/rmagick.h, ext/RMagick/rmmain.cpp
Related to https://github.com/rmagick/rmagick/pull/1476
=> Add DrawAttribute module to simplify Draw, DrawOptions and PolaroidOptions

.rubocop_todo.yml, lib/rmagick_internal.rb, spec/rmagick/image_list/eql_predicate_spec.rb
Similar with https://github.com/rmagick/rmagick/pull/1478
=> Fix ImageList#eql? that should not raise exception if can't compare

ext/RMagick/rmimage.cpp, spec/rmagick/image/add_compose_mask_spec.rb
Similar with https://github.com/rmagick/rmagick/pull/1467
=> Fix Image#add_compose_mask to accept ImageList object

ext/RMagick/rmimage.cpp, spec/rmagick/image/composite_affine_spec.rb
Similar with https://github.com/rmagick/rmagick/pull/1467
=> Fix Image#composite_affine to accept ImageList object

lib/rmagick_internal.rb
Use assert_image_array for type checking, these methods accept ImageList or an Array.
=> Simplify type check in ImageList#{&, +, -, |}

ext/RMagick/rmdraw.cpp, ext/RMagick/rmilist.cpp, ext/RMagick/rmimage.cpp, ext/RMagick/rminfo.cpp, ext/RMagick/rmpixel.cpp, lib/rmagick_internal.rb
Fix type information for yard.
(you can see at https://www.rubydoc.info/gems/rmagick/ )
=> Doc: Fix types

ext/RMagick/extconf.rb
Fix https://github.com/rmagick/rmagick/issues/1500
=> Add PKG_CONFIG_PATH for ImageMagick 7 in order to fix installation error on macOS

ext/RMagick/rmutil.cpp
Fix https://github.com/rmagick/rmagick/issues/1404
=> Sync compression value in order fix  the problem of compression being ignored by ImageMagick 7

lib/rvg/misc.rb
Related to https://github.com/rmagick/rmagick/pull/1509
=> Fix GraphicContext#font_weight to accept Numeric object

ext/RMagick/rmkinfo.cpp, spec/rmagick/kernel_info/scale_spec.rb
Similar with https://github.com/rmagick/rmagick/pull/1489
=> Remove unnecessary type check in KernelInfo#{unity_add, scale}

before_install_osx.sh
https://github.com/rmagick/rmagick/actions/runs/8556356877/job/23447088209?pr=1458
=> CI: Disable openjpeg support to fix build error on macOS

.github/workflows/ci.yml, ext/RMagick/extconf.rb, spec/rmagick/image/mime_type_spec.rb
Fix https://github.com/rmagick/rmagick/issues/1584
=> Fix install error on Windows MINGW environment

.rubocop_todo.yml, lib/rmagick_internal.rb, sig/rmagick/_image_common_methods.rbs, sig/rmagick/image.rbs, sig/rmagick/image_list.rbs, spec/rmagick/image_list/destroy_bang_spec.rb, spec/rmagick/image_list/destroyed_spec.rb
Fix https://github.com/rmagick/rmagick/issues/30
=> Fix ImageList#destroy! that should destroy all internal image objects

CHANGELOG.md, ext/RMagick/rmimage.cpp, spec/rmagick/image/from_blob_spec.rb, spec/rmagick/image/new_spec.rb, spec/rmagick/image/read_inline_spec.rb, spec/rmagick/image/read_spec.rb
Fix https://github.com/rmagick/rmagick/issues/25
=> Sync Image::Info attributes to image object

doc/ex/demo.rb
Related to https://github.com/rmagick/rmagick/pull/1607
=> Doc: Fix file path in demo

doc/ex/bounding_box.rb
Related to https://github.com/rmagick/rmagick/pull/1610
=> Doc: Specify fill_opacity in sample

before_install_linux.sh
Related to https://github.com/rmagick/rmagick/actions/runs/9489141270/job/26171724672
=> CI: Fix library install error on Linux lane

.rubocop_todo.yml, rmagick.gemspec
Ref. https://guides.rubygems.org/mfa-requirement-opt-in/
=> Enable Multi-Factor Authentication for privileged operations

before_install_osx.sh
Fix https://github.com/rmagick/rmagick/actions/runs/9558822769/job/26348152946?pr=1644
=> CI: Ensure to install glib on macOS

ext/RMagick/extconf.rb
The installer checked for multiple ImageMagick installations on the system.
However, the binary path used for checking may differ from the library path actually used during installation.
At the time of installation, it use the package information indicated by PKG_CONFIG_PATH.
So, this patch will remove unhelpful checks.
=> Remove multiple imagemagick version checks

lib/rvg/pathdata.rb, spec/rmagick/rvg/path_data/moveto_spec.rb
Fix https://github.com/rmagick/rmagick/issues/1673
=> Fix FrozenError in Magick::RVG::PathData
